---
title: "03_gradient_netviz"
output: html_document
date: "2023-05-31"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message=FALSE}
library(SpiecEasi)
library(igraph)
library(ggnetwork)
library(intergraph)
library(ggpubr)

options(bitmapType='cairo')

```

Get metadata and otu names for each plot network

```{r}
fung_data <- readRDS("~/cmaiki_lts/kaciekaj/waimea/intermediates/gradient/terrestrial/six_empos_fung_grad_data_ordered.rds")
bact_data <- readRDS("~/cmaiki_lts/kaciekaj/waimea/intermediates/gradient/terrestrial/six_empos_bact_grad_data_ordered.rds")


fung_meta_terr <- readRDS("../../intermediates/gradient/terrestrial/fung_terrestrial_metadata.rds")
bact_meta_terr <- readRDS("../../intermediates/gradient/terrestrial/bact_terrestrial_metadata.rds")

```

## Fungi

```{r}

fung_gradient_networks <- readRDS("../../networks/prev20/gradient/outputs/terrestrial/six_empos_fung_gradient_networks_minlam1e5.rds")

fung_vertex_names <- lapply(fung_data, rownames)

lapply(fung_gradient_networks, function(x) sum(getRefit(x))/2)

# getOptInd(se)
# 
# sum(getRefit(se))/2


fung_igraphs <- list()

for (i in 1:length(fung_gradient_networks)) {
  ig <- adj2igraph(getRefit(fung_gradient_networks[[i]]),
                   vertex.attr=list(name=fung_vertex_names[[i]]))
  
  fung_igraphs[[i]] <- ig
}


fung_no_dummy <- lapply(fung_igraphs, function(x) delete_vertices(x, "dummy"))

saveRDS(fung_no_dummy, "../../intermediates/gradient/terrestrial/fung_gradient_igraphs.rds")


## visualization
fung_no_dummy <- readRDS("../../intermediates/gradient/terrestrial/fung_gradient_igraphs.rds")

plots <- unique(fung_meta_terr$site_name)


fung_net_plots <- list()

for (i in 1:length(fung_no_dummy)) {
  set.seed(123)
  
  gg <- ggplot(ggnetwork(asNetwork(fung_no_dummy[[i]]), layout = "fruchtermanreingold"), aes(x = x, y = y, xend = xend, yend = yend)) +
  geom_edges(color = "grey20", linewidth = 0.1) +
  geom_nodes(color = "#1F78B4") +
  theme_blank() +
  #scale_color_brewer(palette = "Paired") + # "#A6CEE3" "#1F78B4"
  labs(title = plots[i])
  
  fung_net_plots[[i]] <- gg
}

names(fung_net_plots) <- plots

fung_net_plots <- fung_net_plots[c("Beach", "Estuary", "Entrance", "Confluence", "Waterfall", "DrumRoad", "Ridge")]

all_fung <- ggarrange(plotlist=fung_net_plots,
                      ncol = 4,
                      nrow = 2) + bgcolor("white")

ggsave("../../figures/finals/gradient/fung_gradient_network_plots.pdf", width=20, height=9.5)

```

## Bacteria

```{r}
bact_vertex_names <- lapply(bact_data, rownames)


# getOptInd(se)
# 
# sum(getRefit(se))/2

bact_gradient_networks <- readRDS("../../networks/prev20/gradient/outputs/terrestrial/six_empos_bact_gradient_networks.rds")



bact_igraphs <- list()

for (i in 1:length(bact_gradient_networks)) {
  ig <- adj2igraph(getRefit(bact_gradient_networks[[i]]),
                   vertex.attr=list(name=bact_vertex_names[[i]]))
  
  bact_igraphs[[i]] <- ig
}


bact_no_dummy <- lapply(bact_igraphs, function(x) delete_vertices(x, "dummy"))

saveRDS(bact_no_dummy, "../../intermediates/gradient/terrestrial/bact_gradient_igraphs.rds")


## visualization
bact_no_dummy <- readRDS("../../intermediates/gradient/terrestrial/bact_gradient_igraphs.rds")

bact_net_plots <- list()

for (i in 1:length(bact_no_dummy)) {
  set.seed(123)
  
  gg <- ggplot(ggnetwork(asNetwork(bact_no_dummy[[i]]), layout = "fruchtermanreingold"), aes(x = x, y = y, xend = xend, yend = yend)) +
  geom_edges(color = "grey20", linewidth = 0.1) +
  geom_nodes(color = "#A6CEE3") +
  theme_blank() +
  #scale_color_brewer(palette = "Paired") + # "#A6CEE3" "#1F78B4"
  labs(title = plots[i])
  
  bact_net_plots[[i]] <- gg
}

names(bact_net_plots) <- plots

bact_net_plots <- bact_net_plots[c("Beach", "Estuary", "Entrance", "Confluence", "Waterfall", "DrumRoad", "Ridge")]


all_bact <- ggarrange(plotlist = bact_net_plots,
                      ncol = 4,
                      nrow = 2) + bgcolor("white")

ggsave("../../figures/finals/gradient/bact_gradient_network_plots.pdf", all_bact, width=20, height=9.5)




sum(getRefit(se))/2

```


## Cross-domain

```{r}

cross_gradient_networks <- readRDS("../../networks/prev20/gradient/outputs/terrestrial/six_empos_cross_gradient_networks.rds")


cross_vertex_names <- list()

for (i in 1:7) {
  cross_names <- c(fung_vertex_names[[i]], bact_vertex_names[[i]])
  cross_vertex_names[[i]] <- cross_names
}
 

cross_igraphs <- list()

for (i in 1:length(cross_gradient_networks)) {
  ig <- adj2igraph(getRefit(cross_gradient_networks[[i]]),
                   vertex.attr=list(name=cross_vertex_names[[i]]))
  
  cross_igraphs[[i]] <- ig
}


cross_no_dummy <- lapply(cross_igraphs, function(x) delete_vertices(x, "dummy"))
cross_no_dummy <- lapply(cross_no_dummy, function(x) delete_vertices(x, "dummy"))

saveRDS(cross_no_dummy, "../../intermediates/gradient/terrestrial/cross_gradient_igraphs.rds")


## visualization
cross_no_dummy <- readRDS("../../intermediates/gradient/terrestrial/cross_gradient_igraphs.rds")

cross_net_plots <- list()

for (i in 1:length(cross_no_dummy)) {
  set.seed(123)
  
  dat <- ggnetwork(asNetwork(cross_no_dummy[[i]]), layout = "fruchtermanreingold")
  dat$domain <- ifelse(grepl("fung", dat$vertex.names), "Fungi", "Bacteria")

  
  gg <- ggplot(dat, aes(x = x, y = y, xend = xend, yend = yend)) +
  geom_edges(color = "grey20", linewidth = 0.1) +
  geom_nodes(aes(color = domain)) +
  theme_blank() +
  scale_color_brewer(palette = "Paired") + # "#A6CEE3" "#1F78B4"
  labs(title = plots[i], color = "Kingdom")
  
  cross_net_plots[[i]] <- gg
}


names(cross_net_plots) <- plots

cross_net_plots <- cross_net_plots[c("Beach", "Estuary", "Entrance", "Confluence", "Waterfall", "DrumRoad", "Ridge")]

all_cross <- ggarrange(plotlist = cross_net_plots,
                      ncol = 4,
                      nrow = 2,
                      common.legend = TRUE,
                      legend="bottom") + bgcolor("white")

ggsave("../../figures/finals/gradient/cross_gradient_network_plots.pdf", width=20, height=9.5)

```





