---
title: "05a_gradient_nat_connectivity"
output: html_document
date: "2023-08-22"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message=FALSE}
library(igraph)
library(pulsar)
library(data.table)
```

```{r}
# import igraph objects
fung_igraphs <- readRDS("../../intermediates/gradient/terrestrial/fung_gradient_igraphs.rds")
bact_igraphs <- readRDS("../../intermediates/gradient/terrestrial/bact_gradient_igraphs.rds")
cross_igraphs <- readRDS("../../intermediates/gradient/terrestrial/cross_gradient_igraphs.rds")

```


```{r}
# test 
g = fung_igraphs[[3]]

nat_conn <- function(g) {
  orig_max <- max(components(g)$csize)
  n <- vcount(g)
  
  removed.pct <- seq.int(0, 1, length.out=n+1L)
  
  max.comp.removed <- rep.int(orig_max, n)
  
  natural_connectivity <- natural.connectivity(get.adjacency(g, sparse = TRUE))
  
  val <- centr_betw(g)$res
  ord <- V(g)$name[order(val, decreasing=TRUE)]
  
  seq_nets <- list()
  seq_adj <- list()
  
  for (j in seq_len(n - 1L)) {
    g <- delete_vertices(g, ord[j])
    
    seq_nets[[j]] <- g
    
    seq_adj[[j]] <- get.adjacency(g, sparse = TRUE)
    #max.comp.removed[j + 1L] <- max(components(g)$csize)
    #natural_connectivity[j + 1L] <- natural.connectivity(get.adjacency(g))
  }
  
  lapp_test <- lapply(seq_adj, pulsar::natural.connectivity)
  
  test <- pbmclapply(seq_adj, pulsar::natural.connectivity, mc.cores = detectCores() - 1)
  test2 <- append(natural_connectivity, test)
  
  #max.comp.removed <- c(max.comp.removed, 0)
  comp.pct <- max.comp.removed / orig_max
  out <- data.table(comp.size=max.comp.removed, nc = unlist(test2),
                    comp.pct=comp.pct, removed.pct=removed.pct[1:length(removed.pct)-1])
  return(out)
}


b <- ggplot(out, aes(x=removed.pct, y=nc)) +
  geom_point() +
  labs(x="Percentage of nodes removed", y="Natural Connectivity") +
  theme(legend.key = element_rect(fill="white")) +
  theme(panel.border = element_blank(), panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(), axis.line = element_line(colour = "black"),
        panel.background=element_blank(),
        axis.title = element_text(size=14)) +
  #scale_color_manual(values=c("#D81B60", "#1E88E5", "#DEA805")) +
  theme(legend.text = element_text(size=12)) +
   theme(legend.title = element_text(size=14)) +
   guides(color = guide_legend(override.aes = list(size=8))) +
  theme(axis.title.y = element_text(margin = margin(t = 0, r = 10, b = 0, l = 0))) +
  theme(axis.title.x = element_text(margin = margin(t = 10, r = 0, b = 0, l = 0))) +
  scale_x_continuous(limits = c(0,1), expand = c(0, 0)) 
  #scale_y_continuous(limits = c(0,1), expand = c(0, 0)) 
```
