---
title: "05_gradient_robustness"
output: html_document
date: "2023-06-06"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(brainGraph)
```

```{r}
# import igraph objects
fung_igraphs <- readRDS("../../intermediates/gradient/terrestrial/fung_gradient_igraphs.rds")
bact_igraphs <- readRDS("../../intermediates/gradient/terrestrial/bact_gradient_igraphs.rds")
cross_igraphs <- readRDS("../../intermediates/gradient/terrestrial/cross_gradient_igraphs.rds")

# metadata
fung_meta_terr <- readRDS("../../intermediates/gradient/terrestrial/fung_terrestrial_metadata.rds")
bact_meta_terr <- readRDS("../../intermediates/gradient/terrestrial/bact_terrestrial_metadata.rds")

plots <- unique(fung_meta_terr$site_name)
```


```{r}
# robustness test

fung_rob <- lapply(fung_igraphs, function(x) robustness(x, type="vertex", "degree"))
for (i in 1:7) {
  df <- fung_rob[[i]]
  df$domain <- "Fungi"
  df$plot <- plots[[i]]
  
  fung_rob[[i]] <- df
}
fung_deg_rob <- do.call("rbind", fung_rob)
fung_deg_rob$plot <- factor(fung_deg_rob$plot, levels=c("Beach", "Estuary", "Entrance", "Confluence", "Waterfall", "DrumRoad", "Ridge"))


test_mod <- glmmTMB(comp.pct ~ 1 + (1|plot), data = fung_deg_rob)
summary(test_mod)

library(car)
anova(test_mod)

# 
# bact_rob <- lapply(bact_igraphs, function(x) robustness(x, type="vertex", "degree"))
# for (i in 1:7) {
#   df <- bact_rob[[i]]
#   df$domain <- "16S"
#   df$plot <- plots[[i]]
#   
#   bact_rob[[i]] <- df
# }
# bact_deg_rob <- do.call("rbind", bact_rob)
# bact_deg_rob$plot <- factor(bact_deg_rob$plot, levels=c("Beach", "Estuary", "Entrance", "Confluence", "Waterfall", "DrumRoad", "Ridge"))
# 
# 
# cross_rob <- lapply(cross_igraphs, function(x) robustness(x, type="vertex", "degree"))
# for (i in 1:7) {
#   df <- cross_rob[[i]]
#   df$domain <- "Cross"
#   df$plot <- plots[[i]]
#   
#   cross_rob[[i]] <- df
# }
# cross_deg_rob <- do.call("rbind", cross_rob)
# cross_deg_rob$plot <- factor(cross_deg_rob$plot, levels=c("Beach", "Estuary", "Entrance", "Confluence", "Waterfall", "DrumRoad", "Ridge"))
# 
# 
# 
# all_node_robustness_degree <- do.call("rbind", list(fung_deg_rob, bact_deg_rob, cross_deg_rob))
# 
# 
# deg_plot_by_domain <- ggplot(all_node_robustness_degree, aes(x=removed.pct, y=comp.pct, group=domain, color=domain)) +
#   geom_line() +
#   labs(x="Percentage of nodes removed", y="Size of largest connected component",
#        title="Degree-based attack")
# 
# ggsave("../figures/gradient/degree_robustness_by_domain.jpg", width=7, height=5)
# 
# 
# deg_its_plot <- ggplot(fung_deg_rob, aes(x=removed.pct, y=comp.pct, group=plot, color=plot)) +
#   geom_line() +
#   labs(x="Percentage of nodes removed", y="Size of largest connected component",
#        title="ITS, Degree-based attack")
# 
# deg_16s_plot <- ggplot(bact_deg_rob, aes(x=removed.pct, y=comp.pct, group=plot, color=plot)) +
#   geom_line() +
#   labs(x="Percentage of nodes removed", y="Size of largest connected component",
#        title="16S, Degree-based attack")
# 
# deg_cross_plot <- ggplot(cross_deg_rob, aes(x=removed.pct, y=comp.pct, group=plot, color=plot)) +
#   geom_line() +
#   labs(x="Percentage of nodes removed", y="Size of largest connected component",
#        title="Cross-domain, Degree-based attack")
# 
# ggarrange(deg_its_plot, deg_16s_plot, deg_cross_plot, common.legend = TRUE, legend="right", nrow = 1) + bgcolor("white")
# 
# ggsave("../figures/gradient/degree_robustness.jpg", width=18, height=5)


```

```{r}
# robustness test
  
fung_rob_bc <- lapply(fung_igraphs, function(x) robustness(x, type="vertex", "btwn.cent"))
for (i in 1:7) {
  df <- fung_rob_bc[[i]]
  df$domain <- "Fungi"
  df$plot <- plots[[i]]
  
  fung_rob_bc[[i]] <- df
}
fung_bc_rob <- do.call("rbind", fung_rob_bc)
fung_bc_rob$plot <- factor(fung_bc_rob$plot, levels=c("Beach", "Estuary", "Entrance", "Confluence", "Waterfall", "DrumRoad", "Ridge"))


bact_rob_bc <- lapply(bact_igraphs, function(x) robustness(x, type="vertex", "btwn.cent"))
for (i in 1:7) {
  df <- bact_rob_bc[[i]]
  df$domain <- "Bacteria"
  df$plot <- plots[[i]]
  
  bact_rob_bc[[i]] <- df
}
bact_bc_rob <- do.call("rbind", bact_rob_bc)
bact_bc_rob$plot <- factor(bact_bc_rob$plot, levels=c("Beach", "Estuary", "Entrance", "Confluence", "Waterfall", "DrumRoad", "Ridge"))


cross_rob_bc <- lapply(cross_igraphs, function(x) robustness(x, type="vertex", "btwn.cent"))
for (i in 1:7) {
  df <- cross_rob_bc[[i]]
  df$domain <- "Cross"
  df$plot <- plots[[i]]
  
  cross_rob_bc[[i]] <- df
}
cross_bc_rob <- do.call("rbind", cross_rob_bc)
cross_bc_rob$plot <- factor(cross_bc_rob$plot, levels=c("Beach", "Estuary", "Entrance", "Confluence", "Waterfall", "DrumRoad", "Ridge"))



all_node_robustness_bc <- do.call("rbind", list(fung_bc_rob, bact_bc_rob, cross_bc_rob))

saveRDS(all_node_robustness_bc, "../../intermediates/gradient/terrestrial/robustness_data_by_plot.rds")

# bc_plot_by_domain <- ggplot(all_node_robustness_bc, aes(x=removed.pct, y=comp.pct, group=domain, color=domain)) +
#   geom_line() +
#   labs(x="Percentage of nodes removed", y="Size of largest connected component",
#        title="Betweenness-based attack")
# 
# ggsave("../../figures/gradient/terrestrial/btwn_cent_robustness_by_domain.jpg", width=7, height=5)


bc_its_plot <- ggplot(fung_bc_rob, aes(x=removed.pct, y=comp.pct, group=plot, color=plot)) +
  geom_line(linewidth=1.5) +
  labs(x="Percentage of nodes removed", y="Size of largest connected component",
       title="Fungi", color="Plot") +
  theme(legend.key = element_rect(fill="white")) +
  theme(panel.border = element_blank(), panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(), axis.line = element_line(colour = "black"),
        panel.background=element_blank(),
        axis.title = element_text(size=14),
        title=element_text(size=16)) +
  theme(legend.text = element_text(size=12)) +
   theme(legend.title = element_text(size=14)) +
  #theme(plot.margin = margin(0,25,0,0)) +
   guides(color = guide_legend(override.aes = list(size=8))) +
  theme(axis.title.y = element_text(margin = margin(t = 0, r = 10, b = 0, l = 0))) +
  theme(axis.title.x = element_text(margin = margin(t = 10, r = 0, b = 0, l = 0))) +
  scale_x_continuous(limits = c(0,1), expand = c(0, 0)) +
  scale_y_continuous(limits = c(0,1), expand = c(0, 0)) 


#scale_color_manual(values=c("#ee6677", "#33bbee", "#ffae34"))



bc_16s_plot <- ggplot(bact_bc_rob, aes(x=removed.pct, y=comp.pct, group=plot, color=plot)) +
  geom_line(linewidth=1.5) +
  labs(x="Percentage of nodes removed", y="Size of largest connected component",
       title="Bacteria", color="Plot") +
  theme(legend.key = element_rect(fill="white")) +
  theme(panel.border = element_blank(), panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(), axis.line = element_line(colour = "black"),
        panel.background=element_blank(),
        axis.title = element_text(size=14),
        title=element_text(size=16)) +
  theme(legend.text = element_text(size=12)) +
   theme(legend.title = element_text(size=14)) +
  #theme(plot.margin = margin(0,25,0,0)) +
   guides(color = guide_legend(override.aes = list(size=8))) +
  theme(axis.title.y = element_text(margin = margin(t = 0, r = 10, b = 0, l = 0))) +
  theme(axis.title.x = element_text(margin = margin(t = 10, r = 0, b = 0, l = 0))) +
  scale_x_continuous(limits = c(0,1), expand = c(0, 0)) +
  scale_y_continuous(limits = c(0,1), expand = c(0, 0)) 


bc_cross_plot <- ggplot(cross_bc_rob, aes(x=removed.pct, y=comp.pct, group=plot, color=plot)) +
  geom_line(linewidth=1.5) +
  labs(x="Percentage of nodes removed", y="Size of largest connected component",
       title="Cross-domain", color="Plot") +
  theme(legend.key = element_rect(fill="white")) +
  theme(panel.border = element_blank(), panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(), axis.line = element_line(colour = "black"),
        panel.background=element_blank(),
        axis.title = element_text(size=14),
        title=element_text(size=16)) +
  theme(legend.text = element_text(size=12)) +
   theme(legend.title = element_text(size=14)) +
  #theme(plot.margin = margin(0,25,0,0)) +
   guides(color = guide_legend(override.aes = list(size=8))) +
  theme(axis.title.y = element_text(margin = margin(t = 0, r = 10, b = 0, l = 0))) +
  theme(axis.title.x = element_text(margin = margin(t = 10, r = 0, b = 0, l = 0))) +
  scale_x_continuous(limits = c(0,1), expand = c(0, 0)) +
  scale_y_continuous(limits = c(0,1), expand = c(0, 0)) 


library(patchwork)

site_plots <- bc_its_plot + bc_16s_plot + bc_cross_plot & theme(legend.position = "bottom")
#site_plots <- site_plots & xlab(NULL) & ylab(NULL)
site_plots <- site_plots + plot_layout(guides = "collect") 

ggsave("../../figures/gradient/terrestrial/btwn_cent_robustness_fb.jpg", width=17, height=6)

```

## Plot with lines by domain

```{r}
all_node_robustness_bc

cross_bc_rob$plot <- factor(cross_bc_rob$plot, levels=c("Beach", "Estuary", "Entrance", "Confluence", "Waterfall", "DrumRoad", "Ridge"))

ordered_plots <- c("Beach", "Estuary", "Entrance", "Confluence", "Waterfall", "DrumRoad", "Ridge")

all_node_robustness_bc$plot <- factor(all_node_robustness_bc$plot, levels=ordered_plots)

all_node_robustness_bc$domain <- factor(all_node_robustness_bc$domain, levels=c("Fungi", "Bacteria", "Cross"))

bc_by_domain <- list()
for (i in 1:7) {
  dat <- all_node_robustness_bc[all_node_robustness_bc$plot==ordered_plots[i]]
  
  my_plot <- ggplot(dat, aes(x=removed.pct, y=comp.pct, group=domain, color=domain)) +
  geom_line(linewidth=1.5) +
  labs(x="Percentage of nodes removed", y="Size of largest connected component",
       title=plots[i], color="Domain") +
  scale_color_manual(values=c("#D81B60", "#1E88E5", "#DEA805")) +
  theme(legend.key = element_rect(fill="white")) +
  theme(panel.border = element_blank(), panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(), axis.line = element_line(colour = "black"),
        panel.background=element_blank(),
        axis.title = element_text(size=14),
        title=element_text(size=16)) +
  theme(legend.text = element_text(size=12)) +
   theme(legend.title = element_text(size=14)) +
  #theme(plot.margin = margin(0,25,20,0)) +
   guides(color = guide_legend(override.aes = list(size=8))) +
  theme(axis.title.y = element_text(margin = margin(t = 0, r = 10, b = 0, l = 0))) +
  theme(axis.title.x = element_text(margin = margin(t = 10, r = 0, b = 0, l = 0))) +
  scale_x_continuous(limits = c(0,1), expand = c(0, 0)) +
  scale_y_continuous(limits = c(0,1), expand = c(0, 0)) 
  
  bc_by_domain[[i]] <- my_plot
  
}

names(bc_by_domain) <- plots
bc_by_domain <- bc_by_domain[ordered_plots]

# library(ggpubr)
# 
# all_by_dom <- ggarrange(plotlist = bc_by_domain,
#                        nrow = 2,
#                        ncol = 4,
#                        common.legend = TRUE,
#                        legend = "bottom") +
  # bgcolor("white")

dom_plots <- wrap_plots(bc_by_domain) & theme(legend.position = "bottom")
#dom_plots <- dom_plots & xlab(NULL) & ylab(NULL)
dom_plots <- dom_plots + plot_layout(guides = "collect", nrow = 2) 


ggsave("../../figures/gradient/terrestrial/btwn_robustness_by_domain_fb.jpg", width=20, height=11)


```










