---
title: "09b_edaphic_sample_subgraphs"
output: html_document
date: "2023-07-05"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
soil_data_complete <- readRDS("../intermediates/gradient/soil_data_complete.rds")
edaph_summ <- aggregate(. ~ site_num, data = soil_data_complete, FUN = mean)
edaphs <- names(soil_data_complete)[1:18]
```

```{r}

# import data
fung_data <- readRDS("~/cmaiki_lts/kaciekaj/waimea/intermediates/gradient/six_empos_fung_grad_data_ordered.rds")
bact_data <- readRDS("~/cmaiki_lts/kaciekaj/waimea/intermediates/gradient/six_empos_bact_grad_data_ordered.rds")

fung_meta_terr <- readRDS("../intermediates/gradient/fung_terrestrial_metadata.rds")
bact_meta_terr <- readRDS("../intermediates/gradient/bact_terrestrial_metadata.rds")

plots <- unique(fung_meta_terr$site_name)


remove_dummy_row <- function(df) {
  new_df <- df[row.names(df)!="dummy",]
  return(new_df)
}


fung_data <- lapply(fung_data, remove_dummy_row)
bact_data <- lapply(bact_data, remove_dummy_row)


# read in data = 20% prevalence global networks
fung_gradient_networks <- readRDS("../intermediates/gradient/fung_gradient_igraphs.rds")
bact_gradient_networks <- readRDS("../intermediates/gradient/bact_gradient_igraphs.rds")
cross_gradient_networks <- readRDS("../intermediates/gradient/cross_gradient_igraphs.rds")


```

```{r, message=FALSE}
library(tibble)
library(dplyr)
library(igraph)
```


Goal: For each plot network, generate 46 subnetworks corresponding to a given sample. Calculate network-level properties, then calculate Spearman's correlations with soil data

```{r}

# function attempt
make_sample_subnets <- function(abun, network) {
  results <- list()
  for (i in 1:ncol(abun)) {
  to_sub <- rownames(abun[abun[i]>0,])
  subnet <- induced_subgraph(network, V(network)$name %in% to_sub)
  
  results[[i]] <- subnet
  names(results)[i] <- names(abun)[i]
  }
  return(results)
}

fung_sample_subnets <- mapply(make_sample_subnets, fung_data, fung_gradient_networks, SIMPLIFY=FALSE)


# calculate network-level properties on subnetworks

# complexity
fung_comp <- lapply(fung_sample_subnets, function(x) lapply(x, graph.density))

fung_comp_dat <- data.frame(comp = unlist(fung_comp))
fung_comp_dat$site_num <- fung_meta_terr$site_code[match(rownames(fung_comp_dat), fung_meta_terr$sample_id)]

for(i in 1:length(edaphs)) {
  fung_comp_dat[,i+2] <- edaph_summ[,i+1][match(fung_comp_dat$site_num, edaph_summ$site_num)]
  names(fung_comp_dat)[ncol(fung_comp_dat)] <- edaphs[i]
}

fung_comp_p_vals <- vector()
fung_comp_ests <- vector()
for(an_edaph in edaphs) {
  mm <- cor.test(fung_comp_dat$comp, fung_comp_dat[,an_edaph])
  fung_comp_p_vals[an_edaph] <- mm$p.value
  fung_comp_ests[an_edaph] <- ifelse(fung_comp_p_vals[an_edaph]<=0.05, mm$estimate, 0)
}

# diameter
fung_diam <- lapply(fung_sample_subnets, function(x) lapply(x, diameter))

fung_diam_dat <- data.frame(diam = unlist(fung_diam))
fung_diam_dat$site_num <- fung_meta_terr$site_code[match(rownames(fung_diam_dat), fung_meta_terr$sample_id)]

for(i in 1:length(edaphs)) {
  fung_diam_dat[,i+2] <- edaph_summ[,i+1][match(fung_diam_dat$site_num, edaph_summ$site_num)]
  names(fung_diam_dat)[ncol(fung_diam_dat)] <- edaphs[i]
}

fung_diam_p_vals <- vector()
fung_diam_ests <- vector()
for(an_edaph in edaphs) {
  mm <- cor.test(fung_diam_dat$diam, fung_diam_dat[,an_edaph])
  fung_diam_p_vals[an_edaph] <- mm$p.value
  fung_diam_ests[an_edaph] <- ifelse(fung_diam_p_vals[an_edaph]<=0.05, mm$estimate, 0)
}


# modularity # DIFF METHOD FOR NOW
mod_fxn <- function(x) {
  res <- modularity(x, membership(cluster_walktrap(x)))
  return(res)
}
fung_mod <- lapply(fung_sample_subnets, function(x) lapply(x, mod_fxn))

fung_mod_dat <- data.frame(mod = unlist(fung_mod))
fung_mod_dat$site_num <- fung_meta_terr$site_code[match(rownames(fung_mod_dat), fung_meta_terr$sample_id)]

for(i in 1:length(edaphs)) {
  fung_mod_dat[,i+2] <- edaph_summ[,i+1][match(fung_mod_dat$site_num, edaph_summ$site_num)]
  names(fung_mod_dat)[ncol(fung_mod_dat)] <- edaphs[i]
}

fung_mod_p_vals <- vector()
fung_mod_ests <- vector()
for(an_edaph in edaphs) {
  mm <- cor.test(fung_mod_dat$mod, fung_mod_dat[,an_edaph])
  fung_mod_p_vals[an_edaph] <- mm$p.value
  fung_mod_ests[an_edaph] <- ifelse(fung_mod_p_vals[an_edaph]<=0.05, mm$estimate, 0)
}

# transitivity
fung_trans <- lapply(fung_sample_subnets, function(x) lapply(x, transitivity))

fung_trans_dat <- data.frame(trans = unlist(fung_trans))
fung_trans_dat$site_num <- fung_meta_terr$site_code[match(rownames(fung_trans_dat), fung_meta_terr$sample_id)]

for(i in 1:length(edaphs)) {
  fung_trans_dat[,i+2] <- edaph_summ[,i+1][match(fung_trans_dat$site_num, edaph_summ$site_num)]
  names(fung_trans_dat)[ncol(fung_trans_dat)] <- edaphs[i]
}

fung_trans_p_vals <- vector()
fung_trans_ests <- vector()
for(an_edaph in edaphs) {
  mm <- cor.test(fung_trans_dat$trans, fung_trans_dat[,an_edaph])
  fung_trans_p_vals[an_edaph] <- mm$p.value
  fung_trans_ests[an_edaph] <- ifelse(fung_trans_p_vals[an_edaph]<=0.05, mm$estimate, 0)
}

fung_res <- rbind(fung_mod_ests, fung_diam_ests, fung_trans_ests, fung_comp_ests)
rownames(fung_res) <- c("Modularity", "Diameter", "Transitivity", "Complexity")

#hh <- heatmap(res, Colv = NA, Rowv = NA, scale="column")
fung_dt2 <- as.data.frame(t(fung_res)) %>%
  rownames_to_column() %>%
  tidyr::gather(colname, value, -rowname)

fung_hh <- ggplot(fung_dt2, aes(x = rowname, y = colname, fill = value)) +
  geom_tile() +
  labs(x = "", y = "", title = "ITS") +
  scale_fill_distiller(palette = "RdPu") +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))
```

# 16S
```{r}

bact_sample_subnets <- mapply(make_sample_subnets, bact_data, bact_gradient_networks, SIMPLIFY=FALSE)


# calculate network-level properties on subnetworks

# complexity
bact_comp <- lapply(bact_sample_subnets, function(x) lapply(x, graph.density))

bact_comp_dat <- data.frame(comp = unlist(bact_comp))
bact_comp_dat$site_num <- bact_meta_terr$site_code[match(rownames(bact_comp_dat), bact_meta_terr$sample_id)]

for(i in 1:length(edaphs)) {
  bact_comp_dat[,i+2] <- edaph_summ[,i+1][match(bact_comp_dat$site_num, edaph_summ$site_num)]
  names(bact_comp_dat)[ncol(bact_comp_dat)] <- edaphs[i]
}

bact_comp_p_vals <- vector()
bact_comp_ests <- vector()
for(an_edaph in edaphs) {
  mm <- cor.test(bact_comp_dat$comp, bact_comp_dat[,an_edaph])
  bact_comp_p_vals[an_edaph] <- mm$p.value
  bact_comp_ests[an_edaph] <- ifelse(bact_comp_p_vals[an_edaph]<=0.05, mm$estimate, 0)
}

# diameter
bact_diam <- lapply(bact_sample_subnets, function(x) lapply(x, diameter))

bact_diam_dat <- data.frame(diam = unlist(bact_diam))
bact_diam_dat$site_num <- bact_meta_terr$site_code[match(rownames(bact_diam_dat), bact_meta_terr$sample_id)]

for(i in 1:length(edaphs)) {
  bact_diam_dat[,i+2] <- edaph_summ[,i+1][match(bact_diam_dat$site_num, edaph_summ$site_num)]
  names(bact_diam_dat)[ncol(bact_diam_dat)] <- edaphs[i]
}

bact_diam_p_vals <- vector()
bact_diam_ests <- vector()
for(an_edaph in edaphs) {
  mm <- cor.test(bact_diam_dat$diam, bact_diam_dat[,an_edaph])
  bact_diam_p_vals[an_edaph] <- mm$p.value
  bact_diam_ests[an_edaph] <- ifelse(bact_diam_p_vals[an_edaph]<=0.05, mm$estimate, 0)
}


# modularity # DIFF METHOD FOR NOW
mod_fxn <- function(x) {
  res <- modularity(x, membership(cluster_walktrap(x)))
  return(res)
}
bact_mod <- lapply(bact_sample_subnets, function(x) lapply(x, mod_fxn))

bact_mod_dat <- data.frame(mod = unlist(bact_mod))
bact_mod_dat$site_num <- bact_meta_terr$site_code[match(rownames(bact_mod_dat), bact_meta_terr$sample_id)]

for(i in 1:length(edaphs)) {
  bact_mod_dat[,i+2] <- edaph_summ[,i+1][match(bact_mod_dat$site_num, edaph_summ$site_num)]
  names(bact_mod_dat)[ncol(bact_mod_dat)] <- edaphs[i]
}

bact_mod_p_vals <- vector()
bact_mod_ests <- vector()
for(an_edaph in edaphs) {
  mm <- cor.test(bact_mod_dat$mod, bact_mod_dat[,an_edaph])
  bact_mod_p_vals[an_edaph] <- mm$p.value
  bact_mod_ests[an_edaph] <- ifelse(bact_mod_p_vals[an_edaph]<=0.05, mm$estimate, 0)
}

# transitivity
bact_trans <- lapply(bact_sample_subnets, function(x) lapply(x, transitivity))

bact_trans_dat <- data.frame(trans = unlist(bact_trans))
bact_trans_dat$site_num <- bact_meta_terr$site_code[match(rownames(bact_trans_dat), bact_meta_terr$sample_id)]

for(i in 1:length(edaphs)) {
  bact_trans_dat[,i+2] <- edaph_summ[,i+1][match(bact_trans_dat$site_num, edaph_summ$site_num)]
  names(bact_trans_dat)[ncol(bact_trans_dat)] <- edaphs[i]
}

bact_trans_p_vals <- vector()
bact_trans_ests <- vector()
for(an_edaph in edaphs) {
  mm <- cor.test(bact_trans_dat$trans, bact_trans_dat[,an_edaph])
  bact_trans_p_vals[an_edaph] <- mm$p.value
  bact_trans_ests[an_edaph] <- ifelse(bact_trans_p_vals[an_edaph]<=0.05, mm$estimate, 0)
}

bact_res <- rbind(bact_mod_ests, bact_diam_ests, bact_trans_ests, bact_comp_ests)
rownames(bact_res) <- c("Modularity", "Diameter", "Transitivity", "Complexity")

#hh <- heatmap(res, Colv = NA, Rowv = NA, scale="column")
bact_dt2 <- as.data.frame(t(bact_res)) %>%
  rownames_to_column() %>%
  tidyr::gather(colname, value, -rowname)

bact_hh <- ggplot(bact_dt2, aes(x = rowname, y = colname, fill = value)) +
  geom_tile() +
  labs(x = "", y = "", title = "16S") +
  scale_fill_distiller(palette = "RdPu") +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))
```


# Cross-domain

```{r}
cross_data <- list()

for (i in 1:length(fung_data)) {
  cross <- plyr::rbind.fill(fung_data[[i]], bact_data[[i]])
  rownames(cross) <- c(rownames(fung_data[[i]]), rownames(bact_data[[i]]))
  cross_data[[i]] <- cross
}

cross_meta_terr <- rbind.fill(fung_meta_terr, bact_meta_terr)


cross_sample_subnets <- mapply(make_sample_subnets, cross_data, cross_gradient_networks, SIMPLIFY=FALSE)


# calculate network-level properties on subnetworks

# complexity
cross_comp <- lapply(cross_sample_subnets, function(x) lapply(x, graph.density))

cross_comp_dat <- data.frame(comp = unlist(cross_comp))
cross_comp_dat$site_num <- cross_meta_terr$site_code[match(rownames(cross_comp_dat), cross_meta_terr$sample_id)]

for(i in 1:length(edaphs)) {
  cross_comp_dat[,i+2] <- edaph_summ[,i+1][match(cross_comp_dat$site_num, edaph_summ$site_num)]
  names(cross_comp_dat)[ncol(cross_comp_dat)] <- edaphs[i]
}

cross_comp_p_vals <- vector()
cross_comp_ests <- vector()
for(an_edaph in edaphs) {
  mm <- cor.test(cross_comp_dat$comp, cross_comp_dat[,an_edaph])
  cross_comp_p_vals[an_edaph] <- mm$p.value
  cross_comp_ests[an_edaph] <- ifelse(cross_comp_p_vals[an_edaph]<=0.05, mm$estimate, 0)
}

# diameter
cross_diam <- lapply(cross_sample_subnets, function(x) lapply(x, diameter))

cross_diam_dat <- data.frame(diam = unlist(cross_diam))
cross_diam_dat$site_num <- cross_meta_terr$site_code[match(rownames(cross_diam_dat), cross_meta_terr$sample_id)]

for(i in 1:length(edaphs)) {
  cross_diam_dat[,i+2] <- edaph_summ[,i+1][match(cross_diam_dat$site_num, edaph_summ$site_num)]
  names(cross_diam_dat)[ncol(cross_diam_dat)] <- edaphs[i]
}

cross_diam_p_vals <- vector()
cross_diam_ests <- vector()
for(an_edaph in edaphs) {
  mm <- cor.test(cross_diam_dat$diam, cross_diam_dat[,an_edaph])
  cross_diam_p_vals[an_edaph] <- mm$p.value
  cross_diam_ests[an_edaph] <- ifelse(cross_diam_p_vals[an_edaph]<=0.05, mm$estimate, 0)
}


# modularity # DIFF METHOD FOR NOW
mod_fxn <- function(x) {
  res <- modularity(x, membership(cluster_walktrap(x)))
  return(res)
}
cross_mod <- lapply(cross_sample_subnets, function(x) lapply(x, mod_fxn))

cross_mod_dat <- data.frame(mod = unlist(cross_mod))
cross_mod_dat$site_num <- cross_meta_terr$site_code[match(rownames(cross_mod_dat), cross_meta_terr$sample_id)]

for(i in 1:length(edaphs)) {
  cross_mod_dat[,i+2] <- edaph_summ[,i+1][match(cross_mod_dat$site_num, edaph_summ$site_num)]
  names(cross_mod_dat)[ncol(cross_mod_dat)] <- edaphs[i]
}

cross_mod_p_vals <- vector()
cross_mod_ests <- vector()
for(an_edaph in edaphs) {
  mm <- cor.test(cross_mod_dat$mod, cross_mod_dat[,an_edaph])
  cross_mod_p_vals[an_edaph] <- mm$p.value
  cross_mod_ests[an_edaph] <- ifelse(cross_mod_p_vals[an_edaph]<=0.05, mm$estimate, 0)
}

# transitivity
cross_trans <- lapply(cross_sample_subnets, function(x) lapply(x, transitivity))

cross_trans_dat <- data.frame(trans = unlist(cross_trans))
cross_trans_dat$site_num <- cross_meta_terr$site_code[match(rownames(cross_trans_dat), cross_meta_terr$sample_id)]

for(i in 1:length(edaphs)) {
  cross_trans_dat[,i+2] <- edaph_summ[,i+1][match(cross_trans_dat$site_num, edaph_summ$site_num)]
  names(cross_trans_dat)[ncol(cross_trans_dat)] <- edaphs[i]
}

cross_trans_p_vals <- vector()
cross_trans_ests <- vector()
for(an_edaph in edaphs) {
  mm <- cor.test(cross_trans_dat$trans, cross_trans_dat[,an_edaph])
  cross_trans_p_vals[an_edaph] <- mm$p.value
  cross_trans_ests[an_edaph] <- ifelse(cross_trans_p_vals[an_edaph]<=0.05, mm$estimate, 0)
}

cross_res <- rbind(cross_mod_ests, cross_diam_ests, cross_trans_ests, cross_comp_ests)
rownames(cross_res) <- c("Modularity", "Diameter", "Transitivity", "Complexity")

#hh <- heatmap(res, Colv = NA, Rowv = NA, scale="column")
cross_dt2 <- as.data.frame(t(cross_res)) %>%
  rownames_to_column() %>%
  tidyr::gather(colname, value, -rowname)

cross_hh <- ggplot(cross_dt2, aes(x = rowname, y = colname, fill = value)) +
  geom_tile() +
  labs(x = "", y = "", title = "Cross-domain") +
  scale_fill_distiller(palette = "RdPu") +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))

```

plots
```{r}
library(patchwork)

all <- fung_hh + bact_hh + cross_hh

ggsave("../figures/gradient/edaphic_network_spearman.png", width=24, height=6)
```
 


Whole network - only 7 data points (1 per plot)
```{r}
fung_netcarto <- readRDS("../intermediates/gradient/fung_gradient_netcarto_results.rds")

fung_new_mod <- sapply(fung_netcarto, function(x) x[[2]])

maybe <- cor.test(fung_new_mod, edaph_summ$`P-OLSEN`) # seems like most/all edaphic factors have p>0.05

p_vals <- vector()
ests <- vector()
for(an_edaph in edaphs) {
  mm <- cor.test(fung_new_mod, edaph_summ[,an_edaph])
  p_vals[an_edaph] <- mm$p.value
  ests[an_edaph] <- mm$estimate
}

```


