---
title: "09d_edaphic_mrm"
output: html_document
date: "2023-07-06"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message=FALSE}
library(tibble)
library(dplyr)
library(igraph)

library(ecodist)
```

```{r}
soil_data_complete <- readRDS("../intermediates/gradient/soil_data_complete.rds")
edaph_summ <- aggregate(. ~ site_num, data = soil_data_complete, FUN = mean)
edaphs <- names(soil_data_complete)[1:18]

soil_data_filtered <- select(soil_data_complete, site_num, CO2_burst_efflux, `P_OLSEN`, K, Ca, Mg, HWEC, water_holding_capacity, pH)
edaph_summ_filtered <- edaph_summ[,colnames(edaph_summ) %in% colnames(soil_data_filtered)]
filtered_edaphs <- names(soil_data_filtered[2:ncol(soil_data_filtered)])
```

```{r}

# import data
fung_data <- readRDS("~/cmaiki_lts/kaciekaj/waimea/intermediates/gradient/six_empos_fung_grad_data_ordered.rds")
bact_data <- readRDS("~/cmaiki_lts/kaciekaj/waimea/intermediates/gradient/six_empos_bact_grad_data_ordered.rds")
cross_data <- readRDS("../intermediates/gradient/cross_data.rds")

fung_meta_terr <- readRDS("../intermediates/gradient/fung_terrestrial_metadata.rds")
bact_meta_terr <- readRDS("../intermediates/gradient/bact_terrestrial_metadata.rds")
cross_meta_terr <- readRDS("../intermediates/gradient/cross_metadata_terr.rds")

plots <- unique(fung_meta_terr$site_name)


remove_dummy_row <- function(df) {
  new_df <- df[row.names(df)!="dummy",]
  return(new_df)
}


fung_data <- lapply(fung_data, remove_dummy_row)
bact_data <- lapply(bact_data, remove_dummy_row)


# read in data = 20% prevalence global networks
fung_gradient_networks <- readRDS("../intermediates/gradient/fung_gradient_igraphs.rds")
bact_gradient_networks <- readRDS("../intermediates/gradient/bact_gradient_igraphs.rds")
cross_gradient_networks <- readRDS("../intermediates/gradient/cross_gradient_igraphs.rds")


```

## MRM

```{r}
mpd_sample_data <- readRDS("../intermediates/gradient/samp_phydist_data.rds")

mpd_dat <- data.frame(mpd_sample_data[,c("mpd.obs.z", "plot")])

mpd_dat$site_num <- cross_meta_terr$site_code[match(rownames(mpd_dat), cross_meta_terr$sample_id)]


for (i in 1:length(filtered_edaphs)) {
  mpd_dat[,i+3] <- edaph_summ_filtered[,i+1][match(mpd_dat$site_num, edaph_summ_filtered$site_num)]
  names(mpd_dat)[ncol(mpd_dat)] <- filtered_edaphs[i]
}


mpd_mrm <- MRM(dist(mpd.obs.z) ~ dist(CO2_burst_efflux) + dist(`P_OLSEN`) + dist(K) + dist(Ca) + dist(Mg) + dist(water_holding_capacity) + dist(pH) + dist(HWEC), data = mpd_dat, nperm = 999)


saveRDS(mpd_mrm, "../intermediates/gradient/mpd_mrm_results.rds")

```

## dbRDA

```{r}
library(vegan)
### perform dbRDA (if no work, do remotes::install_github("vegandevs/vegan") and reload package)
mpd_dbrda <- vegan::capscale(dist(mpd_dat$mpd.obs.z) ~ CO2_burst_efflux + P_OLSEN + K + Ca + Mg + water_holding_capacity + pH + HWEC, data = mpd_dat, dist="euclidean")



ordiplot(mpd_dbrda,type="t",scaling=2)
ordiplot(mpd_dbrda,type="t",scaling=1)

### check constrained and unconstrained variance
mpd_dbrda$CCA$tot.chi/mpd_dbrda$tot.chi

### permutation tests to access significance of constraints
anova(mpd_dbrda) ## overall test of the significance 
anova(mpd_dbrda, by="terms", perm.max=999)

### correlation of the variables to the first two dbrda axes
dbrda.species.scores=scores(mpd_dbrda,choices =1:2,display = "sites")
cor(cbind(dbrda.species.scores,mpd_dat$mpd.obs.z))
```

## By network metric (diameter)

```{r}
dat_for_mrm <- readRDS("../intermediates/gradient/all_diameter_data_for_mrm.rds")

# ITS
fung_diam_dat <- dat_for_mrm[[1]]

fung_diam_mrm <- MRM(dist(fung_diam_dat$diam) ~ dist(CO2_burst_efflux) + dist(`P_OLSEN`) + dist(K) + dist(Ca) + dist(Mg) + dist(water_holding_capacity) + dist(pH) + dist(HWEC), data = fung_diam_dat, nperm = 999)

saveRDS(fung_diam_mrm, "../intermediates/gradient/fung_diam_mrm_results.rds")


# 16S
bact_diam_dat <- dat_for_mrm[[2]]

bact_diam_mrm <- MRM(dist(bact_diam_dat$diam) ~ dist(CO2_burst_efflux) + dist(`P_OLSEN`) + dist(K) + dist(Ca) + dist(Mg) + dist(water_holding_capacity) + dist(pH) + dist(HWEC), data = bact_diam_dat, nperm = 999)

saveRDS(bact_diam_mrm, "../intermediates/gradient/bact_diam_mrm_results.rds")


# Cross
cross_diam_dat <- dat_for_mrm[[3]]

cross_diam_mrm <- MRM(dist(cross_diam_dat$diam) ~ dist(CO2_burst_efflux) + dist(`P_OLSEN`) + dist(K) + dist(Ca) + dist(Mg) + dist(water_holding_capacity) + dist(pH) + dist(HWEC), data = cross_diam_dat, nperm = 999)

saveRDS(cross_diam_mrm, "../intermediates/gradient/cross_diam_mrm_results.rds")



```






