---
title: "10_funguild_prep"
output: html_document
date: "2023-07-07"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

options(bitmapType='cairo')

library(reshape2)
library(plyr)
library(ggplot2)
library(stringr)

```

```{r}
fung_tax <- readRDS("../../intermediates/global/fung_seed_taxonomy.rds")

fung_data <- readRDS("~/hynson_koastore/kaciekaj/waimea_current/intermediates/gradient/terrestrial/six_empos_fung_grad_data_ordered.rds")


remove_dummy_row <- function(df) {
  new_df <- df[row.names(df)!="dummy",]
  return(new_df)
}


fung_data <- lapply(fung_data, remove_dummy_row)


fung_meta_terr <- readRDS("../../intermediates/gradient/terrestrial/fung_terrestrial_metadata.rds")
plots <- unique(fung_meta_terr$site_name)

```

Goal: Reformat taxonomy table into a single column with prefixes ("k__", "p__") and separated by semicolons.

```{r}
fung_new_tax <- data.frame("OTU ID" = fung_tax$denovo_OTU)
names(fung_new_tax) <- "OTU ID"

fung_new_tax$Kingdom <- paste0("k__", fung_tax$Kingdom)
fung_new_tax$Phylum <- paste0("p__", fung_tax$Phylum)
fung_new_tax$Class <- paste0("c__", fung_tax$Class)
fung_new_tax$Order <- paste0("o__", fung_tax$Order)
fung_new_tax$Family <- paste0("f__", fung_tax$Family)
fung_new_tax$Genus <- paste0("g__", fung_tax$Genus)
fung_new_tax$Species <- paste0("s__", fung_tax$Species)


fung_new_tax$paste_tax <- paste(fung_new_tax$Kingdom, fung_new_tax$Phylum, fung_new_tax$Class, fung_new_tax$Order, fung_new_tax$Family, fung_new_tax$Genus, fung_new_tax$Species, sep=";")


table_for_funguild <- data.frame("OTU ID" = fung_tax$denovo_OTU)
names(table_for_funguild) <- "OTU ID"

test_abun <- fung_data[[7]]

ridge_funguild <- data.frame(table_for_funguild[table_for_funguild$`OTU ID` %in% rownames(test_abun),])
names(ridge_funguild) <- "OTU ID"
rownames(ridge_funguild) <- ridge_funguild$`OTU ID`

ridge_funguild <- merge(ridge_funguild, test_abun, by="row.names")
ridge_funguild <- ridge_funguild[,-1]

ridge_funguild$taxonomy <- fung_new_tax$paste_tax[match(ridge_funguild$`OTU ID`, fung_new_tax$`OTU ID`)]

#write.table(ridge_funguild, file = "funguild/ridge_data_for_funguild.txt", row.names=FALSE, sep="\t")

```


```{r}
#devtools::install_github("brendanf/FUNGuildR")

library(FUNGuildR)

dat <- data.frame(OTU = fung_new_tax$`OTU ID`,
                  Taxonomy = fung_new_tax$paste_tax)

sample_guilds <- funguild_assign(dat)

sample_guilds$trophicMode <- ifelse(is.na(sample_guilds$trophicMode), "NA", sample_guilds$trophicMode)

# remove things only possible confidence ranking
sample_guilds_filt <- sample_guilds[sample_guilds$confidenceRanking!="Possible",]

saveRDS(sample_guilds, "../../intermediates/gradient/terrestrial/funguild_assignments.rds")
#sample_guilds <- tidyr::separate_longer_delim(sample_guilds, trophicMode, delim="-")

#funguild_assignments <- sample_guilds[!is.na(sample_guilds$taxon),]

```

# Draw back to gradient taxa

```{r}
funguild_by_plot <- list()
abun_by_funguild <- list()
for (i in 1:7) {
  df <- fung_data[[i]]
  tax <- sample_guilds_filt[sample_guilds_filt$OTU %in% rownames(df),]
  funguild_by_plot[[i]] <- tax
}

lapply(funguild_by_plot, dim)

# min number of assigned funguild taxa = 307

for (i in 1:7) {
  df <- fung_data[[i]]
  
  new_abun <- df[rownames(df) %in% funguild_by_plot[[i]]$OTU,]
  
  new_abun <- new_abun[sample(rownames(new_abun), 307),]
  new_abun <- new_abun[,colSums(new_abun)>0]
  
  abun_by_funguild[[i]] <- new_abun
}


sum_by_plot <- lapply(abun_by_funguild, function(x) as.data.frame(rowSums(x)))

for (i in 1:7) {
  my_df <- sum_by_plot[[i]]
  names(my_df) <- plots[i]
  sum_by_plot[[i]] <- as.data.frame(t(my_df))
}

all_together <- do.call("rbind.fill", sum_by_plot)
all_together <- as.data.frame(t(all_together))
names(all_together) <- plots

all_together[is.na(all_together)] <- 0
all_together_ra <- decostand(t(all_together), method = "total", margin = 1)


with_troph <- as.data.frame(t(all_together_ra))
with_troph$otu <- rownames(with_troph)
with_troph$trophic <- sample_guilds$trophicMode[match(rownames(with_troph), sample_guilds$OTU)]
# add line for dividing relabun value based on how many "-" there are? ifelse?

divide_relabun <- function(vector_of_relabuns, vector_of_trophs) {
  ct <- str_count(vector_of_trophs, "-")
  new <- ifelse(ct>0, vector_of_relabuns/(ct+1), vector_of_relabuns)
  return(new)
}

with_troph[,1:7] <- apply(with_troph[,1:7], 2, divide_relabun, vector_of_trophs = with_troph$trophic)

with_troph_sep <- tidyr::separate_longer_delim(with_troph, trophic, delim="-")
with_troph_sep$otu <- make.unique(with_troph_sep$otu, "_")
with_troph_sep <- column_to_rownames(with_troph_sep, "otu")


data_melt <- melt(with_troph_sep)
names(data_melt) <- c("otu", "trophic", "plot", "relabun")


trophs <- unique(data_melt$trophic)

dat_by_troph <- list()

for (a_troph in trophs) {
  dat_by_troph[[a_troph]] <- data_melt[data_melt$trophic==a_troph,]
}


troph_aovs <- list()
for (a_troph in trophs) {
  dat <- dat_by_troph[[a_troph]]
  
  stat <- aov(log(relabun + 1) ~ plot, data = dat)
  
 troph_aovs[[a_troph]] <- stat
}


lapply(troph_aovs, summary)



library(paletteer)
library(wesanderson)

test_pl <- ggplot(data_melt, aes(x = variable, y = value, fill = trophic)) +
  geom_bar(stat="identity", position="stack") +
    theme(panel.grid.major=element_blank(), 
          panel.grid.minor=element_blank(), 
          panel.background=element_blank(), 
          axis.line = element_line(colour="black")) +
  scale_y_continuous(expand = c(0, 0), limits = c(0, 1)) +
  labs(x = "Site", y = "Relative Abundance", fill = "Trophic", title = "FUNGuild abundances by site", subtitle = "307 named taxa per site") +
  scale_fill_manual(values = wes_palette("Moonrise3"))

ggsave("../../figures/gradient/terrestrial/funguild_relabun_by_plot.png", width=8, height=5.5)


# bar plot of funguild categories by plot
one_abun <- fung_data[[1]]

one_plot_guild <- sample_guilds[sample_guilds$OTU %in% rownames(one_abun),]
one_plot_guild$trophicMode <- ifelse(is.na(one_plot_guild$trophicMode), "NA", one_plot_guild$trophicMode)


test_bar <- ggplot(one_plot_guild, aes(x=trophicMode)) +
  geom_bar()

test_dat <- one_plot_guild %>% dplyr::group_by(trophicMode, confidenceRanking) %>%
  dplyr::summarise(count = length(unique(OTU))) %>%
  tidyr::separate_longer_delim(trophicMode, delim="-")



# loop
library(scales)
ggcolors <- hex <- hue_pal()(7)

plot_guild_assignments <- list()
funguild_plots <- list()
for (i in 1:length(fung_data)) {
  dat <- fung_data[[i]]
  
  guild_dat <- sample_guilds[sample_guilds$OTU %in% rownames(dat),]
  guild_dat_sep <- tidyr::separate_longer_delim(guild_dat, trophicMode, delim="-")
  
  plot_guild_assignments[[i]] <- guild_dat_sep
  
  gg <- ggplot(guild_dat_sep, aes(x=trophicMode)) +
    geom_bar(fill = ggcolors[i]) +
    labs(title = plots[[i]]) +
    theme(
      #axis.text.x = element_text(colour="black", angle=30, hjust=1), 
      #     panel.grid.major=element_blank(), 
      #     panel.grid.minor=element_blank(), 
      #     panel.background=element_blank(), 
      #     axis.line = element_line(colour="black"),
      #     axis.title.x = element_blank(),
      #     axis.title.y = element_blank(),
      #     axis.text.y = element_text(size=12, colour="black"),
          legend.position = "none") +
   scale_y_continuous(breaks = seq(0, 500, 100),limits = c(c(0, 500)))
  
  funguild_plots[[i]] <- gg

}
names(funguild_plots) <- plots

funguild_plots <- funguild_plots[c("Beach", "Estuary", "Entrance", "Confluence", "Waterfall", "DrumRoad", "Ridge")]
  
#library(patchwork)

all <- funguild_plots[[1]] + funguild_plots[[2]] + funguild_plots[[3]] + funguild_plots[[4]] + funguild_plots[[5]] + funguild_plots[[6]] + funguild_plots[[7]]

ggsave("../../figures/gradient/terrestrial/funguild_counts_by_plot_summarized.jpg", width=14, height=11)

```












