---
title: "11_taxonomy"
output: html_document
date: "2023-10-02"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(dplyr)
library(vegan)
```

Goal: see how conserved (or not) fungi and bacteria are across plots

```{r}
# import data
fung_abun <- readRDS("~/cmaiki_lts/kaciekaj/waimea/intermediates/gradient/terrestrial/six_empos_fung_grad_data_ordered.rds")
bact_abun <- readRDS("~/cmaiki_lts/kaciekaj/waimea/intermediates/gradient/terrestrial/six_empos_bact_grad_data_ordered.rds")

remove_dummy_row <- function(df) {
  new_df <- df[row.names(df)!="dummy",]
  return(new_df)
}


fung_abun <- lapply(fung_abun, remove_dummy_row)
bact_abun <- lapply(bact_abun, remove_dummy_row)

fung_meta_terr <- readRDS("../../intermediates/gradient/terrestrial/fung_terrestrial_metadata.rds")
bact_meta_terr <- readRDS("../../intermediates/gradient/terrestrial/bact_terrestrial_metadata.rds")

plots <- unique(fung_meta_terr$site_name)

```

```{r}
# get tax tables
fung_ps <- readRDS("../../intermediates/global/new_fung_physeq_sampletype_cull.rds")
bact_ps <- readRDS("../../intermediates/global/new_bact_physeq_sampletype_cull.rds")

fung_tax <- as.data.frame(tax_table(fung_ps))
bact_tax <- as.data.frame(tax_table(bact_ps))

```

```{r}
fung_flip <- lapply(fung_abun, function(x) as.data.frame(t(x)))
all_fung <- do.call("rbind.fill", fung_flip)

fung_sampnames <- unlist(lapply(fung_abun, colnames))
rownames(all_fung) <- fung_sampnames
all_fung[is.na(all_fung)] <- 0

fung_w_data <- all_fung
fung_w_data$site <- fung_meta_terr$site_name[match(rownames(fung_w_data), fung_meta_terr$sample_id)]

all_fung_hell <- decostand(all_fung, "hellinger")

fung_site_perm <- adonis(all_fung_hell ~ site, data = fung_w_data, permutations = 9999, method = "bray")



fung_site_nmds <- metaMDS(all_fung, k = 2, distance = "bray", trymax = 100, maxit = 2000)

fung_site_df <- as.data.frame(scores(fung_site_nmds)) %>%
  cbind(fung_w_data$site)

names(fung_site_df)[3] <- "site"
  
fung_site_gg <- 
  ggplot(fung_site_df, aes(x = NMDS1, y = NMDS2)) +
  geom_point(aes(color = site)) +
  stat_ellipse(geom = "polygon", aes(group = site, color = site, fill = site), alpha = 0.3) +
  #annotate("text", x = -2, y = 0.95, label = paste0("stress: ", format(fung_nmds$stress, digits = 4)), hjust = 0) +
  theme_bw()




bact_flip <- lapply(bact_abun, function(x) as.data.frame(t(x)))
all_bact <- do.call("rbind.fill", bact_flip)

bact_sampnames <- unlist(lapply(bact_abun, colnames))
rownames(all_bact) <- bact_sampnames
all_bact[is.na(all_bact)] <- 0

bact_w_data <- all_bact
bact_w_data$site <- bact_meta_terr$site_name[match(rownames(bact_w_data), bact_meta_terr$sample_id)]

all_bact_hell <- decostand(all_bact, "hellinger")

bact_site_perm <- adonis(all_bact_hell ~ site, data = bact_w_data, permutations = 9999, method = "bray")

bact_site_nmds <- metaMDS(all_bact, k = 2, distance = "bray", trymax = 100, maxit = 2000)

bact_site_df <- as.data.frame(scores(bact_site_nmds)) %>%
  cbind(bact_w_data$site)

names(bact_site_df)[3] <- "site"
  
bact_site_gg <- 
  ggplot(bact_site_df, aes(x = NMDS1, y = NMDS2)) +
  geom_point(aes(color = site)) +
  stat_ellipse(geom = "polygon", aes(group = site, color = site, fill = site), alpha = 0.3) +
  #annotate("text", x = -2, y = 0.95, label = paste0("stress: ", format(bact_nmds$stress, digits = 4)), hjust = 0) +
  theme_bw()



```

```{r}
saveRDS(fung_site_perm, "../../intermediates/gradient/terrestrial/fung_site_permanova.rds")
saveRDS(bact_site_perm, "../../intermediates/gradient/terrestrial/bact_site_permanova.rds")
```





```{r}
agg_by_tax <- function(otu_tab, tax_tab, taxonomic_level) {
  sampnames <- names(otu_tab)
  
  copy <- otu_tab
  copy[,taxonomic_level] <- tax_tab[,taxonomic_level][match(rownames(copy), tax_tab$denovo_OTU)]
  new_tab <- stats::aggregate(copy[,sampnames], by = list(copy[,taxonomic_level]), sum)
  
  final <- column_to_rownames(new_tab, "Group.1")
  return(final)
}

otu_tab <- fung_abun[[1]]
tax_tab <- fung_tax

hmm <- as.data.frame(rowSums(final), drop=FALSE)
hmm <- decostand(t(hmm), "total")
what <- as.data.frame(t(hmm))
what <- what %>% rownames_to_column("Class")
names(what)[2] <- "relative_abundance"
what$num <- 1



ra <- decostand(t(final), "total")
names(ra) 


fung_by_class <- agg_by_tax(otu_tab[[1]], tax_tab, "Class")



fung_site_tax <- lapply(fung_abun, function(x) fung_tax[fung_tax$denovo_OTU %in% rownames(x),])

fung_tax_summ <- lapply(fung_site_tax, function(x) x %>% group_by(Class) %>% summarise(n = length(denovo_OTU)) %>% column_to_rownames("Class"))

fung_tax_summ <- lapply(fung_tax_summ, function(x) as.data.frame(t(x)))

hm <- do.call("rbind.fill", fung_tax_summ)
hm$sites <- plots

hm$sites <- factor(hm$sites, levels = c("Beach", "Estuary", "Entrance", "Confluence", "Waterfall", "DrumRoad", "Ridge"))
hm <- hm[order(hm$sites),]
rownames(hm) <- NULL
hm <- hm %>% column_to_rownames("sites")

hm[is.na(hm)] <- 0

no_NA <- hm[,names(hm)!="NA"]

library(pals)
library(pheatmap)
#my_colrs <- stevens.pinkblue()
my_colrs <- brewer.pubu(9)
#my_colrs <- kovesi.linear_blue_5_95_c73(100)
pheatmap(t(no_NA), cluster_cols = FALSE, cluster_rows = FALSE, col = my_colrs)
heatmap(t(no_NA), Colv = NA, col = my_colrs, scale = "none")

gg_fung_dat <- melt(t(no_NA))

outlier_test <- no_NA
outlier_test[outlier_test > 50] <- NA

gg_fung_dat <- reshape2::melt(t(outlier_test))

library(gplots)
heatmap.2(t(outlier_test), trace = "none", na.color = "Green")

fung_heat <- ggplot(gg_fung_dat, aes(x = Var2, y = Var1, fill = value)) +
                geom_tile(color = "black") +
                scale_fill_gradient2(low = "white", high = "blue", na.value = "grey50") +
                coord_fixed()
 


```


```{r}
bact_site_tax <- lapply(bact_abun, function(x) bact_tax[bact_tax$denovo_OTU %in% rownames(x),])

bact_tax_summ <- lapply(bact_site_tax, function(x) x %>% group_by(Class) %>% summarise(n = length(denovo_OTU)) %>% column_to_rownames("Class"))

bact_tax_summ <- lapply(bact_tax_summ, function(x) as.data.frame(t(x)))

hm <- do.call("rbind.fill", bact_tax_summ)
hm$sites <- plots

hm$sites <- factor(hm$sites, levels = c("Beach", "Estuary", "Entrance", "Confluence", "Waterfall", "DrumRoad", "Ridge"))
hm <- hm[order(hm$sites),]
rownames(hm) <- NULL
hm <- hm %>% column_to_rownames("sites")

hm[is.na(hm)] <- 0

no_NA <- hm[,names(hm)!="NA"]

library(pals)
library(pheatmap)
#my_colrs <- stevens.pinkblue()
my_colrs <- brewer.pubu(9)
#my_colrs <- kovesi.linear_blue_5_95_c73(100)
pheatmap(t(no_NA), cluster_cols = FALSE, cluster_rows = FALSE, col = my_colrs)
heatmap(t(hm), Colv = NA, col = my_colrs, scale = "none")

outlier_test <- no_NA
outlier_test[outlier_test > 50] <- NA

gg_bact_dat <- reshape2::melt(t(outlier_test))

library(gplots)
#heatmap.2(t(outlier_test), trace = "none", na.color = "Green")

bact_heat <- ggplot(gg_bact_dat, aes(x = Var2, y = Var1, fill = value)) +
                geom_tile(color = "black") +
                scale_fill_gradient2(low = "white", high = "blue", na.value = "grey50") +
                coord_fixed()
 


```









