---
title: "Accumulation Curves - EMPO"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
options(bitmapType='cairo')
options(scipen=9999)
```

```{r, echo=FALSE, message=FALSE}
library(iNEXT)
library(job)
library(dplyr)
library(ggplot2)
library(ggpubr)
```

```{r}
# read in data (sub means nothing as these are not subset, just following naming conventions from the 3a Rmd to make things easier)
abun_sub <- readRDS("../intermediates/fungal_asv_table_matched_up.rds")
#culled_tax <- readRDS("stuff_to_scp/culled_tax_table.rds")
meta_sub <- readRDS("../intermediates/fungal_metadata_matched_up.rds")

bact_abun <- readRDS("../intermediates/bact_asv_table_matched_up.rds")
bact_met <- readRDS("../intermediates/bact_metadata_matched_up.rds")


# count all beach samples as riverine
meta_sub[meta_sub$site_name=="Beach" & meta_sub$sample_type=="WaterSaline",]$habitat = "Riverine"

bact_met[bact_met$site_name=="Beach" & bact_met$sample_type=="WaterSaline",]$habitat = "Riverine"

```

```{r}
# goal: accumulation curves by empo3 category, per plot(?)
# I think the plots correspond to 'site_name' - there are no distinct lat-lon combos within site

# sample names in abundance table eventually get "X" appended due to the colnames being numeric
# make a new column with these names
meta_sub$x_seq_ids <- paste0("X", meta_sub$sequencing_id)

bact_met$x_seq_ids <- paste0("X", bact_met$sequencing_id)
```

```{r}
# saline detective work
f = meta_sub %>% group_by(habitat, site_name, empo_3) %>% summarise(empo3_len = length(site_name)) %>% arrange(habitat, site_name, desc(empo3_len))

f_sal <- f[grepl("saline", f$empo_3, ignore.case=TRUE) & grepl("water", f$empo_3, ignore.case=TRUE),]
f_met_sal <- meta_sub[grepl("saline", meta_sub$empo_3, ignore.case=TRUE) & grepl("water", meta_sub$empo_3, ignore.case=TRUE),]

write.csv(f_sal, "../intermediates/fung_water_samples_by_hab_and_site.csv")
write.csv(f_met_sal, "../intermediates/fung_water_samples_metadata.csv")


b = bact_met %>% group_by(habitat, site_name, empo_3) %>% summarise(empo3_len = length(site_name)) %>% arrange(habitat, site_name, desc(empo3_len))

b_sal <- b[grepl("saline", b$empo_3, ignore.case=TRUE) & grepl("water", b$empo_3, ignore.case="TRUE"),]

write.csv(b_sal, "../intermediates/bact_water_samples_by_hab_and_site.csv")


# raw data check
full_met <- read.csv("../metadata/all_waimea_hiseq_sample_metadata.csv") # 3206 samples

fung_meta_raw <- full_met[grep("ITS", full_met$locus, ignore.case = T),] # 1586 samples
bact_meta_raw <- full_met[grep("16S", full_met$locus, ignore.case = T),] # 1620

f_raw <- fung_meta_raw %>% group_by(habitat, site_name, empo_3) %>% summarise(empo3_len = length(site_name)) %>% arrange(habitat, site_name, desc(empo3_len))
f_raw_sal <- f_raw[f_raw$habitat %in% c("Marine", "Terrestrial", "Riverine") & grepl("water", f_raw$empo_3, ignore.case=TRUE),]

```


```{r}
# want one list per plot/site, where each item in the list is a vector of nonzero ASV abundances corresponding to each EMPO3 cateogory
# gonna need a loop or apply

# also want to subset sites with multiple habitats (stream, marine, terrestrial) by habitat type

site_subset <- function(asv_table, meta_table) {
  sites <- unique(meta_table$site_name)
  
  site_list <- list()
  
  for (a_site in sites) {
    sub_met <- meta_table[which(meta_table$site_name==a_site),]
    
      if (length(unique(sub_met$habitat != 1))) {
        habs <- unique(sub_met$habitat)
        
          for (a_hab in habs) {
            sub_hab_met <- sub_met[which(sub_met$habitat==a_hab),]
            
            sub_hab_abun <- asv_table[,which(names(asv_table) %in% sub_hab_met$sequencing_id)]
            sub_hab_abun <- data.frame(sub_hab_abun)
            sub_hab_abun <- sub_hab_abun[which(rowSums(sub_hab_abun) > 0),]
            sub_hab_abun <- data.frame(sub_hab_abun)
            
            site_hab_name <- paste(a_site, a_hab, sep=", ")
            
            site_list[[site_hab_name]] <- sub_hab_abun
            
          }
        
      } else {
        
        sub_abun <- asv_table[,which(names(asv_table) %in% sub_met$sequencing_id)]
        sub_abun <- sub_abun[which(rowSums(sub_abun) > 0),]
        
        hab <- unique(sub_met$habitat)
        hab_name <- paste(a_site, hab, sep=", ")
        
        site_list[[hab_name]] <- sub_abun
        
      }
    
  }
  
  return(site_list)
}

asvs_by_site <- site_subset(abun_sub, meta_sub)

asvs_by_site <- asvs_by_site[order(names(asvs_by_site))]

names(asvs_by_site[["DrumRoad, Marine"]]) <- "X102318"

#4, 5

make_emp_list <- function(site, site_list, meta_table, asv_table) {
  
  dat <- site_list[[site]]
  samples <- names(dat)
  
  sub_met <- meta_table[which(meta_table$x_seq_ids %in% samples),]
  
  empo3 <- unique(sub_met$empo_3)
  emp_list <- list()
  
  for (e in empo3) {
    sub_sub_met <- sub_met[which(sub_met$empo_3==e),]
    sub_abun <- asv_table[,which(names(asv_table) %in% sub_sub_met$sequencing_id)]
    sub_abun <- data.frame(sub_abun)

    emp_list[[e]] <- sub_abun
  }
  
  return(emp_list)
}

sites <- names(asvs_by_site)

emp_asv_sums <- lapply(sites,
                make_emp_list,
                asvs_by_site,
                meta_sub,
                abun_sub)

names(emp_asv_sums) <- names(asvs_by_site)

```

```{r}
## inext 

# job::job({
#   site1_inext <- iNEXT(emp_asv_sums[["OutsideRocks"]], nboot = 200) 
# })

#inext_list <- lapply(emp_asv_sums, function(x) iNEXT(x, nboot=200))

inext_results <- list()

for (i in 1:length(emp_asv_sums)) {
  dat <- emp_asv_sums[[i]]
  counts <- sapply(dat, sum)
  end <- max(counts)
  
  curve_calc <- iNEXT(dat, nboot = 200, endpoint = (end*2))
  
  inext_results[[i]] <- curve_calc
}


saveRDS(inext_results, "../outputs/list_of_inext_results_by_site_and_hab.rds")

lapply(inext_results, ggiNEXT)

```

```{r}

plot_list <- list()

for (i in 1:length(inext_results)) {
  subt <- paste0("ASVs = ", nrow(asvs_by_site[[i]]), ", Samples = ", ncol(asvs_by_site[[i]]))
  
  plot <- ggiNEXT(inext_results[[i]]) +
  theme_classic() +
  labs(title = paste(sites[[i]], subt, sep="\n")) +
  theme(plot.title = element_text(hjust = 0.5,
                                  size = 16,
                                  face = "bold",
                                  margin = margin(0,0,20,0)),
        axis.title.x = element_text(vjust=-2),
        axis.title.y = element_text(vjust=2)) +
  scale_shape_manual(values = rep(19, length(emp_asv_sums[[i]]))) +
  #scale_color_brewer(palette = "Set2") +
  #scale_fill_brewer(palette = "Set2") +
  theme(plot.margin = margin(20,10,20,5)) +
  #scale_y_continuous(limits=c(0,30000), breaks=seq(0,30000, by = 10000)) +
  xlab("Number of sequences") +
  ylab("ASV richness")
  
  plot_list[[i]] <- plot
}

saveRDS(plot_list, "../intermediates/emp_accum_curve_plot_list_with_habitat.rds")

```

```{r}

for (i in 1:length(plot_list)) {
  ggsave(filename = paste0("../figures/emp_accum_curves/", sites[[i]], "_accum_curve_with_hab.png"), plot = plot_list[[i]], width = 8, height = 5)
}

```


```{r}
# how many samples and ASVs per plot?
nums <- data.frame(sapply(asvs_by_site, nrow))
nums$samp <- sapply(asvs_by_site, ncol)

names(nums) <- c("asv_abundance", "number_of_samples")

nums <- nums[order(-nums$asv_abundance),]
saveRDS(nums, "../intermediates/how_many_asvs_samps_per_plot.rds")
write.csv(nums, "../outputs/asv_and_sample_counts_by_plot.csv")
```

### Replicate Numbers of EMPO3

```{r}

get_samp_num <- function (table) {
  d_t <- dim(table)
  t_n <- d_t[2]
  
  return(t_n)
}

fung_samp_names <- lapply(emp_asv_sums, function(x) lapply(x, get_samp_num))


library(stringr)

# a terrible workaround 
fung_samp_reps <- data.frame(unlist(fung_samp_names))
fung_samp_reps$empo3 <- sub('.*\\.', '', rownames(fung_samp_reps))

fung_samp_reps$placeholder <- str_extract(rownames(fung_samp_reps), "(.+)[/.]")

fung_samp_reps$site_name <- str_extract(rownames(fung_samp_reps), "(.+)[/,]")
fung_samp_reps$site_name <- gsub(",", "", fung_samp_reps$site_name)

fung_samp_reps$habitat <- str_extract(fung_samp_reps$placeholder, "[/, ](.+)")
fung_samp_reps$habitat <- gsub(", ", "", fung_samp_reps$habitat)
fung_samp_reps$habitat <- substr(fung_samp_reps$habitat, 1, nchar(fung_samp_reps$habitat)-1)

fung_samp_reps <- fung_samp_reps[,c(2,4,5,1)]
rownames(fung_samp_reps) <- NULL
names(fung_samp_reps)[4] <- "num_reps"

fung_samp_reps2 <- arrange(fung_samp_reps, empo3, num_reps, site_name)

fung_min_samp_reps <- fung_samp_reps2 %>% group_by(empo3) %>% summarise(min_rep = min(num_reps))


```


### Replicate Numbers of EMPO3 (bacteria; paste to 03d Rmd after)

```{r}
bact_asvs_by_site <- site_subset(bact_abun, bact_met)

bact_asvs_by_site <- bact_asvs_by_site[order(names(bact_asvs_by_site))]

sites2 <- names(bact_asvs_by_site)

bact_emp_asv_sums <- lapply(sites2,
                make_emp_list,
                bact_asvs_by_site,
                bact_met,
                bact_abun)

names(bact_emp_asv_sums) <- names(bact_asvs_by_site)


get_samp_num <- function (table) {
  d_t <- dim(table)
  t_n <- d_t[2]
  
  return(t_n)
}

bact_samp_names <- lapply(bact_emp_asv_sums, function(x) lapply(x, get_samp_num))


library(stringr)

# a terrible workaround 

make_rep_table <- function(name_list) {
samp_reps <- data.frame(unlist(name_list))
samp_reps$empo3 <- sub('.*\\.', '', rownames(samp_reps))

samp_reps$placeholder <- str_extract(rownames(samp_reps), "(.+)[/.]")

samp_reps$site_name <- str_extract(rownames(samp_reps), "(.+)[/,]")
samp_reps$site_name <- gsub(",", "", samp_reps$site_name)

samp_reps$habitat <- str_extract(samp_reps$placeholder, "[/, ](.+)")
samp_reps$habitat <- gsub(", ", "", samp_reps$habitat)
samp_reps$habitat <- substr(samp_reps$habitat, 1, nchar(samp_reps$habitat)-1)

samp_reps <- samp_reps[,c(2,4,5,1)]
rownames(samp_reps) <- NULL
names(samp_reps)[4] <- "num_reps"

return(samp_reps)
}

bact_samp_reps <- make_rep_table(bact_samp_names)

bact_samp_reps2 <- arrange(bact_samp_reps, empo3, num_reps, site_name)

bact_min_samp_reps <- bact_samp_reps2 %>% group_by(empo3) %>% summarise(min_rep = min(num_reps))

```

```{r}
write.csv(bact_samp_reps2, "../intermediates/bact_replicates_by_empo3.csv")
write.csv(bact_min_samp_reps, "../intermediates/bact_minimum_sample_reps.csv")
```


### Not matched up data

```{r}
# nm = nonmatch
fung_nm_abun <- readRDS("../intermediates/culled_asv_table_aerosols_and_fung_corp_removed.rds")
fung_nm_met <- readRDS("../intermediates/culled_metadata_no_aerosols_fung_corp.rds")

bact_nm_abun <- readRDS("../intermediates/culled_bact_asv_table_aerosols_and_fung_corp_removed.rds")
bact_nm_met <- readRDS("../intermediates/culled_bact_metadata_aerosols_and_fung_corp_removed.rds")

fung_nm_met$x_seq_ids <- paste0("X", fung_nm_met$sequencing_id)
bact_nm_met$x_seq_ids <- paste0("X", bact_nm_met$sequencing_id)


bact_asvs_by_site_nm <- site_subset(bact_nm_abun, bact_nm_met)

bact_asvs_by_site_nm <- bact_asvs_by_site_nm[order(names(bact_asvs_by_site_nm))]

sites3 <- names(bact_asvs_by_site_nm)

bact_emp_asv_sums_nm <- lapply(sites3,
                make_emp_list,
                bact_asvs_by_site_nm,
                bact_nm_met,
                bact_nm_abun)

names(bact_emp_asv_sums_nm) <- names(bact_asvs_by_site_nm)


bact_samp_names_nm <- lapply(bact_emp_asv_sums_nm, function(x) lapply(x, get_samp_num))


bact_samp_reps_nm <- make_rep_table(bact_samp_names_nm)

bact_samp_reps2_nm <- arrange(bact_samp_reps_nm, empo3, num_reps, site_name)

bact_min_samp_reps_nm <- bact_samp_reps2_nm %>% group_by(empo3) %>% summarise(min_rep = min(num_reps))


```

```{r}
fung_asvs_by_site_nm <- site_subset(fung_nm_abun, fung_nm_met)

fung_asvs_by_site_nm <- fung_asvs_by_site_nm[order(names(fung_asvs_by_site_nm))]

sites4 <- names(fung_asvs_by_site_nm)

fung_emp_asv_sums_nm <- lapply(sites4,
                make_emp_list,
                fung_asvs_by_site_nm,
                fung_nm_met,
                fung_nm_abun)

names(fung_emp_asv_sums_nm) <- names(fung_asvs_by_site_nm)


fung_samp_names_nm <- lapply(fung_emp_asv_sums_nm, function(x) lapply(x, get_samp_num))


fung_samp_reps_nm <- make_rep_table(fung_samp_names_nm)

fung_samp_reps2_nm <- arrange(fung_samp_reps_nm, empo3, num_reps, site_name)

fung_min_samp_reps_nm <- fung_samp_reps2_nm %>% group_by(empo3) %>% summarise(min_rep = min(num_reps))

```

```{r}
f_table <- fung_min_samp_reps
f_table$min_rep2 <- fung_min_samp_reps_nm$min_rep
names(f_table)[2:3] <- c("min_reps_when_all_samps_match_btwn_16S_ITS", "min_reps_when_mismatches_occur")

b_table <- bact_min_samp_reps
b_table$min_rep2 <- bact_min_samp_reps_nm$min_rep
names(b_table)[2:3] <- c("min_reps_when_all_samps_match_btwn_16S_ITS", "min_reps_when_mismatches_occur")

```

```{r}
write.csv(f_table, "../intermediates/min_emp_reps_fung.csv")
write.csv(b_table, "../intermediates/min_emp_reps_bact.csv")

write.csv(bact_samp_reps2_nm, "../intermediates/bact_replicates_nonmatch_by_empo3.csv")
```


