---
title: "Accumulation Curves - EMPO"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
options(bitmapType='cairo')
options(scipen=9999)
```

```{r, echo=FALSE, message=FALSE}
library(iNEXT)
library(job)
library(dplyr)
library(ggplot2)
library(ggpubr)
```

```{r}
# read in data
bact_abun <- readRDS("../intermediates/bact_asv_table_matched_up.rds")
bact_met <- readRDS("../intermediates/bact_metadata_matched_up.rds")

# count all beach samples as riverine
bact_met[bact_met$site_name=="Beach" & bact_met$sample_type=="WaterSaline",]$habitat = "Riverine"

```

```{r}
# goal: accumulation curves by empo3 category, per plot(?)
# I think the plots correspond to 'site_name' - there are no distinct lat-lon combos within site

# sample names in abundance table eventually get "X" appended due to the colnames being numeric
# make a new column with these names
bact_met$x_seq_ids <- paste0("X", bact_met$sequencing_id)
```

```{r}
# want one list per plot/site, where each item in the list is a vector of nonzero ASV abundances corresponding to each EMPO3 cateogory
# gonna need a loop or apply

# also want to subset sites with multiple habitats (stream, marine, terrestrial) by habitat type

site_subset <- function(asv_table, meta_table) {
  sites <- unique(meta_table$site_name)
  
  site_list <- list()
  
  for (a_site in sites) {
    sub_met <- meta_table[which(meta_table$site_name==a_site),]
    
      if (length(unique(sub_met$habitat != 1))) {
        habs <- unique(sub_met$habitat)
        
          for (a_hab in habs) {
            sub_hab_met <- sub_met[which(sub_met$habitat==a_hab),]
            
            sub_hab_abun <- asv_table[,which(names(asv_table) %in% sub_hab_met$sequencing_id)]
            sub_hab_abun <- data.frame(sub_hab_abun)
            sub_hab_abun <- sub_hab_abun[which(rowSums(sub_hab_abun) > 0),]
            sub_hab_abun <- data.frame(sub_hab_abun)
            
            site_hab_name <- paste(a_site, a_hab, sep=", ")
            
            site_list[[site_hab_name]] <- sub_hab_abun
            
          }
        
      } else {
        
        sub_abun <- asv_table[,which(names(asv_table) %in% sub_met$sequencing_id)]
        sub_abun <- sub_abun[which(rowSums(sub_abun) > 0),]
        
        hab <- unique(sub_met$habitat)
        hab_name <- paste(a_site, hab, sep=", ")
        
        site_list[[hab_name]] <- sub_abun
        
      }
    
  }
  
  return(site_list)
}

bact_asvs_by_site <- site_subset(bact_abun, bact_met)

bact_asvs_by_site <- bact_asvs_by_site[order(names(bact_asvs_by_site))]

#4, 5

make_emp_list <- function(site, site_list, meta_table, asv_table) {
  
  dat <- site_list[[site]]
  samples <- names(dat)
  
  sub_met <- meta_table[which(meta_table$x_seq_ids %in% samples),]
  
  empo3 <- unique(sub_met$empo_3)
  emp_list <- list()
  
  for (e in empo3) {
    sub_sub_met <- sub_met[which(sub_met$empo_3==e),]
    sub_abun <- asv_table[,which(names(asv_table) %in% sub_sub_met$sequencing_id)]
    sub_abun <- data.frame(sub_abun)
    sub_abun <- sub_abun[which(rowSums(sub_abun) > 0),]
    sub_abun <- data.frame(sub_abun)
    
    asv_sums <- rowSums(sub_abun)
    emp_list[[e]] <- asv_sums
  }
  
  return(emp_list)
}

sites <- names(bact_asvs_by_site)

bact_emp_asv_sums <- lapply(sites,
                            make_emp_list,
                            bact_asvs_by_site,
                            bact_met,
                            bact_abun)

names(bact_emp_asv_sums) <- names(bact_asvs_by_site)

```

```{r}
## inext 

# job::job({
#   site1_inext <- iNEXT(emp_asv_sums[["OutsideRocks"]], nboot = 200) 
# })

#inext_list <- lapply(emp_asv_sums, function(x) iNEXT(x, nboot=200))

bact_inext_results <- list()

for (i in 1:length(bact_emp_asv_sums)) {
  dat <- bact_emp_asv_sums[[i]]
  counts <- sapply(dat, sum)
  end <- max(counts)
  
  curve_calc <- iNEXT(dat, nboot = 200, endpoint = (end*2))
  
  bact_inext_results[[i]] <- curve_calc
}


saveRDS(bact_inext_results, "../outputs/list_of_bact_inext_results_by_site_and_hab.rds")

lapply(bact_inext_results, ggiNEXT)

```

```{r}

bact_plot_list <- list()

for (i in 1:length(bact_inext_results)) {
  subt <- paste0("ASVs = ", nrow(bact_asvs_by_site[[i]]), ", Samples = ", ncol(bact_asvs_by_site[[i]]))
  
  plot <- ggiNEXT(bact_inext_results[[i]]) +
  theme_classic() +
  labs(title = paste(sites[[i]], subt, sep="\n")) +
  theme(plot.title = element_text(hjust = 0.5,
                                  size = 16,
                                  face = "bold",
                                  margin = margin(0,0,20,0)),
        axis.title.x = element_text(vjust=-2),
        axis.title.y = element_text(vjust=2)) +
  scale_shape_manual(values = rep(19, length(bact_emp_asv_sums[[i]]))) +
  #scale_color_brewer(palette = "Set2") +
  #scale_fill_brewer(palette = "Set2") +
  theme(plot.margin = margin(20,10,20,5)) +
  #scale_y_continuous(limits=c(0,30000), breaks=seq(0,30000, by = 10000)) +
  xlab("Number of sequences") +
  ylab("ASV richness")
  
  bact_plot_list[[i]] <- plot
}

saveRDS(bact_plot_list, "../intermediates/bact_emp_accum_curve_plot_list_with_habitat.rds")

```

```{r}

for (i in 1:length(bact_plot_list)) {
  ggsave(filename = paste0("../figures/bact_emp_accum_curves/", sites[[i]], "bact_accum_curve_with_hab.png"), plot = bact_plot_list[[i]], width = 8, height = 5)
}

```


```{r}
# how many samples and ASVs per plot?
nums <- data.frame(sapply(asvs_by_site, nrow))
nums$samp <- sapply(asvs_by_site, ncol)

names(nums) <- c("asv_abundance", "number_of_samples")

nums <- nums[order(-nums$asv_abundance),]
saveRDS(nums, "../intermediates/how_many_asvs_samps_per_plot.rds")
write.csv(nums, "../outputs/asv_and_sample_counts_by_plot.csv")
```








