---
title: "18_bact_increase_prev_thresh"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(dplyr)
library(tibble)
```

## Bacteria


```{r}

bact_abun <- readRDS("../intermediates/bact_culled_abun_otu_lauras_method_post_matchup.rds")
bact_meta <- readRDS("../intermediates/bact_culled_meta_otu_lauras_method_post_matchup.rds")

# sample names in abundance table eventually get "X" appended due to the colnames being numeric
# make a new column with these names
bact_meta$x_seq_ids <- paste0("X", bact_meta$sequencing_id)


bact_otu_sums <- data.frame(rowSums(bact_abun))
bact_otu_sums$sample_freq <- apply(bact_abun, 1, function(c)sum(c!=0))
names(bact_otu_sums) <- c("otu_abundance", "sample_freq")

bact_otu_sums <- rownames_to_column(bact_otu_sums, "ID")
bact_otu_sums <- arrange(bact_otu_sums, desc(sample_freq))
bact_otu_sums <- column_to_rownames(bact_otu_sums, "ID")

bact_otus_no_singlesamps <- bact_otu_sums[bact_otu_sums$sample_freq>1,]

bact_abun_no_singles <- bact_abun[rownames(bact_abun) %in% rownames(bact_otus_no_singlesamps),] # 63847 otus remain 
bact_abun_no_singles <- bact_abun_no_singles[,colSums(bact_abun_no_singles)>0] # 1313 samples
bact_met_no_singles <- bact_meta[as.character(bact_meta$sequencing_id) %in% names(bact_abun_no_singles),]
```


```{r}
new_bact_abun <- bact_abun_no_singles
new_bact_meta <- bact_met_no_singles


hab_subset <- function(asv_table, meta_table) {
  habs <- unique(meta_table$habitat)
  
  hab_list <- list()
  
  for (a_hab in habs) {
    sub_met <- meta_table[which(meta_table$habitat==a_hab),]
    
    sub_hab_abun <- asv_table[,which(names(asv_table) %in% sub_met$sequencing_id)]
    sub_hab_abun <- data.frame(sub_hab_abun)
    sub_hab_abun <- sub_hab_abun[which(rowSums(sub_hab_abun) > 0),]
    sub_hab_abun <- data.frame(sub_hab_abun)
    
    hab_list[[a_hab]] <- sub_hab_abun
    
  }
  
  return(hab_list)
}

bact_asvs_by_hab <- hab_subset(new_bact_abun, new_bact_meta)


```


```{r}
habs <- c("Marine", "Terrestrial", "Riverine")

# function to subset by empo3 based on prevalence threshold
make_emp_hab_prev_list <- function(hab, hab_list, meta_table, asv_table, prev_thresh) {
  
  dat <- hab_list[[hab]]
  samples <- names(dat)
  
  sub_met <- meta_table[which(meta_table$x_seq_ids %in% samples),]
  
  empo3 <- unique(sub_met$empo_3)
  emp_list <- list()
  
  for (e in empo3) {
    sub_sub_met <- sub_met[which(sub_met$empo_3==e),]
    sub_abun <- asv_table[,which(names(asv_table) %in% sub_sub_met$sequencing_id)]
    sub_abun <- data.frame(sub_abun)
    sub_abun <- sub_abun[which(rowSums(sub_abun) > 0),]
    sub_abun <- data.frame(sub_abun)
    
    asv_sums <- data.frame(rowSums(sub_abun))
    asv_sums$sample_freq <- apply(sub_abun, 1, function(c)sum(c!=0))
    names(asv_sums) <- c("asv_abundance", "sample_freq")
    asv_sums$tot_samps <- ncol(sub_abun)
    asv_sums$prev <- asv_sums$sample_freq/ncol(sub_abun)
    
    asv_sums <- rownames_to_column(asv_sums, "ID")
    asv_sums <- arrange(asv_sums, desc(sample_freq))
    asv_sums <- column_to_rownames(asv_sums, "ID")
    
    asv_sums <- asv_sums[asv_sums$prev>=prev_thresh,]
    
    emp_list[[e]] <- asv_sums
  }
  
  return(emp_list)
}


get_filtered_table <- function (emp_prev_list, otu_table) {
  all_things_listed <- lapply(emp_prev_list, function(x) lapply(x, rownames))
  flattened_ish <- lapply(all_things_listed, function(x) Reduce(c, x))
  
  all_things <- unlist(flattened_ish)

  all_things_unique <- unique(all_things)
  
  filtered_table <- otu_table[rownames(otu_table) %in% all_things_unique,]
  filtered_table <- filtered_table[,colSums(filtered_table)>0] 
  
  return(filtered_table)
}

```

```{r}
# 60% prevalence
bact_emp_prev60 <- lapply(habs,
                            make_emp_hab_prev_list,
                            bact_asvs_by_hab,
                            new_bact_meta,
                            new_bact_abun,
                            prev_thresh = 0.6)

bact_prev60_table <- get_filtered_table(bact_emp_prev60, new_bact_abun) # 2567 OTUs, 1313 samples


# 70% prevalence
bact_emp_prev70 <- lapply(habs,
                            make_emp_hab_prev_list,
                            bact_asvs_by_hab,
                            new_bact_meta,
                            new_bact_abun,
                            prev_thresh = 0.7)

bact_prev70_table <- get_filtered_table(bact_emp_prev70, new_bact_abun) # 1714 otus, 1313 samples


# 80% prevalence
bact_emp_prev80 <- lapply(habs,
                            make_emp_hab_prev_list,
                            bact_asvs_by_hab,
                            new_bact_meta,
                            new_bact_abun,
                            prev_thresh = 0.8)

bact_prev80_table <- get_filtered_table(bact_emp_prev80, new_bact_abun) # 1006 otus, 1313 samples


saveRDS(bact_prev60_table, "../networks/bact_prev_test/input_data/bact_prev60_otu_table.rds")
saveRDS(bact_prev70_table, "../networks/bact_prev_test/input_data/bact_prev70_otu_table.rds")
saveRDS(bact_prev80_table, "../networks/bact_prev_test/input_data/bact_prev80_otu_table.rds")



saveRDS(bact_abun_prevfilter_on_empo, "../networks/input_data/bact_prev50_otu_abun.rds")

filt_bact_meta <- new_bact_meta[which(as.character(new_bact_meta$sequencing_id) %in% names(bact_abun_prevfilter_on_empo)),]
```






