---
title: "13_network_visualization"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message=FALSE}
library(igraph)
library(SpiecEasi)
```

```{r}
network <- readRDS("../networks/bact_prev_test/outputs/batch_bact_prev80.rds")

data <- readRDS("../networks/bact_prev_test/input_data/bact_prev80_otu_table.rds")

tax_table <- readRDS("../intermediates/bact_otu_taxonomy_table.rds")
tax_table <- tax_table[tax_table$OTU %in% rownames(data),]

#metadata <- readRDS("../intermediates/prev20_bact_otu_metadata_matched_up.rds")

```

```{r}
vsize    <- rowMeans(clr(data, 1))+3

net_test2     <- adj2igraph(getRefit(network), vertex.attr=list(name=rownames(data)))

net_test <- adj2igraph(getRefit(network))

g_data <-  get.data.frame(net_test2,  what="vertices")$name


getOptInd(network)
sum(getRefit(network))/2


getStability(network)
sum(getRefit(network))/2

```

```{r}
library(GGally)
library(ggpubr)

#net_try_simplify <- simplify(net_try)

a <- ggnet2(net_test2, node.size = 1, color = "#c6cdf7") + labs(title = "Bacteria OTUs, 80% prevalence", subtitle = "Batch test, lossy screening on")

ggsave("../figures/testnetwork_full_fung_prev20_rarefied.png", width = 7, height = 6)

```

```{r}
coords.fdr = layout_with_fr(net_test2)

E(net_test2)[weight > 0]$color<-"steelblue"
E(net_test2)[weight < 0]$color<-"orange"

plot(net_test2, layout=coords.fdr, vertex.size = 2, vertex.label.cex = 0.5)


library(ggnet)
mynet <- asNetwork(net_test2)
network::set.edge.attribute(mynet, "color", ifelse(mynet %e% "weight" > 0, "steelblue", "orange"))


library(microbiome)
phyla <- map_levels(tax_table$Genus, from = "Genus", to = "Phylum", tax_table)
mynet %v% "Phylum" <- phyla
mynet %v% "nodesize" <- vsize


library(pals)
ab = polychrome()
ab31 = ab[1:length(unique(phyla))]
names(ab31) <- unique(phyla) # named palette input to ggnet2 must correspond to phylum names!! or whatever variable desired

p <- ggnet2(mynet, color = "Phylum", palette=ab31,node.size = 1, 
            edge.color = "color", mode = "fruchtermanreingold") 
+ guides(color=guide_legend(title="Phylum"), size = FALSE)



```



```{r}
separation_r <- NULL
        g <- net_test2
        g <- subgraph(g,igraph::degree(g)>0)
        apl <- average.path.length(g)
        separation_r <- c(separation_r, apl)

m = modularity(g,membership(cluster_fast_greedy(g)))


cfg <- cluster_fast_greedy(as.undirected(g))

plot(cfg, g, vertex.label=NA, vertex.size=5)

```

```{r}
#hub 
hs <- hub_score(net_test2, weights=NA)$vector

ordered_hubs <- sort(hs, decreasing=TRUE)
t = tax_table[tax_table$OTU %in% names(ordered_hubs)[1:5],]


plot(g, vertex.size=hs*50, main="Hubs", vertex.label=NA)
```

```{r}
diameter(g)


hist(degree(mynet))

hist(edge.betweenness(g))

hist(igraph::betweenness(g))

which.max(degree(mynet))

plot(degree_distribution(g, cumulative = TRUE))
```










