---
title: "11_cross_domain_network"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#read in data
fung_asv_table <- readRDS("../intermediates/fungal_asv_table_matched_up.rds")
fung_metadata <- readRDS("../intermediates/fungal_metadata_matched_up.rds")

bact_asv_table <- readRDS("../intermediates/bact_asv_table_matched_up.rds")
bact_metadata <- readRDS("../intermediates/bact_metadata_matched_up.rds")

# sample names in abundance table eventually get "X" appended due to the colnames being numeric
# make a new column with these names
fung_metadata$x_seq_ids <- paste0("X", fung_metadata$sequencing_id)
bact_metadata$x_seq_ids <- paste0("X", bact_metadata$sequencing_id)

```

```{r}
# want one list per plot/site, where each item in the list is a vector of nonzero ASV abundances corresponding to each EMPO3 cateogory
# gonna need a loop or apply

# also want to subset sites with multiple habitats (stream, marine, terrestrial) by habitat type

site_subset <- function(asv_table, meta_table) {
  sites <- unique(meta_table$site_name)
  
  site_list <- list()
  
  for (a_site in sites) {
    sub_met <- meta_table[which(meta_table$site_name==a_site),]
    
      if (length(unique(sub_met$habitat != 1))) {
        habs <- unique(sub_met$habitat)
        
          for (a_hab in habs) {
            sub_hab_met <- sub_met[which(sub_met$habitat==a_hab),]
            
            sub_hab_abun <- asv_table[,which(names(asv_table) %in% sub_hab_met$sequencing_id)]
            sub_hab_abun <- data.frame(sub_hab_abun)
            sub_hab_abun <- sub_hab_abun[which(rowSums(sub_hab_abun) > 0),]
            sub_hab_abun <- data.frame(sub_hab_abun)
            
            site_hab_name <- paste(a_site, a_hab, sep=", ")
            
            site_list[[site_hab_name]] <- sub_hab_abun
            
          }
        
      } else {
        
        sub_abun <- asv_table[,which(names(asv_table) %in% sub_met$sequencing_id)]
        sub_abun <- sub_abun[which(rowSums(sub_abun) > 0),]
        
        hab <- unique(sub_met$habitat)
        hab_name <- paste(a_site, hab, sep=", ")
        
        site_list[[hab_name]] <- sub_abun
        
      }
    
  }
  
  return(site_list)
}



#4, 5

make_emp_asv_tables <- function(site, site_list, meta_table, asv_table) {
  
  dat <- site_list[[site]]
  samples <- names(dat)
  
  sub_met <- meta_table[which(meta_table$x_seq_ids %in% samples),]
  
  empo3 <- unique(sub_met$empo_3)
  emp_list <- list()
  
  for (e in empo3) {
    sub_sub_met <- sub_met[which(sub_met$empo_3==e),]
    sub_abun <- asv_table[,which(names(asv_table) %in% sub_sub_met$sequencing_id)]
    sub_abun <- data.frame(sub_abun)
    sub_abun <- sub_abun[which(rowSums(sub_abun) > 0),]
    sub_abun <- data.frame(sub_abun)
    
    #asv_sums <- rowSums(sub_abun)
    emp_list[[e]] <- sub_abun
  }
  
  return(emp_list)
}


```


```{r}
fung_asvs_by_site <- site_subset(fung_asv_table, fung_metadata)

names(fung_asvs_by_site[["DrumRoad, Marine"]]) <- "X102318"


fung_sites <- names(fung_asvs_by_site)

fung_emp_asv_sums <- lapply(fung_sites,
                            make_emp_asv_tables,
                            fung_asvs_by_site,
                            fung_metadata,
                            fung_asv_table)

names(fung_emp_asv_sums) <- names(fung_asvs_by_site)

```

```{r}
bact_asvs_by_site <- site_subset(bact_asv_table, bact_metadata)


bact_sites <- names(bact_asvs_by_site)

bact_emp_asv_sums <- lapply(bact_sites,
                            make_emp_asv_tables,
                            bact_asvs_by_site,
                            bact_metadata,
                            bact_asv_table)

names(bact_emp_asv_sums) <- names(bact_asvs_by_site)

lapply(bact_emp_asv_sums, function(x) lapply(x, dim))

```

Test: Entrance Terrestrial Plant surface

```{r}
bact_test_table <- as.data.frame(bact_emp_asv_sums[["Entrance, Terrestrial"]]["Plant surface"])

fung_test_table <- as.data.frame(fung_emp_asv_sums[["Entrance, Terrestrial"]]["Plant surface"])

# temp fix
names(bact_test_table) <- seq(1:6)
names(fung_test_table) <- seq(1:6)

saveRDS(bact_test_table, "../networks/input_data/bact_entrance_terrestrial_plantsurface.rds")
saveRDS(fung_test_table, "../networks/input_data/fung_entrance_terrestrial_plantsurface.rds")

```






