---
title: "12_cull_by_freqdist_terrestrial"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#read in data
fung_asv_table <- readRDS("../intermediates/fungal_asv_table_matched_up.rds")
fung_metadata <- readRDS("../intermediates/fungal_metadata_matched_up.rds")

bact_asv_table <- readRDS("../intermediates/bact_asv_table_matched_up.rds")
bact_metadata <- readRDS("../intermediates/bact_metadata_matched_up.rds")

# sample names in abundance table eventually get "X" appended due to the colnames being numeric
# make a new column with these names
fung_metadata$x_seq_ids <- paste0("X", fung_metadata$sequencing_id)
bact_metadata$x_seq_ids <- paste0("X", bact_metadata$sequencing_id)

```

```{r}
fung_met_terr <- fung_metadata[which(fung_metadata$habitat=="Terrestrial"),]
fung_abun_terr <- fung_asv_table[,which(names(fung_asv_table) %in% fung_met_terr$sequencing_id)]
fung_abun_terr <- fung_abun_terr[rowSums(fung_abun_terr)>0,]

f_asv_sums <- data.frame(rowSums(fung_abun_terr))
f_asv_sums$asv <- rownames(fung_abun_terr)
f_asv_sums$sample_freq <- apply(fung_abun_terr, 1, function(c)sum(c!=0))
names(f_asv_sums) <- c("asv_abundance", "asv", "sample_freq")
f_asv_sums <- arrange(f_asv_sums, desc(sample_freq))

f_asv_sums_top1000 <- f_asv_sums[1:1000,]
fung_abun_terr_freq_culled <- fung_abun_terr[rownames(fung_abun_terr) %in% f_asv_sums_top1000$asv,]
fung_abun_terr_freq_culled <- fung_abun_terr_freq_culled[,colSums(fung_abun_terr_freq_culled)>0]

```

```{r}
## just for now, pick one empo3 category to run network with
f_met_pc <- fung_met_terr[fung_met_terr$empo_3=="Plant corpus" & fung_met_terr$site_name=="Entrance",]

# 19 of 21 entrance plant corpus samples are in the top1000 terrestrial ITS ASV table
f_abun_pc <- fung_abun_terr_freq_culled[,names(fung_abun_terr_freq_culled) %in% f_met_pc$sequencing_id]
f_abun_pc <- f_abun_pc[rowSums(f_abun_pc)>0,]

saveRDS(f_abun_pc, "../networks/input_data/fung_entrance_terr_top1000_plantcorpus.rds")

```





