---
title: "13_network_visualization"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(igraph)
library(SpiecEasi)
```

```{r}
plantcorp_terr_entr_net <- readRDS("../networks/outputs/fungal_entrance_terrestrial_plantcorpus.rds")

pc_terr_entr_data <- readRDS("../networks/input_data/fung_entrance_terr_top1000_plantcorpus.rds")

```

```{r}
vsize    <- rowMeans(clr(pc_terr_entr_data, 1))+3

net_test     <- adj2igraph(getRefit(plantcorp_terr_entr_net))

am.coord <- layout.fruchterman.reingold(net_test)

plot(net_test, layout=am.coord, vertex.size=vsize, vertex.label=NA, main="glasso")


# network has no connections
getOptInd(plantcorp_terr_entr_net)
sum(getRefit(plantcorp_terr_entr_net))/2


getStability(plantcorp_terr_entr_net)
sum(getRefit(plantcorp_terr_entr_net))/2
```

```{r}
library(GGally)

ggnet2(net_test, node.size = 1, color = "navyblue") + ggtitle("Terrestrial Fungal Plant Corpus, Site: Entrance")
ggsave("../figures/testnetwork_terr_fung_plantcorp_entrance.png", width = 5, height = 4)
```






