---
title: "13_network_visualization"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(igraph)
library(SpiecEasi)
```

```{r}
terr_entrance_network <- readRDS("../networks/outputs/fungal_entrance_terrestrial_network_all_empos.rds")

terr_entr_too_fast <- readRDS("../networks/outputs/fung_entr_terr_finished_too_fast.rds")

#pc_terr_entr_data <- readRDS("../networks/input_data/fung_entrance_terr_top1000_plantcorpus.rds")

```

```{r}
#vsize    <- rowMeans(clr(pc_terr_entr_data, 1))+3

net_test     <- adj2igraph(getRefit(terr_entrance_network))

net_try <- graph_from_adjacency_matrix(getRefit(terr_entrance_network))


net_toofast <- graph_from_adjacency_matrix(getRefit(terr_entr_too_fast))

# max(abs(terr_entrance_network$est$icov - t(terr_entrance_network$est$icov)))
# 
# c = as.matrix(getRefit(terr_entrance_network))
# 
# #fixing it
# se.gl.small.refit <- SpiecEasi::tril(c) + t(SpiecEasi::tril(c))
# ig.gl <- adj2igraph(se.gl.small.refit)

# am.coord <- layout.fruchterman.reingold(net_test)
# 
# plot(net_test, layout=am.coord, vertex.size=vsize, vertex.label=NA, main="glasso")


# network has no connections
getOptInd(terr_entrance_network)
sum(getRefit(terr_entrance_network))/2


getStability(terr_entrance_network)
sum(getRefit(terr_entrance_network))/2


# network has no connections
getOptInd(terr_entr_too_fast)
sum(getRefit(terr_entr_too_fast))/2


getStability(terr_entr_too_fast)
sum(getRefit(terr_entr_too_fast))/2
```

```{r}
library(GGally)
library(ggpubr)

a <- ggnet2(net_try, node.size = 1, color = "#c6cdf7") + labs(title = "Terrestrial Fungal All EMPO3s, Site: Entrance", subtitle = "Default Settings, 28 hours")
#ggsave("../figures/testnetwork_terr_fung_plantcorp_entrance.png", width = 5, height = 4)

b <- ggnet2(net_toofast, node.size = 1, color = "#d8a499") + labs(title = "Terrestrial Fungal All EMPO3s, Site: Entrance", subtitle = "lambda.min.ratio=1e-1, nlambda=50, 20 min")

ab <- ggarrange(a, b, ncol = 2)

ggsave("../figures/testnetwork_terr_fung_allempos_entrance_twoplot.png", width = 11, height = 5)
```






