---
title: "13_network_visualization"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(igraph)
library(SpiecEasi)
```

```{r}
terr_entrance_network <- readRDS("../networks/outputs/fungal_entrance_terrestrial_network_allempos_zeroinflatedfilt.rds")

terr_entr_data <- readRDS("../networks/input_data/fung_entrance_terr_top1000_allempos_in_site_entrance.rds")

metadata <- readRDS("../intermediates/fungal_metadata_matched_up.rds")

```

```{r}
#vsize    <- rowMeans(clr(pc_terr_entr_data, 1))+3

#net_test     <- adj2igraph(getRefit(terr_entrance_network), vertex.attr=list(name=rownames(terr_entr_data)))


#g_data <-  get.data.frame(net_test,  what="vertices")$name

net_try <- graph_from_adjacency_matrix(terr_entrance_network[[100]])


#net_toofast <- graph_from_adjacency_matrix(getRefit(terr_entr_too_fast))

# max(abs(terr_entrance_network$est$icov - t(terr_entrance_network$est$icov)))
# 
# c = as.matrix(getRefit(terr_entrance_network))


# network has no connections
getOptInd(terr_entrance_network)
sum(getRefit(terr_entrance_network))/2


getStability(terr_entrance_network)
sum(getRefit(terr_entrance_network))/2


# network has no connections
getOptInd(terr_entr_too_fast)
sum(getRefit(terr_entr_too_fast))/2


getStability(terr_entr_too_fast)
sum(getRefit(terr_entr_too_fast))/2
```

```{r}
library(GGally)
library(ggpubr)

net_try_simplify <- simplify(net_try)

a <- ggnet2(net_try_simplify, node.size = 1, color = "#c6cdf7") + labs(title = "Terrestrial Fungal All EMPO3s, Site: Entrance", subtitle = "Zero inflated filter applied")

ggsave("../figures/testnetwork_terr_fung_entrance_zeroinfl_filtered.png", width = 5, height = 4)

```


```{r}
separation_r <- NULL
        g <- net_test
        g <- subgraph(g,igraph::degree(g)>0)
        apl <- average.path.length(g)
        separation_r <- c(separation_r, apl)

m = modularity(g,membership(cluster_fast_greedy(g)))

```








