---
title: "14_zero_inflated_filter"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# load data
fung_asv_table <- readRDS("../intermediates/no_singlesampASVs_fung_asv_table.rds")
fung_asv_table <- t(fung_asv_table)

bact_asv_table <- readRDS("../intermediates/no_singlesampASVs_bact_asv_table.rds")
bact_asv_table <- t(bact_asv_table)

```

Below function is from https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0200458

```{r}
##############################################################################################
# 
# Filtering function by pair of OTU prevalence 
# for abundance data and for presence /absence data
#
# INRA Theix, le 15/11/2018
# 
# Rarity of microbial species: In search of reliable associations
# PLOS ONE
# 
# Arnaud Cougoul, Xavier Bailly , Gwena?l Vourch, Patrick Gasqui
#
##############################################################################################


##############################################################################################
# Filtering function for abundance data
# otu_table: a matrix of count data with samples per row and species per column
# risk: alpha level for testability
# return a matrix whose values are equal to 1 for OTU pairs fully testable and 0 if not.


filter_by_pair <- function (otu_table, risk=0.05){
  
  prevalence = colMeans (otu_table>0)
  N = dim(otu_table)[1]
  d = dim(otu_table)[2]
  
  tt = qt(1-risk/2, N-2, lower.tail = TRUE)
  K = (tt^2)/(N-2+tt^2)
  
  f1<-function(x){(1-x)/(1+((1-K)/K)*x)}
  
  res <- matrix(0,ncol=d,nrow=d)
  for (i in 1:(d-1)){
    for (j in (i+1):d){
      if(f1(prevalence[i]) < prevalence[j]) res[i,j]<-1
    }
  } 
  
  res <- res+t(res)
  diag(res)=1
  res
}

```

```{r}
# apply filtering function to our data
fung_abun_zeroinf_filt <- filter_by_pair(fung_asv_table, risk = 0.05)

saveRDS(fung_abun_zeroinf_filt, "../networks/input_data/full_fung_zeroinf_filtered.rds")

```










