---
title: "Outlier Analysis"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, echo=FALSE, message=FALSE}

library(MASS)
library(dplyr)
library(ggplot2)
library(ggpubr)

```

We want to look for outliers by habitat and by guild in terms of observed ASV richness.

```{r}

# read in the data
culled_abun <- readRDS("../intermediates/culled_asv_table.rds")
culled_tax <- readRDS("../intermediates/culled_tax_table.rds")
culled_meta <- readRDS("../intermediates/culled_metadata.rds")

culled_meta <- data.frame(culled_meta)


```

I need a linear model. The unit of this will be at the ASV level (read count by ASV), not sample
Do studres() on a linear model of richness ~ ASV for every guild in each of the 3 habitats?
Collapse ASV table. Model read count vector by ASV name vector


```{r}

# 1st try - marine  and primary producer

# subset ASV table

# find which sample IDs are for PPs in Marine
pp_mar_id <- culled_meta[which(culled_meta$trophic=="PrimaryProducer" & culled_meta$habitat=="Marine"),][["sequencing_id"]]

# subset ASV table by these IDs
pp_mar_asvs <- culled_abun[,names(culled_abun) %in% pp_mar_id]
# remove empty ASVs - 27167 ASVs
pp_mar_asvs <- pp_mar_asvs[rowSums(pp_mar_asvs)>0,]

pp_mar_sums <- rowSums(pp_mar_asvs)

pp_mar_names <- rownames(pp_mar_asvs)

df <- data.frame(pp_mar_names, pp_mar_sums)


mod <- lm(pp_mar_sums ~ 1, data = df)

res <- studres(mod)



res_over3 <- res[abs(res)>3]

# res_over4 <- nonzero_res[nonzero_res>4]


outlier_names <- names(res_over3)

out_tbl <- pp_mar_asvs[rownames(pp_mar_asvs) %in% outlier_names,]
# remove empty samples
out_tbl <- out_tbl[,colSums(out_tbl)>0]

summary(rowSums(out_tbl))


all_pp_mar <- sum(pp_mar_sums)

all_out <- sum(rowSums(out_tbl))

s = all_pp_mar - all_out

s / (all_pp_mar + all_out) # removing these ASVs would remove 34% of the fungal ASV richness in marine primary producers


```

```{r}

# 2nd try - terrestrial and environmental

# subset ASV table

# find which sample IDs are for env in terrestrial
env_terr_id <- culled_meta[which(culled_meta$trophic=="Environmental" & culled_meta$habitat=="Terrestrial"),][["sequencing_id"]]

# subset ASV table by these IDs
env_terr_asvs <- culled_abun[,names(culled_abun) %in% env_terr_id]
# remove empty ASVs - 27167 ASVs
env_terr_asvs <- env_terr_asvs[rowSums(env_terr_asvs)>0,]

env_terr_sums <- rowSums(env_terr_asvs)

env_terr_names <- rownames(env_terr_asvs)

new_df <- data.frame(env_terr_names, env_terr_sums)


mod2 <- lm(env_terr_sums ~ 1, data = new_df)

res2 <- studres(mod2)



new_res_over3 <- res2[abs(res2)>3]

# res_over4 <- nonzero_res[nonzero_res>4]


new_outlier_names <- names(new_res_over3)

new_out_tbl <- env_terr_asvs[rownames(env_terr_asvs) %in% new_outlier_names,]
# remove empty samples
new_out_tbl <- new_out_tbl[,colSums(new_out_tbl)>0]

summary(rowSums(new_out_tbl))


all_env_terr <- sum(env_terr_sums)

all_new_out <- sum(rowSums(new_out_tbl))

d = all_env_terr - all_new_out

d / (all_env_terr + all_new_out) # removing these ASVs would remove 30% of the fungal ASV richness in terrestrial environmental samples


```








