---
title: "4_richness_violin"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}

library(dplyr)

```

```{r}

#data import
abun <- readRDS("../intermediates/culled_asv_table.rds")
meta <- data.frame(readRDS("../intermediates/culled_metadata.rds"))

```

```{r}

# want to write a function to create data frames with sample id, ASV richness, habitat, and guild

# steps:
# for a given habitat and trophic combination (inputs). ASV table is also an input, and metadata
# get sample ids from metadata table
# subset ASV table by these sample ids and remove empty samples/ASVs
# for every sample, take the sum of every cell > 0 (richness)
# transpose, make data frame
# make habitat and guild columns, repeat the name down the whole way

# lapply over habitat? and guild? is there a for loop for guild in the function that we do a lapply over habitat for?

# hab = "Riverine"
# tro = "Environmental"


# collapse "Omnivore", "Herbivore", "Detritivore", "Carnivore" into "Consumer"
consumers <- c("Omnivore", "Herbivore", "Detritivore", "Carnivore")
meta$trophic[meta$trophic %in% consumers] <- "Consumer"


# function to make tables of ASV richness by sample for a given habitat-trophic level combo
make_sample_tables <- function(tro, hab, metadata, asv_table) {
    
    sub_met = metadata[which(metadata$habitat==hab & metadata$trophic==tro),][["sequencing_id"]]
    
    asvs <- asv_table[,names(asv_table) %in% sub_met]
      
    # remove empty ASVs
    asvs <- asvs[rowSums(asvs)>0,]
    
    rich = data.frame(lapply(asvs, function(x) sum(x>0)))
    
    b = data.frame("sequencing_id" = colnames(asvs),
                   "richness" = t(rich),
                   "habitat" = rep(hab, length(rich)),
                   "trophic" = rep(tro, length(rich)))
    
    rownames(b) = NULL
    
    return(b)

  
}


guilds = c("PrimaryProducer", "Environmental", "Consumer")

habitats = c("Terrestrial", "Riverine", "Marine")


big_list = list()

# makes a list of lists (3 habitat lists, 3 guild tables within each list)
for (a_hab in habitats) {
  
  big_list[[a_hab]] = lapply(guilds,
                      make_sample_tables,
                      hab = a_hab,
                      metadata = meta,
                      asv_table = abun)
  
}

# name lists by hab-troph combo
for(a_hab in habitats) {
  
  for (i in 1:length(big_list)) {
    names(big_list[[a_hab]])[i] <- paste(a_hab, guilds[i], sep="_")
  }

  
}

# collapse into 1 list of 9 tables
bigger_list <- unlist(big_list, recursive = FALSE)

# there aren't any consumers in the Marine data, but the Unknown data appear to be consumers
# replace the empty table under marine consumer with a table for marine unknown
bigger_list[["Marine.Marine_Consumer"]] <- make_sample_tables("Unknown", "Marine", meta, abun)

big_df <- do.call("rbind", bigger_list)

# rename unknown marine to consumer
big_df$trophic[big_df$trophic=="Unknown"] <- "Consumer"

saveRDS(big_df, "../intermediates/big_richness_data_frame.rds")

```

```{r}

# plotting! or attempting to

p <- ggplot(big_df, aes(x = habitat, y = richness, fill = trophic)) +
  geom_violin(aes(color = trophic), position = position_dodge(0.6), width = 1.5) +
  geom_point(pch = 19, position = position_jitterdodge(dodge.width=0.6, jitter.width=0.20), size=0.3, alpha = 0.4, show.legend = FALSE) +
  stat_summary(fun.min = function(z) { quantile(z,0.25) },
               fun.max = function(z) { quantile(z,0.75) },
               fun = median,
               position = position_dodge(0.6),
               color = "white", show.legend = FALSE) +
  scale_color_brewer(palette = "Set2") +
  scale_fill_brewer(palette = "Set2") +
  theme(panel.grid.major=element_blank(), panel.grid.minor=element_blank(),
        panel.background=element_blank(), 
        axis.title.x = element_text(size=14, margin = margin(15,0,0,0)),
        axis.title.y = element_text(size=14, margin = margin(0,10,0,0)),
        axis.line = element_line(colour="black"),
        axis.text.x = element_text(size=12, colour="black"),
        axis.text.y = element_text(size=12, colour="black"),
        legend.title = element_text(size=14),
        legend.text = element_text(size=12, colour="black")) +
  labs(x = "Habitat", y = "ASV richness", fill = "Trophic levels") +
  guides(color = "none") +
  scale_y_continuous(expand = c(0, 0), limits = c(0,2500))

options(bitmapType='cairo')
ggsave("../figures/richness_violins_nomosslichen.png", width = 11, height = 7)


# want to make a subplot with marine only so that the y axis isn't so squished
mar_df <- big_df[which(big_df$habitat=="Marine"),]

mar_p <- ggplot(mar_df, aes(x = habitat, y = richness, fill = trophic)) +
  geom_violin(aes(color = trophic), position = position_dodge(0.8), width = 1.5) +
  geom_point(pch = 19, position = position_jitterdodge(dodge.width=0.8, jitter.width=0.20), size=0.3, alpha = 0.4, show.legend = FALSE) +
  stat_summary(fun.min = function(z) { quantile(z,0.25) },
               fun.max = function(z) { quantile(z,0.75) },
               fun = median,
               position = position_dodge(0.8),
               color = "white", show.legend = FALSE) +
  scale_color_brewer(palette = "Set2") +
  scale_fill_brewer(palette = "Set2") +
  theme(panel.grid.major=element_blank(), panel.grid.minor=element_blank(),
        panel.background=element_blank(), 
        axis.title.x = element_text(size=14, margin = margin(15,0,0,0)),
        axis.title.y = element_text(size=14, margin = margin(0,10,0,0)),
        axis.line = element_line(colour="black"),
        axis.text.x = element_text(size=12, colour="black"),
        axis.text.y = element_text(size=12, colour="black"),
        legend.title = element_text(size=14),
        legend.text = element_text(size=12, colour="black")) +
  labs(x = "Habitat", y = "ASV richness", fill = "Trophic levels") +
  guides(color = "none") +
  scale_y_continuous(expand = c(0, 0), limits = c(0,1000))

ggsave("../figures/richness_violins_marine_only.png", width = 11, height = 7)


mar_squish <- ggplot(mar_df, aes(x = habitat, y = richness, fill = trophic)) +
  geom_violin(aes(color = trophic), position = position_dodge(0.8), width = 1.5) +
  geom_point(pch = 19, position = position_jitterdodge(dodge.width=0.8, jitter.width=0.20), size=0.3, alpha = 0.4, show.legend = FALSE) +
  stat_summary(fun.min = function(z) { quantile(z,0.25) },
               fun.max = function(z) { quantile(z,0.75) },
               fun = median,
               position = position_dodge(0.8),
               color = "white", show.legend = FALSE) +
  scale_color_brewer(palette = "Set2") +
  scale_fill_brewer(palette = "Set2") +
  theme(panel.grid.major=element_blank(), panel.grid.minor=element_blank(),
        panel.background=element_blank(), 
        axis.title.x = element_text(size=14, margin = margin(15,0,0,0)),
        axis.title.y = element_text(size=14, margin = margin(0,10,0,0)),
        axis.line = element_line(colour="black"),
        axis.text.x = element_text(size=12, colour="black"),
        axis.text.y = element_text(size=12, colour="black"),
        legend.title = element_text(size=14),
        legend.text = element_text(size=12, colour="black")) +
  labs(x = "Habitat", y = "ASV richness", fill = "Trophic levels") +
  guides(color = "none") +
  scale_y_continuous(expand = c(0, 0), limits = c(0,200))

ggsave("../figures/richness_violins_marine_squish.png", width = 11, height = 7)

```


Who are the outliers?

```{r}

out <- big_df[which(big_df$richness>1800),]
#out <- out[order(-out$richness),]

out_meta <- meta[which(meta$sequencing_id %in% out$sequencing_id),]

out$sample_type <- out_meta$sample_type
out$site <- out_meta$site_name

rownames(out) <- NULL

saveRDS(out, "../intermediates/potential_outlier_identities.rds")



# marine outlier

mar_out <- mar_df[which(mar_df$richness>750),]
#out <- out[order(-out$richness),]

mar_out_meta <- meta[which(meta$sequencing_id %in% mar_out$sequencing_id),]

mar_out$sample_type <- mar_out_meta$sample_type
mar_out$site <- mar_out_meta$site_name

rownames(mar_out) <- NULL

saveRDS(mar_out, "../intermediates/potential_marine_outlier.rds")

```


### ANOVA

```{r}

# asking if the means in richness differ between guilds within a habitat
mar_df # already have from before

ter_df <- big_df[which(big_df$habitat=="Terrestrial"),]

str_df <- big_df[which(big_df$habitat=="Riverine"),]


# marine
mar_rich_aov <- aov(formula = richness ~ trophic, data = mar_df)
mar_tuk <- TukeyHSD(mar_rich_aov)


# terrestrial
ter_rich_aov <- aov(formula = richness ~ trophic, data = ter_df)
ter_tuk <- TukeyHSD(ter_rich_aov)

# stream
str_rich_aov <- aov(formula = richness ~ trophic, data = str_df)
str_tuk <- TukeyHSD(str_rich_aov)

```







