---
title: "7_core"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}

library(dplyr)
library(ggplot2)
library(tibble)
library(reshape2)

```

```{r}
#data import
abun <- readRDS("../intermediates/culled_asv_table.rds") # samples are columns, ASVs are rows
meta <- readRDS("../intermediates/culled_metadata.rds")

meta <- data.frame(meta)

# collapse "Omnivore", "Herbivore", "Detritivore", "Carnivore" into "Consumer"
consumers <- c("Omnivore", "Herbivore", "Detritivore", "Carnivore")
meta$trophic[meta$trophic %in% consumers] <- "Consumer"
# convert marine "Unknown" trophic to consumer
meta$trophic[meta$habitat=="Marine" & meta$trophic=="Unknown"] <- "Consumer"

```


### Data Wrangling

```{r}

abun2 <- rownames_to_column(abun, "ASV")
# check sample numbers - yes there are no empty samples
# melt2 <- melt(abun2)
# melt2$habitat <- meta$habitat[match(melt2$variable, meta$sequencing_id)]
# melt2$trophic <- meta$trophic[match(melt2$variable, meta$sequencing_id)]
# 
# mar_melt2 <- melt2[which(melt2$habitat=="Marine"),]
# str_melt2 <- melt2[which(melt2$habitat=="Riverine"),]
# ter_melt2 <- melt2[which(melt2$habitat=="Terrestrial"),]

melt_abun <- melt(abun2)
melt_abun <- melt_abun[melt_abun$value>0,]
colnames(melt_abun)[2] <- "sequencing_id"

# add habitat and trophic columns matching by sequencing ID
melt_abun$habitat <- meta$habitat[match(melt_abun$sequencing_id, meta$sequencing_id)]
melt_abun$trophic <- meta$trophic[match(melt_abun$sequencing_id, meta$sequencing_id)]


trophs = c("PrimaryProducer", "Environmental", "Consumer")
habitats = c("Terrestrial", "Riverine", "Marine")


melt_list <- list()

# subset melted df by trophic level and habitat
make_melt_tables <- function(tro, hab, melt_table) {
    sub_df <- melt_table[which(melt_table$habitat==hab & melt_table$trophic==tro),]
    return(sub_df)
}

for (a_hab in habitats) {
  melt_list[[a_hab]] = lapply(trophs,
                              make_melt_tables,
                              hab = a_hab,
                              melt_table = melt_abun)
}


num_samps <- list()
# get the total number of samples in a trophic level (within a habitat) for prevalence denominator
for (a_hab in habitats) {
  num_samps[[a_hab]] <- sapply(melt_list[[a_hab]], function(x) length(unique(x$sequencing_id)))
}

# chk <- melt_abun[which(!(melt_abun$habitat %in% c("Marine", "Riverine", "Terrestrial"))),] # good, extras are not in 3 habitats of interest (lab and NA)


# formula to prevalence of given ASV across samples in a guild within habitat
prev_calc <- function(df, denom) {
  # df will already be subset by trophic level within habitat
  df <- as.data.frame(df)
  df <- df %>% group_by(ASV) %>% summarise(prev = n_distinct(sequencing_id)/denom)
  return(df)
}

# didn't work
# for (i in 1:length(num_samps)) {
#   ter <- lapply(melt_list[["Terrestrial"]], prev_calc, num_samps[["Terrestrial"]][i])
#   str <- lapply(melt_list[["Riverine"]], prev_calc, num_samps[["Riverine"]][i])
#   mar <- lapply(melt_list[["Marine"]], prev_calc, num_samps[["Marine"]][i])
# }

ter <- str <- mar <- list()

ter[[1]] <- prev_calc(melt_list[["Terrestrial"]][1], num_samps[["Terrestrial"]][1])
ter[[2]] <- prev_calc(melt_list[["Terrestrial"]][2], num_samps[["Terrestrial"]][2])
ter[[3]] <- prev_calc(melt_list[["Terrestrial"]][3], num_samps[["Terrestrial"]][3])


str[[1]] <- prev_calc(melt_list[["Riverine"]][1], num_samps[["Riverine"]][1])
str[[2]] <- prev_calc(melt_list[["Riverine"]][2], num_samps[["Riverine"]][2])
str[[3]] <- prev_calc(melt_list[["Riverine"]][3], num_samps[["Riverine"]][3])


mar[[1]] <- prev_calc(melt_list[["Marine"]][1], num_samps[["Marine"]][1])
mar[[2]] <- prev_calc(melt_list[["Marine"]][2], num_samps[["Marine"]][2])
mar[[3]] <- prev_calc(melt_list[["Marine"]][3], num_samps[["Marine"]][3])


names(ter) <- names(str) <- names(mar) <- trophs

t <- lapply(ter, function(x) arrange(x, desc(prev)))
s <- lapply(str, function(x) arrange(x, desc(prev)))
m <- lapply(mar, function(x) arrange(x, desc(prev)))

```

### Plotting

```{r}
prev_plot <- function(df) {
  p <- ggplot(data = df, aes(x=ASV, y=prev)) +
    geom_point(alpha = 0.3) +
    theme(axis.text.x = element_blank(),
          axis.line = element_line(colour="black")) +
    geom_hline(yintercept = 0.8, color="blue") +
    geom_hline(yintercept = 0.6, color="red") +
    scale_y_continuous(expand = c(0, 0), limits = c(0,1.0))
  
  return(p)
}

# terrestrial 
ter_plots <- lapply(t, prev_plot)

for (i in 1:length(trophs)) {
  tp <- ter_plots[[i]] + labs(title = trophs[i])
  ter_plots[[i]] <- tp
}

library(ggpubr)

a <- ggarrange(ter_plots[[1]], ter_plots[[2]], ter_plots[[3]], nrow = 1, 
               vjust = 0.1,
               #labels = c(trophs[[3]], trophs[[2]], trophs[[3]]),
               font.label=list(color="black", face = "plain", size=14))

b <- annotate_figure(a, top = text_grob("Terrestrial", 
               color = "black", face = "bold", size = 14))

ggsave("../figures/terrestrial_prevalence.png", width = 17, height = 5)


# riverine 
str_plots <- lapply(s, prev_plot)

for (i in 1:length(trophs)) {
  sp <- str_plots[[i]] + labs(title = trophs[i])
  str_plots[[i]] <- sp
}

c <- ggarrange(str_plots[[1]], str_plots[[2]], str_plots[[3]], nrow = 1, 
               vjust = 0.1,
               #labels = c(trophs[[3]], trophs[[2]], trophs[[3]]),
               font.label=list(color="black", face = "plain", size=14))

d <- annotate_figure(c, top = text_grob("Riverine", 
               color = "black", face = "bold", size = 14))

ggsave("../figures/riverine_prevalence.png", width = 17, height = 5)


# marine 
mar_plots <- lapply(m, prev_plot)

for (i in 1:length(trophs)) {
  mp <- mar_plots[[i]] + labs(title = trophs[i])
  mar_plots[[i]] <- mp
}

e <- ggarrange(mar_plots[[1]], mar_plots[[2]], mar_plots[[3]], nrow = 1, 
               vjust = 0.1,
               #labels = c(trophs[[3]], trophs[[2]], trophs[[3]]),
               font.label=list(color="black", face = "plain", size=14))

f <- annotate_figure(e, top = text_grob("Marine", 
               color = "black", face = "bold", size = 14))

ggsave("../figures/marine_prevalence.png", width = 17, height = 5)


```

















