---
title: "accumulation_curves"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r}
# read in abundance table
# sample IDS are cols, ASVs are rows
abun <- readRDS("../intermediates/culled_asv_table.rds")
tax <- readRDS("../intermediates/culled_tax_table.rds")

its_meta <- readRDS("../intermediates/culled_metadata.rds")


```


### Accumulation Curves

```{r}

library(iNEXT)

# example: ASV accumulation curves for Primary Producers and Animals in Terrestrial habitat

# find which sample IDs are for PPs in Terrestrial - 330 samples
pp_terr_id <- its_meta[its_meta$trophic=="PrimaryProducer" & its_meta$habitat=="Terrestrial",][["sequencing_id"]]

# subset ASV table by these IDs
pp_terr_asvs <- abun[,names(abun) %in% pp_terr_id]
# remove empty ASVs - 27167 ASVs
pp_terr_asvs <- pp_terr_asvs[rowSums(pp_terr_asvs)>0,]

pp_terr_sums <- rowSums(pp_terr_asvs)

saveRDS(pp_terr_sums, "../intermediates/plant_terrestrial_asv_sums.rds")


# repeat for Animals in Terrestrial - 380 samples
anim_terr_id <- its_meta[its_meta$host=="Animal" & its_meta$habitat=="Terrestrial",][["sequencing_id"]]

anim_terr_asvs <- abun[,names(abun) %in% anim_terr_id]
# 16038 ASVs
anim_terr_asvs <- anim_terr_asvs[rowSums(anim_terr_asvs)>0,] 

anim_terr_sums <- rowSums(anim_terr_asvs)

saveRDS(anim_terr_sums, "../intermediates/animal_terrestrial_asv_sums.rds")


## curves

# make list with ASV sums
terrestrial <- list(pp_terr_sums, anim_terr_sums)
names(terrestrial) <- c("Primary Producer", "Animal")

terr_accum <- iNEXT(terrestrial, nboot = 200)


```


```{r}

# tiny test

# make ASV sums smaller
tiny_plant <- sample(pp_terr_sums, 100)
tiny_animal <- sample(anim_terr_sums, 100)

# do accum curves for these
tiny_list <- list(tiny_plant, tiny_animal)
names(tiny_list) <- c("Primary Producer", "Animal")


tim <- proc.time()
tiny_accum <- iNEXT(tiny_list, nboot = 10)

tim - proc.time() # 132 seconds - this is actually faster than the cluster version :(

```


Parallelization??

```{r}

library(parallel)

cl <- makeCluster(5)

ptm <- proc.time()

clusterExport(cl, "tiny_list")

clusterEvalQ(cl, {
  library(iNEXT)
  a <- iNEXT(tiny_list, nboot = 10)
})


stopCluster(cl)

ptm - proc.time() #157 seconds elapsed

```



```{r}

data("spider")

out <- iNEXT(spider, nboot = 200)

ggiNEXT(out, type = 1)

ggiNEXT(out, type = 2)



```







