---
title: "degree_and_bc_tukeys"
output: html_document
date: "2024-09-17"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, echo=F}
# read in data
deg_dat <- readRDS("../../intermediates/new_knockouts/degree_tukey_results.rds")

bc_dat <- readRDS("../../intermediates/new_knockouts/bc_tukey_results.rds")
options(scipen=999)
```

```{r}
# these go together
d1 <- as.data.frame(deg_dat[[1]])
d2 <- do.call("rbind", deg_dat[[2]])
d3 <- do.call("rbind", deg_dat[[4]])

d4 <- do.call("rbind", deg_dat[[3]])
d5 <- do.call("rbind", deg_dat[[5]])


deg1 <- rbind(d2, d3)
write.csv(deg1, "../../outputs/degree_tukey_1.csv")

deg2 <- rbind(d1, d4, d5)
write.csv(deg2, "../../outputs/degree_tukey_2.csv")
```

```{r}
# these go together
b1 <- as.data.frame(bc_dat[[1]])
b2 <- do.call("rbind", bc_dat[[2]])
b3 <- do.call("rbind", bc_dat[[4]])

b4 <- do.call("rbind", bc_dat[[3]])
b5 <- do.call("rbind", bc_dat[[5]])


bc1 <- rbind(b2, b3)
write.csv(bc1, "../../outputs/bc_tukey_1.csv")

bc2 <- rbind(b1, b4, b5)
write.csv(bc2, "../../outputs/bc_tukey_2.csv")
```


<!-- # Degree -->

<!-- ### Whole watershed -->

<!-- ```{r, echo=F} -->
<!-- deg_dat[[1]] -->
<!-- ``` -->

<!-- ### Habitat -->

<!-- Between habitats within kingdom -->
<!-- ```{r, echo=F} -->
<!-- deg_dat[[2]] -->
<!-- ``` -->

<!-- Between kingdoms within habitat -->
<!-- ```{r, echo=F} -->
<!-- deg_dat[[3]] -->
<!-- ``` -->


<!-- ### Gradient -->

<!-- Between sites within kingdom -->
<!-- ```{r, echo=F} -->
<!-- deg_dat[[4]] -->
<!-- ``` -->

<!-- Between kingdoms within sites -->
<!-- ```{r, echo=F} -->
<!-- deg_dat[[5]] -->
<!-- ``` -->


<!-- # Betweenness Centrality -->

<!-- ### Whole watershed -->

<!-- ```{r, echo=F} -->
<!-- bc_dat[[1]] -->
<!-- ``` -->

<!-- ### Habitat -->

<!-- Between habitats within kingdom -->
<!-- ```{r, echo=F} -->
<!-- bc_dat[[2]] -->
<!-- ``` -->

<!-- Between kingdoms within habitat -->
<!-- ```{r, echo=F} -->
<!-- bc_dat[[3]] -->
<!-- ``` -->


<!-- ### Gradient -->

<!-- Between sites within kingdom -->
<!-- ```{r, echo=F} -->
<!-- bc_dat[[4]] -->
<!-- ``` -->

<!-- Between kingdoms within sites -->
<!-- ```{r, echo=F} -->
<!-- bc_dat[[5]] -->
<!-- ``` -->


