---
title: "xx_dummy_network"
output: html_document
date: "2024-09-11"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

15 nodes in this sample network, one component with 8 nodes, one component with 5 nodes, and 2 disconnected nodes

```{r, echo=F, message = F, warning = F, error = F}
library(igraph)
library(data.table)
library(brainGraph)
```

```{r, echo=F}

myrobustness_bc <- function(g, kingdom) {
  
  n = vertex=vcount(g)
  orig_max <- max(components(g)$csize)
  max.comp.removed <- rep.int(orig_max, n)
  removed.pct <- seq.int(0, 1, length.out=n+1L)
  nodename <- rep("x", n+1L)
  
  for (j in seq_len(n - 1L)) {
    val <- centr_betw(g)$res 
    ord <- V(g)$name[order(val, decreasing=TRUE)]
    
    nodename[j + 1L] <- ord[1]
    
    g <- delete_vertices(g, ord[1])
    max.comp.removed[j + 1L] <- max(components(g)$csize)
    
    #cat(".")
    
  }
  
  max.comp.removed <- c(max.comp.removed, 0)
  comp.pct <- max.comp.removed / orig_max
  out <- data.table(node.removed = nodename, comp.size=max.comp.removed,
                    comp.pct=comp.pct, removed.pct=removed.pct)
  
  out$type <- rep("btwncent", nrow(out))
  out$kingdom <- rep(kingdom, nrow(out))
  return(out)
  
  
}
```

```{r, echo=F}
# adj_matrix <- matrix(c(
#   0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
#   1, 0, 1, 1, 0, 0, 0, 0, 0, 0,
#   0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
#   0, 1, 0, 0, 1, 0, 0, 0, 0, 0,
#   0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
#   0, 0, 0, 0, 0, 0, 1, 1, 0, 0,
#   0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
#   0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
#   0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
#   0, 0, 0, 0, 0, 0, 0, 0, 0, 0
# ), nrow = 10, byrow = TRUE)

# Define the corrected adjacency matrix
adj_matrix <- matrix(0, nrow = 15, ncol = 15)

# Component 1 (8 nodes) - Modular Structure
adj_matrix[1, 2] <- 1
adj_matrix[2, 1] <- 1
adj_matrix[2, 3] <- 1
adj_matrix[3, 2] <- 1
adj_matrix[3, 4] <- 1
adj_matrix[4, 3] <- 1
adj_matrix[4, 5] <- 1
adj_matrix[5, 4] <- 1
adj_matrix[5, 6] <- 1
adj_matrix[6, 5] <- 1
adj_matrix[6, 7] <- 1
adj_matrix[7, 6] <- 1
adj_matrix[7, 8] <- 1
adj_matrix[8, 7] <- 1
adj_matrix[8, 5] <- 1
adj_matrix[5, 8] <- 1
adj_matrix[2, 4] <- 1
adj_matrix[4, 2] <- 1
adj_matrix[6, 8] <- 1
adj_matrix[8, 6] <- 1

# Component 2 (5 nodes) - Modular Structure
adj_matrix[9, 10] <- 1
adj_matrix[10, 9] <- 1
adj_matrix[10, 11] <- 1
adj_matrix[11, 10] <- 1
adj_matrix[11, 12] <- 1
adj_matrix[12, 11] <- 1
adj_matrix[12, 13] <- 1
adj_matrix[13, 12] <- 1
adj_matrix[13, 9] <- 1
adj_matrix[9, 13] <- 1
adj_matrix[10, 12] <- 1
adj_matrix[12, 10] <- 1

# Create the graph from the adjacency matrix
g <- graph_from_adjacency_matrix(adj_matrix, mode = "undirected")
V(g)$name <- letters[1:15]

robby <- myrobustness_bc(g, kingdom = "test")

robby

plot(g)



val <- centr_betw(g)$res 
ord <- V(g)$name[order(val, decreasing=TRUE)]
g_rm1 <- delete_vertices(g, ord[1])
    

newlist <- list()
  
for (j in seq_len(14)) {
    val <- centr_betw(g)$res 
    ord <- V(g)$name[order(val, decreasing=TRUE)]
    
    g <- delete_vertices(g, ord[1])
    
    n = plot(g, main = paste("Removed node ", ord[1]))
    
    newlist[[j]] <- n
  }

```

