---
title: "01_hostenv_data_prep"
output: html_document
date: "2024-04-15"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Goal: prepare 20% prev filtered data from global networks for empo1 networks.

Should have 3 data frames per fungi, bact (host samples and env samples)
Figure out dummy row - should have sums of prevalence filtered otus but only for samples included in the network

```{r}
library(dplyr)
library(tibble)
```

```{r}

# import data
fung_abun <- readRDS("~/hynson_koastore/kaciekaj/waimea_current/intermediates/global/fully_filtered_p20_fungal_otu_table_matched_up.rds") # 2128 otus, 1384 samples
bact_abun <- readRDS("~/hynson_koastore/kaciekaj/waimea_current/intermediates/global/fully_filtered_p20_bact_otu_table_matched_up.rds") # 13468 otus, 1384 samples

# TEST - all samples are matched up
# f_test <- fung_abun
# names(f_test) <- fung_meta$sample_id[match(names(fung_abun), fung_meta$x_seq_id)]
# b_test <- bact_abun
# names(b_test) <- bact_meta$sample_id[match(names(bact_abun), bact_meta$x_seq_id)]


fung_meta <- readRDS("~/hynson_koastore/kaciekaj/waimea_current/intermediates/global/fully_filtered_p20_fungal_otu_metadata_matched_up.rds")
bact_meta <- readRDS("~/hynson_koastore/kaciekaj/waimea_current/intermediates/global/fully_filtered_p20_bact_otu_metadata_matched_up.rds")

# some data formatting
fung_meta$empo1[!(fung_meta$empo1 %in% c("PrimaryProducer", "Environmental"))] <- "Consumer"
bact_meta$empo1[!(bact_meta$empo1 %in% c("PrimaryProducer", "Environmental"))] <- "Consumer"

fung_dummy <- fung_abun[row.names(fung_abun)=="dummy",]
bact_dummy <- bact_abun[row.names(bact_abun)=="dummy",]

# names(fung_dummy) <- fung_meta$sample_id[match(names(fung_abun), fung_meta$x_seq_id)]
# names(bact_dummy) <- bact_meta$sample_id[match(names(bact_abun), bact_meta$x_seq_id)]


fung_abun <- fung_abun[row.names(fung_abun)!="dummy",]
bact_abun <- bact_abun[row.names(bact_abun)!="dummy",]


```

Host samples

```{r}

fung_host <- fung_meta[fung_meta$empo_1=="Host-associated",]
bact_host <- bact_meta[bact_meta$empo_1=="Host-associated",]

# fungi
fung_host_abun <- fung_abun[,names(fung_abun) %in% fung_host$x_seq_id]
fung_host_abun <- fung_host_abun[rowSums(fung_host_abun)>0,] # 2031 otus, 1014 samples
fung_host_dum <- fung_dummy[names(fung_dummy) %in% names(fung_host_abun)]
fung_host_abun <- rbind(fung_host_abun, fung_host_dum)
names(fung_host_abun) <- fung_host$sample_id[match(names(fung_host_abun), fung_host$x_seq_id)]

saveRDS(fung_host_abun, "../intermediates/hostnon/fung_prev20_hostassoc_abun.rds")

# bacteria
bact_host_abun <- bact_abun[,names(bact_abun) %in% bact_host$x_seq_id]
bact_host_abun <- bact_host_abun[rowSums(bact_host_abun)>0,] # 12706 otus, 1014 samples
bact_host_dum <- bact_dummy[names(bact_dummy) %in% names(bact_host_abun)]
bact_host_abun <- rbind(bact_host_abun, bact_host_dum)
names(bact_host_abun) <- bact_host$sample_id[match(names(bact_host_abun), bact_host$x_seq_id)]

saveRDS(bact_host_abun, "../intermediates/hostnon/bact_prev20_hostassoc_abun.rds")

```


Environmental samples

```{r}
fung_env_meta <- fung_meta[fung_meta$empo_1=="Free-living",]
bact_env_meta <- bact_meta[bact_meta$empo_1=="Free-living",]

# fungi
fung_env_abun <- fung_abun[,names(fung_abun) %in% fung_env_meta$x_seq_id]
fung_env_abun <- fung_env_abun[rowSums(fung_env_abun)>0,] # 2115 otus, 370 samples
fung_env_dum <- fung_dummy[names(fung_dummy) %in% names(fung_env_abun)]
fung_env_abun <- rbind(fung_env_abun, fung_env_dum)
names(fung_env_abun) <- fung_env_meta$sample_id[match(names(fung_env_abun), fung_env_meta$x_seq_id)]

saveRDS(fung_env_abun, "../intermediates/hostnon/fung_prev20_env_abun.rds")

# bacteria
bact_env_abun <- bact_abun[,names(bact_abun) %in% bact_env_meta$x_seq_id]
bact_env_abun <- bact_env_abun[rowSums(bact_env_abun)>0,] # 13004 otus, 370 samples
bact_env_dum <- bact_dummy[names(bact_dummy) %in% names(bact_env_abun)]
bact_env_abun <- rbind(bact_env_abun, bact_env_dum)
names(bact_env_abun) <- bact_env_meta$sample_id[match(names(bact_env_abun), bact_env_meta$x_seq_id)]

saveRDS(bact_env_abun, "../intermediates/hostnon/bact_prev20_env_abun.rds")

```

``` {r}

hostnon_samp_counts <- fung_meta %>% dplyr::group_by(empo_1, site_name) %>% dplyr::summarise(sum = n())

hostnon_min_df <- hostnon_samp_counts %>% dplyr::group_by(site_name) %>% dplyr::slice(which.min(sum))



empo1 <- unique(fung_meta$empo_1)

take_random <- function(empo, abun, meta, min_count_df) {
  sub_met <- meta[meta$empo_1==empo,]
  
  sub_abun <- abun[,names(abun) %in% sub_met$x_seq_id]
  sub_abun <- sub_abun[rowSums(sub_abun)>0,] 
  
  plots <- unique(sub_met$site_name)
  
  res <- list()
  
  for (a_plot in plots) {
    plot_met <- sub_met[sub_met$site_name==a_plot,]
    plot_abun <- sub_abun[,names(sub_abun) %in% plot_met$x_seq_id]
    plot_abun <- plot_abun[rowSums(plot_abun)>0,]
    
    min_empo_num <- min_count_df$sum[min_count_df$site_name==a_plot]
    
    plot_abun <- plot_abun[,order(colSums(plot_abun), decreasing = TRUE)]
    
    set.seed(123)
    random_samps_abun <- plot_abun[,sample(names(plot_abun), min_empo_num)]
    random_samps_abun <- random_samps_abun[rowSums(random_samps_abun)>0,]
    
    res[[a_plot]] <- random_samps_abun
    
  }
  
  return(res)
  
}


fung_empo1_list <- lapply(empo1,
                   take_random,
                   abun = fung_abun,
                   meta = fung_meta,
                   min_count_df = hostnon_min_df)
names(fung_empo1_list) <- empo1
```

```{r}

multi_merge_matrix <- function(matrix_list) {
  
  r <- merge(matrix_list[[1]], matrix_list[[2]], by="row.names", all=TRUE)
  # ASVs become a row, change back to rownames
  r <- column_to_rownames(r, "Row.names")

  for (i in 3:length(matrix_list)) {
  r <- merge(r, matrix_list[[i]], by="row.names", all=T)
  rownames(r) <- r[,1]
  r[,1] <- NULL
  }

  r[is.na(r)] <- 0

  return(r)

}
```


```{r}
### make merged otu tables
fung_nonhost_abun <- multi_merge_matrix(fung_empo1_list[["Free-living"]])
fung_host_abun <- multi_merge_matrix(fung_empo1_list[["Host-associated"]])


fung_down_meta <- fung_meta[fung_meta$x_seq_id %in% names(fung_hostnon_abun),]


all_fung_plot_abun <- list(fung_nonhost_abun, fung_host_abun)
names(all_fung_plot_abun) <- empo1


# add dummy row from prev20 culling, but only for samples existing in the empo1/plot tables
fung_samp_names <- lapply(all_fung_plot_abun, names)

fung_dummy_by_table <- lapply(fung_samp_names, 
                              function(x) as.data.frame(fung_dummy[,names(fung_dummy) %in% x]))


all_fung_with_dummy <- list()

for(i in 1:length(all_fung_plot_abun)) {
  attach <- rbind(all_fung_plot_abun[[i]],
                  fung_dummy_by_table[[i]])
  all_fung_with_dummy[[i]] <- attach
}

names(all_fung_with_dummy) <- empo1

```

Bacteria


```{r}
# this is different from fungi because we want to use the same randomly selected samples as picked for the fungi
# so this function just gets otu tables by plot, which will be subset by sample id later
get_bact_plot_abun <- function(empo, abun, meta) {
  sub_met <- meta[meta$empo_1==empo,]
  
  sub_abun <- abun[,names(abun) %in% sub_met$x_seq_id]
  sub_abun <- sub_abun[rowSums(sub_abun)>0,] 
  
  plots <- unique(sub_met$site_name)
  
  res <- list()
  
  for (a_plot in plots) {
    plot_met <- sub_met[sub_met$site_name==a_plot,]
    plot_abun <- sub_abun[,names(sub_abun) %in% plot_met$x_seq_id]
    plot_abun <- plot_abun[rowSums(plot_abun)>0,]
    
    res[[a_plot]] <- plot_abun
    
  }
  
  return(res)
  
}


bact_empo_list <- lapply(empo1,
                   get_bact_plot_abun,
                   abun = bact_abun,
                   meta = bact_meta)
names(bact_empo_list) <- empo1

```


```{r}
# convert sample names from X-starting ids to WMEA ids
x_to_id <- function(abun, meta) {
  my_abun <- abun
  names(my_abun) <- meta$sample_id[match(names(my_abun), meta$x_seq_id)]
  return(my_abun)
}

fung_with_ids <- lapply(all_fung_with_dummy,
            x_to_id,
            meta = fung_meta)

 
### make merged otu tables
bact_nonhost_abun <- multi_merge_matrix(bact_empo_list[["Free-living"]])
bact_host_abun <- multi_merge_matrix(bact_empo_list[["Host-associated"]])

bact_nonhost_abun <- x_to_id(bact_nonhost_abun, meta = bact_meta)
bact_host_abun <- x_to_id(bact_host_abun, meta = bact_meta)

new_bact_nonhost_abun <- bact_nonhost_abun
new_bact_host_abun <- bact_host_abun

new_bact_nonhost_abun <- new_bact_nonhost_abun[,names(new_bact_nonhost_abun) %in% names(fung_with_ids[["Free-living"]])]
new_bact_nonhost_abun <- new_bact_nonhost_abun[rowSums(new_bact_nonhost_abun)>0,]

new_bact_host_abun <- new_bact_host_abun[,names(new_bact_host_abun) %in% names(fung_with_ids[["Host-associated"]])]
new_bact_host_abun <- new_bact_host_abun[rowSums(new_bact_host_abun)>0,]


all_bact_plot_abun <- list(new_bact_nonhost_abun, new_bact_host_abun)

# add dummy row from prev20 culling, but only for samples existing in the empo1/plot tables
bact_samp_names <- lapply(all_bact_plot_abun, names)

names(bact_dummy) <- bact_meta$sample_id[match(names(bact_dummy), bact_meta$x_seq_id)]

bact_dummy_by_table <- lapply(bact_samp_names, 
                              function(x) as.data.frame(bact_dummy[,names(bact_dummy) %in% x]))

all_bact_with_dummy <- list()

for(i in 1:length(all_bact_plot_abun)) {
  attach <- rbind(all_bact_plot_abun[[i]],
                  bact_dummy_by_table[[i]])
  all_bact_with_dummy[[i]] <- attach
}

names(all_bact_with_dummy) <- empo1

```

```{r}
ff <- lapply(fung_with_ids, function(x) x[,sort(names(x))])
names(ff) <- empo1
saveRDS(ff, "../intermediates/hostnon/fung_hostnon_abun_for_networks.rds")

bb <- lapply(all_bact_with_dummy, function(x) x[,sort(names(x))])
names(bb) <- empo1
saveRDS(bb, "../intermediates/hostnon/bact_hostnon_abun_for_networks.rds")


# check
all(names(ff[[1]])==names(bb[[1]]))
all(names(ff[[2]])==names(bb[[2]]))
```







Downsampling

```{r}
# take the lowest number of samples across all plots

min(table(fung_meta$site_name))

empo1 <- unique(fung_meta$empo_1) # using host instead of empo1 level column bc empo1 level codes wood arthropod as environmental

sites <- unique(fung_meta$site_name) 

site_downsample <- function(site, abun, meta) {

    site_met <- meta[meta$site_name==site,]
    site_abun <- abun[,names(abun) %in% site_met$x_seq_id]
    site_abun <- site_abun[rowSums(site_abun)>0,]
    
    min_empo_num <- 48
    
    site_abun <- site_abun[,order(colSums(site_abun), decreasing = TRUE)]
    
    set.seed(123)
    random_samps_abun <- site_abun[,sample(names(site_abun), min_empo_num)]
    random_samps_abun <- random_samps_abun[rowSums(random_samps_abun)>0,]
    
  
}
  

fung_hostnon_list <- lapply(sites,
                   site_downsample,
                   abun = fung_abun,
                   meta = fung_meta)
names(fung_hostnon_list) <- sites


bact_hostnon_list <- lapply(sites,
                   site_downsample,
                   abun = bact_abun,
                   meta = bact_meta)
names(bact_hostnon_list) <- sites

```


```{r}

multi_merge_matrix <- function(matrix_list) {
  
  r <- merge(matrix_list[[1]], matrix_list[[2]], by="row.names", all=TRUE)
  # ASVs become a row, change back to rownames
  r <- column_to_rownames(r, "Row.names")

  for (i in 3:length(matrix_list)) {
  r <- merge(r, matrix_list[[i]], by="row.names", all=T)
  rownames(r) <- r[,1]
  r[,1] <- NULL
  }

  r[is.na(r)] <- 0

  return(r)

}
```







```{r}
### make merged otu tables
fung_hostnon_abun <- multi_merge_matrix(fung_hostnon_list)

bact_hostnon_abun <- multi_merge_matrix(bact_hostnon_list)

fung_down_meta <- fung_meta[fung_meta$x_seq_id %in% names(fung_hostnon_abun),]


all_fung_plot_abun <- list(fung_plant_abun,
                           fung_anim_abun,
                           fung_env_abun)
names(all_fung_plot_abun) <- c("Plant", "Animal", "Nonhost")

#saveRDS(all_fung_plot_abun, "../intermediates/fung_plant_abun_for_networks.rds")


# add dummy row from prev20 culling, but only for samples existing in the empo1/plot tables
fung_samp_names <- lapply(all_fung_plot_abun, names)

fung_dummy_by_table <- lapply(fung_samp_names, 
                              function(x) as.data.frame(fung_dummy[,names(fung_dummy) %in% x]))


all_fung_with_dummy <- list()

for(i in 1:length(all_fung_plot_abun)) {
  attach <- rbind(all_fung_plot_abun[[i]],
                  fung_dummy_by_table[[i]])
  all_fung_with_dummy[[i]] <- attach
}

names(all_fung_with_dummy) <- c("Plant", "Animal", "Nonhost")

```







