---
title: "03_hostenv_diff_from_random"
output: html_document
date: "2024-04-18"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
# otu tables
fung_data <- readRDS("../intermediates/hostnon/fung_hostnon_abun_for_networks.rds")
bact_data <- readRDS("../intermediates/hostnon/bact_hostnon_abun_for_networks.rds")


remove_dummy_row <- function(df) {
  new_df <- df[row.names(df)!="dummy",]
  return(new_df)
}


fung_data <- lapply(fung_data, remove_dummy_row)
bact_data <- lapply(bact_data, remove_dummy_row)


# import igraph objects
# fung_igraphs <- readRDS("../intermediates/hostnon/fung_hostnon_igraphs.rds")
# bact_igraphs <- readRDS("../intermediates/hostnon/bact_hostnon_igraphs.rds")
# cross_igraphs <- readRDS("../intermediates/hostnon/cross_hostnon_igraphs.rds")

fung_igraphs <- readRDS("../intermediates/hostnon/downsampled_fung_hostnon_network.rds")
bact_igraphs <- readRDS("../intermediates/hostnon/downsampled_bact_hostnon_network.rds")
cross_igraps <- readRDS("../intermediates/hostnon/downsampled_cross_hostnon_network.rds")

# metadata
fung_meta <- readRDS("../intermediates/global/fully_filtered_p20_fungal_otu_metadata_matched_up.rds")
bact_meta <- readRDS("../intermediates/global/fully_filtered_p20_bact_otu_metadata_matched_up.rds")

empo1 <- c("Free-living", "Host-associated")
```

## Diff from random

```{r}
fung_power_law <- lapply(fung_igraphs, function(x) power.law.fit(degree(x))$KS.p)
fung_power_law > 0.05

bact_power_law <- lapply(bact_igraphs, function(x) power.law.fit(degree(x))$KS.p)
bact_power_law > 0.05

cross_power_law <- lapply(cross_igraphs, function(x) power.law.fit(degree(x))$KS.p)
cross_power_law > 0.05


tab <- data.frame("Fungi" = unlist(fung_power_law),
                  "Bacteria" = unlist(bact_power_law),
                  "Cross-domain" = unlist(cross_power_law))
rownames(tab) <- empo1


write.csv(tab, "../outputs/hostnon_downsampled_scalefree_table.csv")


# small world
library(qgraph)

fung_sw = lapply(fung_igraphs, smallworldIndex)
bact_sw <- lapply(bact_igraphs, smallworldIndex)
cross_sw <- lapply(cross_igraphs, smallworldIndex)

sw_vals <- data.frame(Fungi = sapply(fung_sw, function(x) x$index),
                      Bacteria = sapply(bact_sw, function(x) x$index),
                      Cross = sapply(cross_sw, function(x) x$index))

rownames(sw_vals) <- empo1

write.csv(sw_vals, "../outputs/hostnon_downsampled_smallworld_table.csv")

```



