---
title: "04_hostenv_downsample"
output: html_document
date: "2024-04-20"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(dplyr)
library(igraph)
library(ggnetwork)
library(intergraph)
library(brainGraph)
library(patchwork)
library(network)
library(SpiecEasi)

library(plyr)
library(tibble)
library(pbmcapply)
library(reshape2)

options(bitmapType='cairo')
```

```{r}
# read in data
fung_net <- readRDS("../intermediates/hostnon/fung_hostnon_igraphs.rds")
bact_net <- readRDS("../intermediates/hostnon/bact_hostnon_igraphs.rds")
cross_net <- readRDS("../intermediates/hostnon/cross_hostnon_igraphs.rds")
```

```{r}

fung_meta <- readRDS("../intermediates/global/fully_filtered_p20_fungal_otu_metadata_matched_up.rds")
bact_meta <- readRDS("../intermediates/global/fully_filtered_p20_bact_otu_metadata_matched_up.rds")

empo1 <- c("Free-living", "Host-associated")
```

```{r}

fung_data <- readRDS("../intermediates/hostnon/fung_hostnon_abun_for_networks.rds")
bact_data <- readRDS("../intermediates/hostnon/bact_hostnon_abun_for_networks.rds")


remove_dummy_row <- function(df) {
  new_df <- df[row.names(df)!="dummy",]
  return(new_df)
}

fung_data <- lapply(fung_data, remove_dummy_row)
bact_data <- lapply(bact_data, remove_dummy_row)



take_top <- function (otu_table) {
  otus <- data.frame(OTU = rownames(otu_table),
                     sum = rowSums(otu_table))
  
  otus <- otus[order(otus$sum, decreasing=TRUE),]
  
  top_400 <- otus[1:400,]
  
  tab <- otu_table[rownames(otu_table) %in% top_400$OTU,]
  tab <- tab[,colSums(tab) > 0]
  
  return(tab)
}

fung_top400 <- lapply(fung_data, take_top)
 

fung_top400 <- lapply(fung_top400, function(x) as.data.frame(t(x)))

lapply(fung_top400, dim) # host-associated loses 1 of 370 samples

fung_rnames <- lapply(fung_top400, rownames)

all_fung_dat <- do.call("rbind.fill", fung_top400)
rownames(all_fung_dat) <- unlist(fung_rnames)

all_fung_dat[is.na(all_fung_dat)] <- 0

#saveRDS(all_fung_dat, "../intermediates/global/downsampled_fung_otu_table.rds")

```

```{r}

bact_top400 <- lapply(bact_data, take_top)

bact_top400 <- lapply(bact_top400, function(x) as.data.frame(t(x)))

dim(bact_top400[[1]]) # no samples lost

bact_rnames <- lapply(bact_top400, rownames)

all_bact_dat <- do.call("rbind.fill", bact_top400)
rownames(all_bact_dat) <- unlist(bact_rnames)

all_bact_dat[is.na(all_bact_dat)] <- 0

#saveRDS(all_bact_dat, "../intermediates/global/downsampled_bact_otu_table.rds")

```

```{r}

fung_remove <- lapply(fung_data, function(x) rownames(x)[!(rownames(x) %in% colnames(all_fung_dat))])


filt_fung_net <- mapply(function(x,y) delete_vertices(x, y), fung_net, fung_remove)
  



bact_remove <- lapply(bact_data, function(x) rownames(x)[!(rownames(x) %in% colnames(all_bact_dat))])

filt_bact_net <- mapply(function(x,y) delete_vertices(x, y), bact_net, bact_remove)


cross_remove <- mapply(c, fung_remove, bact_remove)

filt_cross_net <- mapply(function(x,y) delete_vertices(x, y), cross_net, cross_remove)


names(filt_fung_net) <- empo1
names(filt_bact_net) <- empo1
names(filt_cross_net) <- empo1

saveRDS(filt_fung_net, "../intermediates/hostnon/downsampled_fung_hostnon_network.rds")
saveRDS(filt_bact_net, "../intermediates/hostnon/downsampled_bact_hostnon_network.rds")
saveRDS(filt_cross_net, "../intermediates/hostnon/downsampled_cross_hostnon_network.rds")


# get downsampled abundance tables
get_tbl <- function(network, abun) {
  vert <- as.character(V(network)$name)
  
  df <- abun[rownames(abun) %in% vert,]
  
  return(df)
}


fung_down_abun = mapply(get_tbl, network = filt_fung_net, abun = fung_data, SIMPLIFY = FALSE)

bact_down_abun = mapply(get_tbl, network = filt_bact_net, abun = bact_data, SIMPLIFY = FALSE)

saveRDS(fung_down_abun, "../intermediates/hostnon/fung_hostnon_downsampled_abuns.rds")
saveRDS(bact_down_abun, "../intermediates/hostnon/bact_hostnon_downsampled_abuns.rds")


```




