---
title: "05_habitat_robustness"
output: html_document
date: "2023-06-06"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(brainGraph)
```

```{r}
# import igraph objects
fung_igraphs <- readRDS("../intermediates/habitat/fung_habitat_igraphs.rds")
bact_igraphs <- readRDS("../intermediates/habitat/bact_habitat_igraphs.rds")
cross_igraphs <- readRDS("../intermediates/habitat/cross_habitat_igraphs.rds")

# metadata
fung_meta <- readRDS("../intermediates/global/fully_filtered_p20_fungal_otu_metadata_matched_up.rds")
bact_meta <- readRDS("../intermediates/global/fully_filtered_p20_bact_otu_metadata_matched_up.rds")

habs <- unique(fung_meta$habitat)
```


```{r}
# robustness test

fung_rob <- lapply(fung_igraphs, function(x) robustness(x, type="vertex", "btwn.cent"))
for (i in 1:3) {
  df <- fung_rob[[i]]
  df$domain <- "Fungi"
  df$habitat <- habs[[i]]
  
  fung_rob[[i]] <- df
}
fung_bc_rob <- do.call("rbind", fung_rob)


bact_rob <- lapply(bact_igraphs, function(x) robustness(x, type="vertex", "btwn.cent"))
for (i in 1:3) {
  df <- bact_rob[[i]]
  df$domain <- "Bacteria"
  df$habitat <- habs[[i]]
  
  bact_rob[[i]] <- df
}
bact_bc_rob <- do.call("rbind", bact_rob)


cross_rob <- lapply(cross_igraphs, function(x) robustness(x, type="vertex", "btwn.cent"))
for (i in 1:3) {
  df <- cross_rob[[i]]
  df$domain <- "Interkingdom"
  df$habitat <- habs[[i]]
  
  cross_rob[[i]] <- df
}
cross_bc_rob <- do.call("rbind", cross_rob)



all_node_robustness_btwn <- do.call("rbind", list(fung_bc_rob, bact_bc_rob, cross_bc_rob))

saveRDS(all_node_robustness_btwn, "../intermediates/habitat/robustness_data_by_habitat.rds")


#### read in
all_node_robustness_btwn <- readRDS("../intermediates/habitat/robustness_data_by_habitat.rds")

all_node_robustness_btwn <- all_node_robustness_btwn %>% mutate(domain = str_replace(domain, "Cross", "Interkingdom"))

fung_bc_rob <- all_node_robustness_btwn[all_node_robustness_btwn$domain=="Fungi",]
bact_bc_rob <- all_node_robustness_btwn[all_node_robustness_btwn$domain=="Bacteria",]
cross_bc_rob <- all_node_robustness_btwn[all_node_robustness_btwn$domain=="Interkingdom",]

bc_its_plot <- ggplot(fung_bc_rob, aes(x=removed.pct, y=comp.pct, group=habitat, color=habitat)) +
  geom_line(linewidth=1.5) +
  labs(x="Percentage of nodes removed", y="Size of largest connected component",
       title="Fungi", color = "Habitat") +
  theme(legend.key = element_rect(fill="white")) +
  theme(panel.border = element_blank(), panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(), axis.line = element_line(colour = "black"),
        panel.background=element_blank(),
        plot.title=element_text(size=16),
        axis.title = element_text(size=16),
        title=element_text(size=12)) +
  #scale_color_manual(values=c("#D81B60", "#1E88E5", "#DEA805")) +
  scale_color_manual(values = c("#5d8ca8ff", "#d5695dff", "#D3Ba68ff")) +
  theme(legend.text = element_text(size=12)) +
   theme(legend.title = element_text(size=14)) +
   guides(color = guide_legend(override.aes = list(size=6))) +
  theme(axis.title.y = element_text(margin = margin(t = 0, r = 10, b = 0, l = 0))) +
  theme(axis.title.x = element_text(margin = margin(t = 10, r = 0, b = 0, l = 0))) +
  scale_x_continuous(limits = c(0,1), expand = c(0, 0)) +
  scale_y_continuous(limits = c(0,1), expand = c(0, 0)) 

bc_16s_plot <- ggplot(bact_bc_rob, aes(x=removed.pct, y=comp.pct, group=habitat, color=habitat)) +
  geom_line(linewidth=1.5) +
  labs(x="Percentage of nodes removed", y="Size of largest connected component",
       title="Bacteria", color = "Habitat") +
  theme(legend.key = element_rect(fill="white")) +
  theme(panel.border = element_blank(), panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(), axis.line = element_line(colour = "black"),
        panel.background=element_blank(),
        plot.title=element_text(size=16),
        axis.title = element_text(size=16),
        title=element_text(size=12)) +
  scale_color_manual(values = c("#5d8ca8ff", "#d5695dff", "#D3Ba68ff")) +
  theme(legend.text = element_text(size=12)) +
   theme(legend.title = element_text(size=14)) +
   guides(color = guide_legend(override.aes = list(size=6))) +
  #theme(plot.margin = margin(0,25,0,0)) +
  theme(axis.title.y = element_text(margin = margin(t = 0, r = 10, b = 0, l = 0))) +
  theme(axis.title.x = element_text(margin = margin(t = 10, r = 0, b = 0, l = 0))) +
  scale_x_continuous(limits = c(0,1), expand = c(0, 0)) +
  scale_y_continuous(limits = c(0,1), expand = c(0, 0)) 

bc_cross_plot <- ggplot(cross_bc_rob, aes(x=removed.pct, y=comp.pct, group=habitat, color=habitat)) +
  geom_line(linewidth=1.5) +
  labs(x="Percentage of nodes removed", y="Size of largest connected component",
       title="Cross-domain", color="Habitat") +
  theme(legend.key = element_rect(fill="white")) +
  theme(panel.border = element_blank(), panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(), axis.line = element_line(colour = "black"),
        panel.background=element_blank(),
        plot.title=element_text(size=16),
        axis.title = element_text(size=16),
        title=element_text(size=12)) +
  scale_color_manual(values = c("#5d8ca8ff", "#d5695dff", "#D3Ba68ff")) +
  theme(legend.text = element_text(size=12)) +
   theme(legend.title = element_text(size=14)) +
   guides(color = guide_legend(override.aes = list(size=6))) +
  theme(axis.title.y = element_text(margin = margin(t = 0, r = 10, b = 0, l = 0))) +
  theme(axis.title.x = element_text(margin = margin(t = 10, r = 0, b = 0, l = 0))) +
  scale_x_continuous(limits = c(0,1), expand = c(0, 0)) +
  scale_y_continuous(limits = c(0,1), expand = c(0, 0)) 


library(patchwork)

plots <- bc_its_plot + bc_16s_plot + bc_cross_plot & theme(legend.position = "bottom")
#plots <- plots & xlab(NULL) & ylab(NULL)
plots <- plots + plot_layout(guides = "collect") 



#ggarrange(bc_its_plot, bc_16s_plot, bc_cross_plot, common.legend = TRUE, legend="bottom", nrow = 1) + bgcolor("white")

ggsave("../figures/finals/habitat/habitat_btwn_robustness_for_affinity.pdf", width=17, height=6)


```


## Plot with lines by domain

```{r}
all_node_robustness_btwn
all_node_robustness_btwn$domain <- factor(all_node_robustness_btwn$domain, c("Fungi", "Bacteria", "Interkingdom"))

bc_by_domain <- list()
for (i in 1:3) {
  dat <- all_node_robustness_btwn[all_node_robustness_btwn$habitat==habs[i]]
  
  my_plot <- ggplot(dat, aes(x=removed.pct, y=comp.pct, group=domain, color=domain)) +
  geom_line(linewidth=1.5) +
  labs(x="Percentage of nodes removed", y="Size of largest connected component",
       title=habs[i], color="Domain") +
    theme(legend.key = element_rect(fill="white")) +
  theme(panel.border = element_blank(), panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(), axis.line = element_line(colour = "black"),
        panel.background=element_blank(),
        plot.title=element_text(size=16),
        axis.title = element_text(size=16),
        title=element_text(size=12)) +
  #scale_color_manual(values=c("#D81B60", "#1E88E5", "#DEA805")) +
  scale_color_manual(values = c("#5d8ca8ff", "#d5695dff", "#D3Ba68ff")) +
  theme(legend.text = element_text(size=12)) +
   theme(legend.title = element_text(size=14)) +
   guides(color = guide_legend(override.aes = list(size=6))) +
  #theme(plot.margin = margin(0,25,0,0)) +
  theme(axis.title.y = element_text(margin = margin(t = 0, r = 10, b = 0, l = 0))) +
  theme(axis.title.x = element_text(margin = margin(t = 10, r = 0, b = 0, l = 0))) +
  scale_x_continuous(limits = c(0,1), expand = c(0, 0)) +
  scale_y_continuous(limits = c(0,1), expand = c(0, 0)) 
  
  bc_by_domain[[i]] <- my_plot
  
}

names(bc_by_domain) <- habs
bc_by_domain <- bc_by_domain[c("Marine","Riverine", "Terrestrial")]

hab_plots <- wrap_plots(bc_by_domain) & theme(legend.position = "bottom")
#hab_plots <- hab_plots & xlab(NULL) & ylab(NULL)
hab_plots <- hab_plots + plot_layout(guides = "collect") 


ggsave("../figures/finals/habitat/btwn_robustness_by_domain_for_affinity.pdf", width=17, height=6)


```










