---
title: "06_habitat_keystone_knockout_robustness"
output: html_document
date: "2023-06-22"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message=FALSE}
library(dplyr)
library(igraph)
library(brainGraph)
library(ggplot2)
library(ggpubr)
library(MetBrewer)

options(bitmapType='cairo')
```

```{r}
# read in data
fung_habitat_networks <- readRDS("../intermediates/habitat/fung_habitat_igraphs.rds")
bact_habitat_networks <- readRDS("../intermediates/habitat/bact_habitat_igraphs.rds")
cross_habitat_networks <- readRDS("../intermediates/habitat/cross_habitat_igraphs.rds")

fung_meta <- readRDS("../intermediates/global/fully_filtered_p20_fungal_otu_metadata_matched_up.rds")
bact_meta <- readRDS("../intermediates/global/fully_filtered_p20_bact_otu_metadata_matched_up.rds")

# hub data
fung_netcarto <- readRDS("../intermediates/habitat/fung_habitat_netcarto_results.rds")
bact_netcarto <- readRDS("../intermediates/habitat/bact_habitat_netcarto_results.rds")
cross_netcarto <- readRDS("../intermediates/habitat/cross_habitat_netcarto_results.rds")


habs <- unique(fung_meta$habitat)
```

# Robustness test

## ITS

```{r}

fung_keystone_data <- lapply(fung_netcarto, function(x) as.data.frame(x))

sub_to_hub <- function(df) {
  subd <- df[grep("Hub", df$role),]
  return(subd)
}


fung_keystone_data <- lapply(fung_keystone_data, sub_to_hub)

# make networks with no keystones
fung_net_nokey <- list()

for (i in 1:length(fung_keystone_data)) {
  net_no_key <- delete_vertices(fung_habitat_networks[[i]], fung_keystone_data[[i]]$name)
  fung_net_nokey[[i]] <- net_no_key
}


# get robustness tables for the full networks
fung_bc_rob_full <- list()

for (i in 1:length(fung_keystone_data)) {
  bc_robust <- robustness(fung_habitat_networks[[i]], type = "vertex", "btwn.cent")
  bc_robust$Type <- "Full"
  
  fung_bc_rob_full[[i]] <- bc_robust
}

# get robustness tables for no keystone networks
fung_bc_rob_nokey <- list()

for (i in 1:length(fung_keystone_data)) {
  bc_robust <- robustness(fung_net_nokey[[i]], type = "vertex", "btwn.cent")
  bc_robust$Type <- "Keystones Removed"
  
  fung_bc_rob_nokey[[i]] <- bc_robust
}


# join data by plot
fung_robustness_data <- list()

for (i in 1:length(fung_keystone_data)) {
  fung_robustness_data[[i]] <- rbind(fung_bc_rob_full[[i]], fung_bc_rob_nokey[[i]])
}


# plotting
fung_key_rob_plots <- list()

for (i in 1:length(fung_keystone_data)) {
  fung_key_rob_plots[[i]] <- ggplot(fung_robustness_data[[i]], aes(x=removed.pct, y=comp.pct, group=Type, color=Type)) +
    labs(x="Percentage of nodes removed", y="Size of largest connected component",
       title=paste0(habs[[i]], ", ", nrow(fung_keystone_data[[i]]), " Keystone OTUs")) +
    geom_line(size=1.5) +
  theme(legend.key = element_rect(fill="white")) +
  theme(panel.border = element_blank(), panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(), axis.line = element_line(colour = "black"),
        panel.background=element_blank(),
        axis.title = element_text(size=16),
        title=element_text(size=16)) +
  #scale_color_manual(values=c("#D81B60", "#1E88E5", "#DEA805")) +
  scale_color_manual(values=met.brewer("Archambault")[3:4]) +
  theme(legend.text = element_text(size=12)) +
   theme(legend.title = element_text(size=14)) +
   guides(color = guide_legend(override.aes = list(size=12))) +
  #theme(plot.margin = margin(0,25,0,0)) +
  theme(axis.title.y = element_text(margin = margin(t = 0, r = 10, b = 0, l = 0))) +
  theme(axis.title.x = element_text(margin = margin(t = 10, r = 0, b = 0, l = 0))) +
  scale_x_continuous(limits = c(0,1), expand = c(0, 0)) +
  scale_y_continuous(limits = c(0,1), expand = c(0, 0)) 
}

#sort plots by plot order
names(fung_key_rob_plots) <- habs
fung_key_rob_plots <- fung_key_rob_plots[c("Marine", "Riverine", "Terrestrial")]


fung_key_rob_plots[[1]] <- fung_key_rob_plots[[1]] + theme(axis.title.x = element_blank())
fung_key_rob_plots[[2]] <- fung_key_rob_plots[[2]] + theme(axis.title.y = element_blank())
fung_key_rob_plots[[3]] <- fung_key_rob_plots[[3]] + theme(axis.title.x = element_blank(),
                                                           axis.title.y = element_blank())


all_fung <- fung_key_rob_plots[[1]] + fung_key_rob_plots[[2]] + fung_key_rob_plots[[3]] & theme(legend.position = "bottom")
#plots <- plots & xlab(NULL) & ylab(NULL)
all_fung <- all_fung + plot_layout(guides = "collect") 

ggsave("../figures/finals/habitat/alternative_fung_keystone_removal_robustness_by_hab.pdf", width=18, height=6)


```

## 16S

```{r}

bact_keystone_data <- lapply(bact_netcarto, function(x) as.data.frame(x))

bact_keystone_data <- lapply(bact_keystone_data, sub_to_hub)

# make networks with no keystones
bact_net_nokey <- list()

for (i in 1:length(bact_keystone_data)) {
  net_no_key <- delete_vertices(bact_habitat_networks[[i]], bact_keystone_data[[i]]$name)
  bact_net_nokey[[i]] <- net_no_key
}


# get robustness tables for the full networks
bact_bc_rob_full <- list()

for (i in 1:length(bact_keystone_data)) {
  bc_robust <- robustness(bact_habitat_networks[[i]], type = "vertex", "btwn.cent")
  bc_robust$Type <- "Full"
  
  bact_bc_rob_full[[i]] <- bc_robust
}

# get robustness tables for no keystone networks
bact_bc_rob_nokey <- list()

for (i in 1:length(bact_keystone_data)) {
  bc_robust <- robustness(bact_net_nokey[[i]], type = "vertex", "btwn.cent")
  bc_robust$Type <- "Keystones Removed"
  
  bact_bc_rob_nokey[[i]] <- bc_robust
}


# join data by plot
bact_robustness_data <- list()

for (i in 1:length(bact_keystone_data)) {
  bact_robustness_data[[i]] <- rbind(bact_bc_rob_full[[i]], bact_bc_rob_nokey[[i]])
}


# plotting
bact_key_rob_plots <- list()

for (i in 1:length(bact_keystone_data)) {
  bact_key_rob_plots[[i]] <- ggplot(bact_robustness_data[[i]], aes(x=removed.pct, y=comp.pct, group=Type, color=Type)) +
    labs(x="Percentage of nodes removed", y="Size of largest connected component",
       title=paste0(habs[[i]], ", ", nrow(bact_keystone_data[[i]]), " Keystone OTUs")) +
    geom_line(size=1.5) +
  theme(legend.key = element_rect(fill="white")) +
  theme(panel.border = element_blank(), panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(), axis.line = element_line(colour = "black"),
        panel.background=element_blank(),
        axis.title = element_text(size=16),
        title=element_text(size=16)) +
    scale_color_manual(values=met.brewer("Archambault")[3:4]) +
  theme(legend.text = element_text(size=12)) +
   theme(legend.title = element_text(size=14)) +
   guides(color = guide_legend(override.aes = list(size=12))) +
  #theme(plot.margin = margin(0,25,0,0)) +
  theme(axis.title.y = element_text(margin = margin(t = 0, r = 10, b = 0, l = 0))) +
  theme(axis.title.x = element_text(margin = margin(t = 10, r = 0, b = 0, l = 0))) +
  scale_x_continuous(limits = c(0,1), expand = c(0, 0)) +
  scale_y_continuous(limits = c(0,1), expand = c(0, 0)) 
}

# save 1 for presentation purposes
# ggsave("../figures/habitat/one_bact_keystone_removal_rob_plot.png", bact_key_rob_plots[[1]], width=10, height=6)


#sort plots by plot order
names(bact_key_rob_plots) <- habs
bact_key_rob_plots <- bact_key_rob_plots[c("Marine", "Riverine", "Terrestrial")]

bact_key_rob_plots[[1]] <- bact_key_rob_plots[[1]] + theme(axis.title.x = element_blank())
bact_key_rob_plots[[2]] <- bact_key_rob_plots[[2]] + theme(axis.title.y = element_blank())
bact_key_rob_plots[[3]] <- bact_key_rob_plots[[3]] + theme(axis.title.x = element_blank(),
                                                           axis.title.y = element_blank())


all_bact <- bact_key_rob_plots[[1]] + bact_key_rob_plots[[2]] + bact_key_rob_plots[[3]] & theme(legend.position = "bottom")
#plots <- plots & xlab(NULL) & ylab(NULL)
all_bact <- all_bact + plot_layout(guides = "collect") 

ggsave("../figures/finals/habitat/alternative_bact_keystone_removal_robustness_by_hab.pdf", width=18, height=6)


```

## Cross-domain

```{r}

cross_keystone_data <- lapply(cross_netcarto, function(x) as.data.frame(x))

cross_keystone_data <- lapply(cross_keystone_data, sub_to_hub)

# make networks with no keystones
cross_net_nokey <- list()

for (i in 1:length(cross_keystone_data)) {
  net_no_key <- delete_vertices(cross_habitat_networks[[i]], cross_keystone_data[[i]]$name)
  cross_net_nokey[[i]] <- net_no_key
}


# get robustness tables for the full networks
cross_bc_rob_full <- list()

for (i in 1:length(cross_keystone_data)) {
  bc_robust <- robustness(cross_habitat_networks[[i]], type = "vertex", "btwn.cent")
  bc_robust$Type <- "Full"
  
  cross_bc_rob_full[[i]] <- bc_robust
}

# get robustness tables for no keystone networks
cross_bc_rob_nokey <- list()

for (i in 1:length(cross_keystone_data)) {
  bc_robust <- robustness(cross_net_nokey[[i]], type = "vertex", "btwn.cent")
  bc_robust$Type <- "Keystones Removed"
  
  cross_bc_rob_nokey[[i]] <- bc_robust
}


# join data by plot
cross_robustness_data <- list()

for (i in 1:length(cross_keystone_data)) {
  cross_robustness_data[[i]] <- rbind(cross_bc_rob_full[[i]], cross_bc_rob_nokey[[i]])
}


# plotting
cross_key_rob_plots <- list()

for (i in 1:length(cross_keystone_data)) {
  cross_key_rob_plots[[i]] <- ggplot(cross_robustness_data[[i]], aes(x=removed.pct, y=comp.pct, group=Type, color=Type)) +
    labs(x="Percentage of nodes removed", y="Size of largest connected component",
       title=paste0(habs[[i]], ", ", nrow(cross_keystone_data[[i]]), " Keystone OTUs")) +
    geom_line(size=1.5) +
  theme(legend.key = element_rect(fill="white")) +
  theme(panel.border = element_blank(), panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(), axis.line = element_line(colour = "black"),
        panel.background=element_blank(),
        axis.title = element_text(size=16),
        title=element_text(size=18)) +
    scale_color_manual(values=met.brewer("Archambault")[3:4]) +
  theme(legend.text = element_text(size=16)) +
   theme(legend.title = element_text(size=18)) +
   guides(color = guide_legend(override.aes = list(size=12))) +
  #theme(plot.margin = margin(0,25,0,0)) +
  theme(axis.title.y = element_text(margin = margin(t = 0, r = 10, b = 0, l = 0))) +
  theme(axis.title.x = element_text(margin = margin(t = 10, r = 0, b = 0, l = 0))) +
  scale_x_continuous(limits = c(0,1), expand = c(0, 0)) +
  scale_y_continuous(limits = c(0,1), expand = c(0, 0)) 
}

#sort plots by plot order
names(cross_key_rob_plots) <- habs
cross_key_rob_plots <- cross_key_rob_plots[c("Marine", "Riverine", "Terrestrial")]

cross_key_rob_plots[[1]] <- cross_key_rob_plots[[1]] + theme(axis.title.x = element_blank())
cross_key_rob_plots[[2]] <- cross_key_rob_plots[[2]] + theme(axis.title.y = element_blank())
cross_key_rob_plots[[3]] <- cross_key_rob_plots[[3]] + theme(axis.title.x = element_blank(),
                                                           axis.title.y = element_blank())


all_cross <- cross_key_rob_plots[[1]] + cross_key_rob_plots[[2]] + cross_key_rob_plots[[3]] & theme(legend.position = "bottom")
#plots <- plots & xlab(NULL) & ylab(NULL)
all_cross <- all_cross + plot_layout(guides = "collect") 

ggsave("../figures/finals/habitat/alternative_cross_keystone_removal_robustness_by_hab.pdf", width=18, height=6)


```




