---
title: "02_robustness_vs_topology"
output: html_document
date: "2024-09-06"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(igraph)
library(ggplot2)

habitat_palette <- c("#3F5671", "#83A1C3", "#B9D6B6")
```


Habitat networks only
```{r}
# stream, terrestrial, marine
# inputs are lists of lists of 3 dfs
fung_hab_robust <- readRDS("../intermediates/new_knockouts/fung_habitat_knockouts.rds")
bact_hab_robust <- readRDS("../intermediates/new_knockouts/bact_habitat_knockouts.rds")
cross_hab_robust <- readRDS("../intermediates/new_knockouts/cross_habitat_knockouts.rds")

# habitat igraphs
fung_igraphs <- readRDS("../intermediates/habitat/fung_habitat_igraphs.rds")
bact_igraphs <- readRDS("../intermediates/habitat/bact_habitat_igraphs.rds")
cross_igraphs <- readRDS("../intermediates/habitat/cross_habitat_igraphs.rds")


```

```{r} 
tables_to_work_on <- list(fung_hab_robust[[1]][[1]], # stream
                          fung_hab_robust[[1]][[2]], # terrestrial
                          fung_hab_robust[[1]][[3]], # marine
                          bact_hab_robust[[1]][[1]], # stream
                          bact_hab_robust[[1]][[2]], # terrestrial
                          bact_hab_robust[[1]][[3]], # marine
                          cross_hab_robust[[1]][[1]], # stream
                          cross_hab_robust[[1]][[2]], # terrestrial
                          cross_hab_robust[[1]][[3]]  # marine
                          )


all_auc <- lapply(tables_to_work_on,
                  function(x)
                    integrate(approxfun(x$removed.pct, x$comp.pct), 0, 1, subdivisions = 1000)$value
                  )

regress_df <- data.frame(kingdom = c(rep("Fungi", 3), rep("Bacteria", 3), rep("Interkingdom", 3)),
                         habitat = rep(c("Stream", "Terrestrial", "Marine"), 3),
                         robustness = unlist(all_auc))


# modularity
fung_netcarto <- readRDS("../intermediates/habitat/fung_habitat_netcarto_results.rds")
fung_modularity <- sapply(fung_netcarto, function(x) x[[2]])

bact_netcarto <- readRDS("../intermediates/habitat/bact_habitat_netcarto_results.rds")
bact_modularity <- sapply(bact_netcarto, function(x) x[[2]])

cross_netcarto <- readRDS("../intermediates/habitat/cross_habitat_netcarto_results.rds")
cross_modularity <- sapply(cross_netcarto, function(x) x[[2]])

regress_df$modularity <- c(fung_modularity, bact_modularity, cross_modularity)


net_list <- list(fung_igraphs[[1]], fung_igraphs[[2]], fung_igraphs[[3]],
            bact_igraphs[[1]], bact_igraphs[[2]], bact_igraphs[[3]],
            cross_igraphs[[1]], cross_igraphs[[2]], cross_igraphs[[3]])
# richness
regress_df$richness <- sapply(net_list,gorder)


#complexity (as linkage density)
# fung_cmp <- sapply(fung_igraphs, graph.density)
# bact_cmp <- sapply(bact_igraphs, graph.density)
# cross_cmp <- sapply(cross_igraphs, graph.density)
# 
# regress_df$complexity <- c(fung_cmp, bact_cmp, cross_cmp)


# connectance
connectance <- function(g) {
  ecount(g) / vcount(g)^2 
}


fung_conn <- sapply(fung_igraphs, connectance)
bact_conn <- sapply(bact_igraphs, connectance)
cross_conn <- sapply(cross_igraphs, connectance)

regress_df$connectance <- c(fung_conn, bact_conn, cross_conn)


# ratio of edges to nodes
regress_df$num_nodes <- sapply(net_list, gorder)
regress_df$num_edges <- sapply(net_list, gsize)

regress_df$ratio <- regress_df$num_edges / regress_df$num_nodes


# percent negative edges
hab_neg_edges <- readRDS("../intermediates/habitat/hab_neg_pct.rds") # in same order as regress_df
regress_df$pct_neg <- hab_neg_edges$neg_pct



# remove marine fungi
# regress_df_nomarfung <- regress_df[c(1,2,4:9),]
```

```{r}
ratio_lm <- summary(lm(robustness ~ ratio, data = regress_df))

ratio_pl <- ggplot(data = regress_df, aes(x = ratio, y = robustness, color = habitat, shape = kingdom)) +
      stat_smooth(method = "lm", 
                  aes(group = 1),
              formula = y ~ x, 
              geom = "smooth",
              se = F,
              color = "darkgrey",
              alpha = 0.5) +
    geom_point(size = 5, alpha = 0.8) +
  scale_color_manual(values = habitat_palette) +
  annotate("text", x = 18, y = 0.03, label = paste("Adj_R2 =", round(ratio_lm$adj.r.squared, 3))) +
  annotate("text", x = 18, y = 0.01, label = paste("P =", round(ratio_lm$coefficients[2,4], 3))) +
  theme_classic() +
  theme(axis.text = element_text(color = "black", size = 10)) +
  guides(color = "none", shape = "none") +
  labs(x = "Ratio of edges to nodes", y = "Robustness") +
  scale_y_continuous(breaks = seq(0, 0.3, 0.1),
                              limits = c(c(0, 0.3)))


pct_neg_lm <- summary(lm(robustness ~ pct_neg, data = regress_df))

pct_neg_pl <- ggplot(data = regress_df, aes(x = pct_neg, y = robustness, color = habitat, shape = kingdom)) +
      stat_smooth(method = "lm", 
                  aes(group = 1),
              formula = y ~ x, 
              geom = "smooth",
              se = F,
              color = "darkgrey",
              alpha = 0.5) +
    geom_point(size = 5, alpha = 0.8) +
  scale_color_manual(values = habitat_palette) +
  annotate("text", x = 0.28, y = 0.03, label = paste("Adj_R2 =", round(pct_neg_lm$adj.r.squared, 3))) +
  annotate("text", x = 0.28, y = 0.01, label = paste("P =", round(pct_neg_lm$coefficients[2,4], 3))) +
  theme_classic() +
  theme(axis.text = element_text(color = "black", size = 10)) +
  guides(color = "none", shape = "none") +
  labs(x = "Proportion of Negative Edges", y = "Robustness") +
  scale_y_continuous(breaks = seq(0, 0.3, 0.1),
                              limits = c(c(0, 0.3)))



# ratio_lm_nomf <- summary(lm(robustness ~ ratio, data = regress_df_nomarfung))
# 
# ratio_pl_nomf <- ggplot(data = regress_df_nomarfung, aes(x = ratio, y = robustness, color = habitat, shape = kingdom)) +
#   geom_point(size = 3) +
#       stat_smooth(method = "lm", 
#                   aes(group = 1),
#               formula = y ~ x, 
#               geom = "smooth",
#               se = F,
#               color = "black") +
#   annotate("text", x = 18, y = 0.11, label = paste("Adj_R2 =", round(ratio_lm_nomf$adj.r.squared, 3))) +
#   annotate("text", x = 18, y = 0.095, label = paste("P =", round(ratio_lm_nomf$coefficients[2,4], 3))) +
#   theme_classic() +
#   theme(axis.text = element_text(color = "black", size = 10)) +
#   guides(color = "none", shape = "none") +
#   labs(x = "Ratio of edges to nodes", y = "Robustness", title = "No marine fungi")
# 
# 
# xx <- ratio_pl + ratio_pl_nomf
```



Plot!

```{r}
mod_lm <- summary(lm(robustness ~ modularity, data = regress_df))

mod_pl <- ggplot(data = regress_df, aes(x = modularity, y = robustness, color = habitat, shape = kingdom)) +
      stat_smooth(method = "lm", 
                  aes(group = 1),
              formula = y ~ x, 
              geom = "smooth",
              se = F,
              color = "darkgrey",
              alpha = 0.5) +
    geom_point(size = 5, alpha = 0.8) +
  scale_color_manual(values = habitat_palette) +
  annotate("text", x = 0.52, y = 0.03, label = paste("Adj_R2 =", round(mod_lm$adj.r.squared, 3))) +
  annotate("text", x = 0.52, y = 0.01, label = paste("P =", round(mod_lm$coefficients[2,4], 3))) +
  theme_classic() +
  theme(axis.text = element_text(color = "black", size = 10)) +
  guides(color = "none", shape = "none") +
  labs(x = "Modularity", y = "Robustness") +
  scale_y_continuous(breaks = seq(0, 0.3, 0.1),
                              limits = c(c(0, 0.3)))



rich_lm <- summary(lm(robustness ~ richness, data = regress_df))

rich_pl <- ggplot(data = regress_df, aes(x = richness, y = robustness, color = habitat, shape = kingdom)) +
      stat_smooth(method = "lm", 
                  aes(group = 1),
              formula = y ~ x, 
              geom = "smooth",
              se = F,
              color = "darkgrey",
              alpha = 0.5) +
    geom_point(size = 5, alpha = 0.8) +
  scale_color_manual(values = habitat_palette) +
  annotate("text", x = 7500, y = 0.03, label = paste("Adj_R2 =", round(rich_lm$adj.r.squared, 3))) +
  annotate("text", x = 7500, y = 0.01, label = paste("P =", round(rich_lm$coefficients[2,4], 3))) +
  theme_classic() +
  theme(axis.text = element_text(color = "black", size = 10)) +
  guides(color = "none", shape = "none") +
  labs(x = "Richness", y = "Robustness") +
  scale_y_continuous(breaks = seq(0, 0.3, 0.1),
                              limits = c(c(0, 0.3)))



conn_lm <- summary(lm(robustness ~ connectance, data = regress_df))

conn_pl <- ggplot(data = regress_df, aes(x = connectance, y = robustness, color = habitat, shape = kingdom)) +
      stat_smooth(method = "lm", 
                  aes(group = 1),
              formula = y ~ x, 
              geom = "smooth",
              se = F,
              color = "darkgrey",
              alpha = 0.5) +
    geom_point(size = 5, alpha = 0.8) +
  scale_color_manual(values = habitat_palette) +
  annotate("text", x = 0.0023, y = 0.03, label = paste("Adj_R2 =", round(conn_lm$adj.r.squared, 3))) +
  annotate("text", x = 0.0023, y = 0.01, label = paste("P =", round(conn_lm$coefficients[2,4], 3))) +
  theme_classic() +
  theme(axis.text = element_text(color = "black", size = 10)) +
  labs(x = "Connectance", y = "Robustness") +
  scale_y_continuous(breaks = seq(0, 0.3, 0.1),
                              limits = c(c(0, 0.3)))
```


```{r}
library(patchwork)



plots <- mod_pl + rich_pl + conn_pl + ratio_pl + pct_neg_pl + plot_layout(ncol = 3)

ggsave("../figures/aug2024_revisions/robustness_vs_complexity_regressions.pdf", width = 12, height=6.5)
```

```{r}
# mod_lm_nomf <- summary(lm(robustness ~ modularity, data = regress_df_nomarfung))
# 
# mod_pl_nomf <- ggplot(data = regress_df_nomarfung, aes(x = modularity, y = robustness, color = habitat, shape = kingdom)) +
#   geom_point(size = 3) +
#       stat_smooth(method = "lm", 
#                   aes(group = 1),
#               formula = y ~ x, 
#               geom = "smooth",
#               se = F,
#               color = "black") +
#   annotate("text", x = 0.52, y = 0.11, label = paste("Adj_R2 =", round(mod_lm_nomf$adj.r.squared, 3))) +
#   annotate("text", x = 0.52, y = 0.095, label = paste("P =", round(mod_lm_nomf$coefficients[2,4], 3))) +
#   theme_classic() +
#   theme(axis.text = element_text(color = "black", size = 10)) +
#   guides(color = "none", shape = "none") +
#   labs(x = "Modularity", y = "Robustness")
# 
# 
# 
# rich_lm_nomf <- summary(lm(robustness ~ richness, data = regress_df_nomarfung))
# 
# rich_pl_nomf <- ggplot(data = regress_df_nomarfung, aes(x = richness, y = robustness, color = habitat, shape = kingdom)) +
#   geom_point(size = 3) +
#       stat_smooth(method = "lm", 
#                   aes(group = 1),
#               formula = y ~ x, 
#               geom = "smooth",
#               se = F,
#               color = "black") +
#   annotate("text", x = 7500, y = 0.11, label = paste("Adj_R2 =", round(rich_lm_nomf$adj.r.squared, 3))) +
#   annotate("text", x = 7500, y = 0.095, label = paste("P =", round(rich_lm_nomf$coefficients[2,4], 3))) +
#   theme_classic() +
#   theme(axis.text = element_text(color = "black", size = 10)) +
#   guides(color = "none", shape = "none") +
#   labs(x = "Richness", y = "Robustness")
# 
# 
# 
# conn_lm_nomf <- summary(lm(robustness ~ connectance, data = regress_df_nomarfung))
# 
# conn_pl_nomf <- ggplot(data = regress_df_nomarfung, aes(x = connectance, y = robustness, color = habitat, shape = kingdom)) +
#   geom_point(size = 3) +
#       stat_smooth(method = "lm", 
#                   aes(group = 1),
#               formula = y ~ x, 
#               geom = "smooth",
#               se = F,
#               color = "black") +
#   annotate("text", x = 0.0023, y = 0.11, label = paste("Adj_R2 =", round(conn_lm_nomf$adj.r.squared, 3))) +
#   annotate("text", x = 0.0023, y = 0.095, label = paste("P =", round(conn_lm_nomf$coefficients[2,4], 3))) +
#   theme_classic() +
#   theme(axis.text = element_text(color = "black", size = 10)) +
#   labs(x = "Connectance", y = "Robustness")
```


```{r}
# library(patchwork)
# 
# plots_nomf <- mod_pl_nomf + rich_pl_nomf + conn_pl_nomf
```

Efficiency and original AUC comparison

```{r}
fung_ws <- readRDS("../intermediates/new_knockouts/fung_watershed_efficiency_knockouts.rds")
bact_ws <- readRDS("../intermediates/new_knockouts/bact_watershed_efficiency_knockouts.rds")
cross_ws <- readRDS("../intermediates/new_knockouts/cross_watershed_efficiency_knockouts.rds")


ws_eff_auc <- lapply(list(fung_ws, bact_ws, cross_ws),
                  function(x)
                    integrate(approxfun(x$removed.pct, x$comp.pct), 0, 1, subdivisions = 1000)$value
                  )


old_ws <- readRDS("../intermediates/new_knockouts/whole_watershed_bc_knockouts.rds")

fung_old_ws <- old_ws[old_ws$kingdom=="Fungi" & old_ws$type=="btwncent",]
bact_old_ws <- old_ws[old_ws$kingdom=="Bacteria" & old_ws$type=="btwncent",]
cross_old_ws <- old_ws[old_ws$kingdom=="Interkingdom" & old_ws$type=="btwncent",]

ws_bc_auc <- lapply(list(fung_old_ws, bact_old_ws, cross_old_ws),
                  function(x)
                    integrate(approxfun(x$removed.pct, x$comp.pct), 0, 1, subdivisions = 1000)$value
                  )



marine_fung <- readRDS("../intermediates/new_knockouts/marine_fungi_efficiency_knockouts.rds")
marine_bact <- readRDS("../intermediates/new_knockouts/marine_bact_efficiency_knockouts.rds")
marine_cross <- readRDS("../intermediates/new_knockouts/marine_cross_efficiency_knockouts.rds")

mar_eff_auc <- lapply(list(marine_fung, marine_bact, marine_cross),
                  function(x)
                    integrate(approxfun(x$removed.pct, x$comp.pct), 0, 1, subdivisions = 1000)$value
                  )


mar_old_fung <- readRDS("../intermediates/new_knockouts/fung_habitat_knockouts.rds")[[1]][[3]]
mar_old_bact <- readRDS("../intermediates/new_knockouts/bact_habitat_knockouts.rds")[[1]][[3]]
mar_old_cross <- readRDS("../intermediates/new_knockouts/cross_habitat_knockouts.rds")[[1]][[3]]


mar_bc_auc <- lapply(list(mar_old_fung, mar_old_bact, mar_old_cross),
                  function(x)
                    integrate(approxfun(x$removed.pct, x$comp.pct), 0, 1, subdivisions = 1000)$value
                  )


compar = data.frame(watershed_original = unlist(ws_bc_auc),
                    watershed_efficiency = unlist(ws_eff_auc),
                    marine_original = unlist(mar_bc_auc),
                    marine_efficiency = unlist(mar_eff_auc))

row.names(compar) = c("Fungi", "Bacteria", "Interkingdom")

```

Test efficiency for marine vs largest component

```{r}

marine_fung <- readRDS("../intermediates/new_knockouts/marine_fungi_efficiency_knockouts.rds")
marine_bact <- readRDS("../intermediates/new_knockouts/marine_bact_efficiency_knockouts.rds")
marine_cross <- readRDS("../intermediates/new_knockouts/marine_cross_efficiency_knockouts.rds")

mar_eff_auc <- lapply(list(marine_fung, marine_bact, marine_cross),
                  function(x)
                    integrate(approxfun(x$removed.pct, x$comp.pct), 0, 1, subdivisions = 1000)$value
                  )


mar_old_fung <- readRDS("../intermediates/new_knockouts/fung_habitat_knockouts.rds")[[1]][[3]]
mar_old_bact <- readRDS("../intermediates/new_knockouts/bact_habitat_knockouts.rds")[[1]][[3]]
mar_old_cross <- readRDS("../intermediates/new_knockouts/cross_habitat_knockouts.rds")[[1]][[3]]


mar_bc_auc <- lapply(list(mar_old_fung, mar_old_bact, mar_old_cross),
                  function(x)
                    integrate(approxfun(x$removed.pct, x$comp.pct), 0, 1, subdivisions = 1000)$value
                  )


new <- data.frame(auc = c(unlist(mar_bc_auc), unlist(mar_eff_auc)))
new$type = c(rep("largest_component", 3),
             rep("efficiency", 3))
new$kingdom = rep(c("Fungi", "Bacteria", "Interkingdom"), 2)


mar <- regress_df[regress_df$habitat=="Marine",]

mar = mar[,c(2,4:9)]
mar = rbind(mar, mar)

new <- cbind(new, mar)

mmod <- ggplot(new, aes(x = modularity, y = auc, shape = type, color = type)) +
  geom_point(size = 4) +
  theme_classic() +
  theme(legend.position = "none")

rrich <- ggplot(new, aes(x = richness, y = auc, shape = type, color = type)) +
  geom_point(size = 4) +
  theme_classic() +
  theme(legend.position = "none")


cconn <- ggplot(new, aes(x = connectance, y = auc, shape = type, color = type)) +
  geom_point(size = 4) +
  theme_classic()

rrat <- ggplot(new, aes(x = ratio, y = auc, shape = type, color = type)) +
  geom_point(size = 4) +
  theme_classic() +
  labs(x = "Ratio of edges to nodes") +
  theme(legend.position = "none")
  

library(patchwork)

xx = mmod + rrich+ rrat +  cconn + plot_layout(nrow = 2)

```



```{r}
# complexity source code from igraph ish - https://github.com/igraph/rigraph/blob/c9c6a884c4d65248162d75d697c9c671d376d6ce/tests/testthat/test-graph.density.R#L3
#  g = filt_fung_net
# gd = edge_density(g)
# gd2 <- ecount(g) / vcount(g) / (vcount(g) - 1) * 2
```

