---
title: "02a_all_robustness_vs_topology"
output: html_document
date: "2024-09-06"
---


All networks, downsampled

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(igraph)
library(ggplot2)
library(rnetcarto)
library(data.table)
#habitat_palette <- c("#3F5671", "#83A1C3", "#B9D6B6")

source("~/hynson_koastore/kaciekaj/waimea_current/misc/new_knockout_functions.R")
```

Get AUC values for all downsampled networks

```{r}
# networks
filt_fung_net <- readRDS("../intermediates/global/weighted_filt_fung_net.rds")
filt_bact_net <- readRDS("../intermediates/global/weighted_filt_bact_net.rds")
filt_cross_net <- readRDS("../intermediates/global/weighted_filt_cross_net.rds")


g_bact = filt_bact_net

bact_sub <- induced.subgraph(g_bact, vids = sample(V(g_bact)$name, size = 839))

g_cross = filt_cross_net

cross_sub <- induced.subgraph(g_cross, vids = sample(V(g_cross)$name, size = 839))



test = lapply(list(filt_fung_net, bact_sub, cross_sub), 
              function(x) myrobustness_bc(x, kingdom = "placeholder"))



```


```{r}
##### watershed
# all_robustness <- readRDS("../intermediates/new_knockouts/whole_watershed_bc_knockouts.rds")
# 
fung_ws_rob <- test[[1]]
bact_ws_rob <- test[[2]]
cross_ws_rob <- test[[3]]


get_auc <- function(robustness_table) {
  xx = integrate(approxfun(robustness_table$removed.pct, robustness_table$comp.pct), 0, 1, subdivisions = 1000)$value
  
  return(xx)
}


ws_df <- data.frame(kingdom = c("Fungi", "Bacteria", "Interkingdom"),
                    category = rep("Watershed", 3),
                    robustness = sapply(list(fung_ws_rob, bact_ws_rob, cross_ws_rob), get_auc),
                    network = c("b", "a", "c"))

##### habitat
# stream, terrestrial, marine
# inputs are lists of lists of 3 dfs
hab_bc <- readRDS("../intermediates/habitat/hab_downsamp918_bc_knockouts.rds")

fung_hab_robust <- hab_bc[1:3]
bact_hab_robust <- hab_bc[4:6]
cross_hab_robust <- hab_bc[7:9]


hab_auc <- lapply(hab_bc,
                  get_auc)


hab_auc_df <- data.frame(kingdom = c(rep("Fungi", 3), rep("Bacteria", 3), rep("Interkingdom", 3)),
                         category = rep(c("Stream", "Terrestrial", "Marine"), 3),
                         robustness = unlist(hab_auc),
                         network = c("b","b","b","a","a","a","c","c","c"))


##### gradient

# robustness results from slurm
grad_bc <- readRDS("../intermediates/gradient/grad_downsamp721_bc_knockouts.rds")

# fung_grad_robust <- grad_bc[1:7]
# bact_grad_robust <- grad_bc[8:14]
# cross_grad_robust <- grad_bc[15:21]


all_grad_auc  <- lapply(grad_bc, get_auc)



## by site
gradient_sites <- c("Beach", "Estuary", "Entrance", "Confluence", "Waterfall", "DrumRoad", "Ridge")


grad_site_auc_df <- data.frame(kingdom = c(rep("Fungi", 7), rep("Bacteria", 7), rep("Interkingdom", 7)),
                         category = rep(gradient_sites, 3),
                         robustness = unlist(all_grad_auc),
                         network = c(rep("b", 7), rep("a",7), rep("c",7)))


### combine
all_auc_dat <- rbind(ws_df, hab_auc_df, grad_site_auc_df)
all_auc_dat <- all_auc_dat[,1:3]
```


```{r}
regress_df <- all_auc_dat


# networks
#filt_fung_net <- filt_fung_net
filt_bact_net <- bact_sub
filt_cross_net <- cross_sub

#saveRDS(list(filt_fung_net, bact_sub, cross_sub), "../intermediates/richtest_downsamp/watershed_nets840.rds")

fung_hab_igraphs <- readRDS("../intermediates/habitat/fung_downsamp918_igraphs.rds")
bact_hab_igraphs <- readRDS("../intermediates/habitat/bact_downsamp918_igraphs.rds")
cross_hab_igraphs <- readRDS("../intermediates/habitat/cross_downsamp918_igraphs.rds")

fung_grad_igraphs <- readRDS("../intermediates/gradient/terrestrial/fung_downsamp721_igraphs.rds")
bact_grad_igraphs <- readRDS("../intermediates/gradient/terrestrial/bact_downsamp721_igraphs.rds")
cross_grad_igraphs <- readRDS("../intermediates/gradient/terrestrial/cross_downsamp721_igraphs.rds")

```

modularity
```{r}
# watershed
# fung_netcarto <- readRDS("../intermediates/global/down_fung_netcarto.rds")
# bact_netcarto <- netcarto(get.adjacency(filt_bact_net, sparse=F))
# cross_netcarto <- netcarto(get.adjacency(filt_bact_net, sparse=F))
# 
# fung_ws_mod <- fung_netcarto[[2]]
# bact_ws_mod <- bact_netcarto[[2]]
# cross_ws_mod <- cross_netcarto[[2]]
# 
# saveRDS(c(fung_ws_mod, bact_ws_mod, cross_ws_mod), "../intermediates/global/ws_downsamp839_netcarto.rds")

ws_mod <- readRDS("../intermediates/global/ws_downsamp839_netcarto.rds")

# habitat
# fung_hab_netc <- lapply(fung_hab_igraphs, function(x)
#   netcarto(get.adjacency(x, sparse = FALSE)))

# fung_hab_mod <- sapply(fung_hab_netc, function(x) x[[2]])
# 
# bact_hab_netc <- lapply(bact_hab_igraphs, function(x)
#   netcarto(get.adjacency(x, sparse = FALSE)))
# 
# bact_hab_mod <- sapply(bact_hab_netc, function(x) x[[2]])
# 
# cross_hab_netc <- lapply(cross_hab_igraphs, function(x)
#   netcarto(get.adjacency(x, sparse = FALSE)))
# 
# cross_hab_mod <- sapply(cross_hab_netc, function(x) x[[2]])
# 
# saveRDS(c(fung_hab_netc, bact_hab_netc, cross_hab_netc), "../intermediates/habitat/hab_downsamp918_netcarto.rds")

hab_mod <- readRDS("../intermediates/habitat/hab_downsamp918_netcarto.rds")

# gradient
# fung_grad_netc <- lapply(fung_grad_igraphs, function(x)
#   netcarto(get.adjacency(x, sparse = FALSE)))
# 
# fung_grad_mod <- sapply(fung_grad_netc, function(x) x[[2]])
# 
# bact_grad_netc <- lapply(bact_grad_igraphs, function(x)
#   netcarto(get.adjacency(x, sparse = FALSE)))
# 
# bact_grad_mod <- sapply(bact_grad_netc, function(x) x[[2]])
# 
# cross_grad_netc <- lapply(cross_grad_igraphs, function(x)
#   netcarto(get.adjacency(x, sparse = FALSE)))
# 
# cross_grad_mod <- sapply(cross_grad_netc, function(x) x[[2]])
# 
# saveRDS(c(fung_grad_netc, bact_grad_netc, cross_grad_netc), "../intermediates/gradient/grad_downsamp721_netcarto.rds")

grad_mod <- readRDS("../intermediates/gradient/grad_downsamp721_netcarto.rds")


hm <- sapply(hab_mod, function(x) x[[2]])
gm <- sapply(grad_mod, function(x) x[[2]])

regress_df$modularity <- c(ws_mod, hm, gm)
```

richness

```{r}
richy = list(filt_fung_net, filt_bact_net, filt_cross_net)
big_net_list <- c(richy,
                  fung_hab_igraphs, bact_hab_igraphs, cross_hab_igraphs,
                  fung_grad_igraphs, bact_grad_igraphs, cross_grad_igraphs)

# richness
regress_df$richness <- sapply(big_net_list,gorder)
```

```{r}
# connectance
connectance <- function(g) {
  ecount(g) / vcount(g)^2 
}


regress_df$connectance <- sapply(big_net_list, connectance)

```

```{r}
# ratio of edges to nodes
regress_df$num_nodes <- sapply(big_net_list, gorder)
regress_df$num_edges <- sapply(big_net_list, gsize)

regress_df$ratio <- regress_df$num_edges / regress_df$num_nodes
```


```{r} 
ws_neg_edges <- readRDS("../intermediates/richtest_downsamp/watershed840_neg_edge_pcts.rds")$neg_pct

# percent negative edges
hab_neg_edges <- readRDS("../intermediates/habitat/hab_downsamp918_neg_pct.rds") 
hab_neg_pct <- hab_neg_edges$neg_pct


grad_neg_edges <- readRDS("../intermediates/gradient/grad_downsamp721_neg_pct.rds")

grad_neg_pct <- grad_neg_edges$neg_pct


regress_df$neg_pct <- c(ws_neg_edges, hab_neg_pct, grad_neg_pct)

write.csv(regress_df, "../intermediates/richtest_downsamp/regression_numbers_alldownsamp.csv")
```

```{r}
ratio_lm <- summary(lm(robustness ~ ratio, data = regress_df))

ratio_pl <- ggplot(data = regress_df, aes(x = ratio, y = robustness, color = category, shape = kingdom)) +
      stat_smooth(method = "lm", 
                  aes(group = 1),
              formula = y ~ x, 
              geom = "smooth",
              se = F,
              color = "darkgrey",
              alpha = 0.5) +
    geom_point(size = 5, alpha = 0.8) +
  annotate("text", x = 6, y = 0.03, label = paste("Adj_R2 =", round(ratio_lm$adj.r.squared, 3))) +
  annotate("text", x = 6, y = 0.01, label = paste("P =", round(ratio_lm$coefficients[2,4], 3))) +
  theme_classic() +
  theme(axis.text = element_text(color = "black", size = 10)) +
  guides(color = "none", shape = "none") +
  labs(x = "Ratio of edges to nodes", y = "Robustness") 
  # scale_y_continuous(breaks = seq(0, 0.3, 0.1),
  #                             limits = c(c(0, 0.3)))


pct_neg_lm <- summary(lm(robustness ~ neg_pct, data = regress_df))

pct_neg_pl <- ggplot(data = regress_df, aes(x = neg_pct, y = robustness, color = category, shape = kingdom)) +
      stat_smooth(method = "lm", 
                  aes(group = 1),
              formula = y ~ x, 
              geom = "smooth",
              se = F,
              color = "darkgrey",
              alpha = 0.5) +
    geom_point(size = 5, alpha = 0.8) +
  annotate("text", x = 0.28, y = 0.03, label = paste("Adj_R2 =", round(pct_neg_lm$adj.r.squared, 3))) +
  annotate("text", x = 0.28, y = 0.01, label = paste("P =", round(pct_neg_lm$coefficients[2,4], 3))) +
  theme_classic() +
  theme(axis.text = element_text(color = "black", size = 10)) +
  guides(color = "none", shape = "none") +
  labs(x = "Proportion of Negative Edges", y = "Robustness") 
  # scale_y_continuous(breaks = seq(0, 0.3, 0.1),
  #                             limits = c(c(0, 0.3)))
```



Plot!

```{r}
mod_lm <- summary(lm(robustness ~ modularity, data = regress_df))

mod_pl <- ggplot(data = regress_df, aes(x = modularity, y = robustness, color = category, shape = kingdom)) +
      stat_smooth(method = "lm", 
                  aes(group = 1),
              formula = y ~ x, 
              geom = "smooth",
              se = F,
              color = "darkgrey",
              alpha = 0.5) +
    geom_point(size = 5, alpha = 0.8) +
  annotate("text", x = 0.67, y = 0.03, label = paste("Adj_R2 =", round(mod_lm$adj.r.squared, 3))) +
  annotate("text", x = 0.67, y = 0.01, label = paste("P =", round(mod_lm$coefficients[2,4], 3))) +
  theme_classic() +
  theme(axis.text = element_text(color = "black", size = 10)) +
  guides(color = "none", shape = "none") +
  labs(x = "Modularity", y = "Robustness") 
  # scale_y_continuous(breaks = seq(0, 0.3, 0.1),
  #                             limits = c(c(0, 0.3)))



rich_lm <- summary(lm(robustness ~ richness, data = regress_df))

rich_pl <- ggplot(data = regress_df, aes(x = richness, y = robustness, color = category, shape = kingdom)) +
      stat_smooth(method = "lm", 
                  aes(group = 1),
              formula = y ~ x, 
              geom = "smooth",
              se = F,
              color = "darkgrey",
              alpha = 0.5) +
    geom_point(size = 5, alpha = 0.8) +
  annotate("text", x = 875, y = 0.03, label = paste("Adj_R2 =", round(rich_lm$adj.r.squared, 3))) +
  annotate("text", x = 875, y = 0.01, label = paste("P =", round(rich_lm$coefficients[2,4], 3))) +
  theme_classic() +
  theme(axis.text = element_text(color = "black", size = 10)) +
  guides(color = "none", shape = "none") +
  labs(x = "Richness", y = "Robustness") 
  # scale_y_continuous(breaks = seq(0, 0.3, 0.1),
  #                             limits = c(c(0, 0.3)))


conn_lm <- summary(lm(robustness ~ connectance, data = regress_df))

conn_pl <- ggplot(data = regress_df, aes(x = connectance, y = robustness, color = category, shape = kingdom)) +
      stat_smooth(method = "lm", 
                  aes(group = 1),
              formula = y ~ x, 
              geom = "smooth",
              se = F,
              color = "darkgrey",
              alpha = 0.5) +
    geom_point(size = 5, alpha = 0.8) +
  annotate("text", x = 0.0085, y = 0.03, label = paste("Adj_R2 =", round(conn_lm$adj.r.squared, 3))) +
  annotate("text", x = 0.0085, y = 0.01, label = paste("P =", round(conn_lm$coefficients[2,4], 3))) +
  theme_classic() +
  theme(axis.text = element_text(color = "black", size = 10)) +
  labs(x = "Connectance", y = "Robustness") 
  # scale_y_continuous(breaks = seq(0, 0.3, 0.1),
  #                             limits = c(c(0, 0.3)))
```


```{r}
library(patchwork)

library(cowplot)
my_legend <- get_legend(conn_pl)
library(ggpubr)
pp <- as_ggplot(my_legend)


conn_pl <- conn_pl + theme(legend.position = "none")

plots <- mod_pl + rich_pl + conn_pl + ratio_pl + pct_neg_pl + pp + plot_layout(ncol = 3)

ggsave("../figures/aug2024_revisions/all_DOWNSAMPLEDv2_networks_robustness_vs_complexity_regressions.pdf", width = 14, height=9)
```

```{r}
# mod_lm_nomf <- summary(lm(robustness ~ modularity, data = regress_df_nomarfung))
# 
# mod_pl_nomf <- ggplot(data = regress_df_nomarfung, aes(x = modularity, y = robustness, color = habitat, shape = kingdom)) +
#   geom_point(size = 3) +
#       stat_smooth(method = "lm", 
#                   aes(group = 1),
#               formula = y ~ x, 
#               geom = "smooth",
#               se = F,
#               color = "black") +
#   annotate("text", x = 0.52, y = 0.11, label = paste("Adj_R2 =", round(mod_lm_nomf$adj.r.squared, 3))) +
#   annotate("text", x = 0.52, y = 0.095, label = paste("P =", round(mod_lm_nomf$coefficients[2,4], 3))) +
#   theme_classic() +
#   theme(axis.text = element_text(color = "black", size = 10)) +
#   guides(color = "none", shape = "none") +
#   labs(x = "Modularity", y = "Robustness")
# 
# 
# 
# rich_lm_nomf <- summary(lm(robustness ~ richness, data = regress_df_nomarfung))
# 
# rich_pl_nomf <- ggplot(data = regress_df_nomarfung, aes(x = richness, y = robustness, color = habitat, shape = kingdom)) +
#   geom_point(size = 3) +
#       stat_smooth(method = "lm", 
#                   aes(group = 1),
#               formula = y ~ x, 
#               geom = "smooth",
#               se = F,
#               color = "black") +
#   annotate("text", x = 7500, y = 0.11, label = paste("Adj_R2 =", round(rich_lm_nomf$adj.r.squared, 3))) +
#   annotate("text", x = 7500, y = 0.095, label = paste("P =", round(rich_lm_nomf$coefficients[2,4], 3))) +
#   theme_classic() +
#   theme(axis.text = element_text(color = "black", size = 10)) +
#   guides(color = "none", shape = "none") +
#   labs(x = "Richness", y = "Robustness")
# 
# 
# 
# conn_lm_nomf <- summary(lm(robustness ~ connectance, data = regress_df_nomarfung))
# 
# conn_pl_nomf <- ggplot(data = regress_df_nomarfung, aes(x = connectance, y = robustness, color = habitat, shape = kingdom)) +
#   geom_point(size = 3) +
#       stat_smooth(method = "lm", 
#                   aes(group = 1),
#               formula = y ~ x, 
#               geom = "smooth",
#               se = F,
#               color = "black") +
#   annotate("text", x = 0.0023, y = 0.11, label = paste("Adj_R2 =", round(conn_lm_nomf$adj.r.squared, 3))) +
#   annotate("text", x = 0.0023, y = 0.095, label = paste("P =", round(conn_lm_nomf$coefficients[2,4], 3))) +
#   theme_classic() +
#   theme(axis.text = element_text(color = "black", size = 10)) +
#   labs(x = "Connectance", y = "Robustness")
```


