---
title: "13_robustness"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message=FALSE}
library(dplyr)
library(igraph)
library(ggnetwork)
library(intergraph)
library(brainGraph)
library(patchwork)

options(bitmapType='cairo')
```

```{r}
# read in data
fung_net <- readRDS("../intermediates/global/fung20_igraph.rds")
bact_net <- readRDS("../intermediates/global/bact20_igraph.rds")
cross_net <- readRDS("../intermediates/global/cross20_igraph.rds")
```

```{r}

# import metadata
fung_abun <- readRDS("../intermediates/global/fully_filtered_p20_fungal_otu_table_matched_up.rds")
bact_abun <- readRDS("../intermediates/global/fully_filtered_p20_bact_otu_table_matched_up.rds")

fung_abun <- fung_abun[rownames(fung_abun)!="dummy",]
bact_abun <- bact_abun[rownames(bact_abun)!="dummy",]

cross_data_names <- c(rownames(fung_abun),rownames(bact_abun))

```

```{r}
# robustness test

# Calculate node removal robustness
# fung_node_robustness <- robustness(fung_net, type = "vertex", "degree")
# fung_node_robustness$domain <- "fungi"
# 
# # Calculate node removal robustness
# bact_node_robustness <- robustness(bact_net, type = "vertex", "degree")
# bact_node_robustness$domain <- "bacteria"
# 
# # Calculate node removal robustness
# cross_node_robustness <- robustness(cross_net, type = "vertex", "degree")
# cross_node_robustness$domain <- "cross"




# Calculate betweenness removal robustness
fung_btwn_robustness <- robustness(fung_net, type = "vertex", "btwn.cent")
fung_btwn_robustness$domain <- "Fungi"

# Calculate betweenness removal robustness
bact_btwn_robustness <- robustness(bact_net, type = "vertex", "btwn.cent")
bact_btwn_robustness$domain <- "Bacteria"

# Calculate betweenness removal robustness
cross_btwn_robustness <- robustness(cross_net, type = "vertex", "btwn.cent")
cross_btwn_robustness$domain <- "Cross"



#all_node_robustness_degree <- do.call("rbind", list(fung_node_robustness, bact_node_robustness, cross_node_robustness))

all_node_robustness_btwn <- do.call("rbind", list(fung_btwn_robustness, bact_btwn_robustness, cross_btwn_robustness))


#saveRDS(all_node_robustness_degree, "../intermediates/global/robustness_degree_results.rds")
saveRDS(all_node_robustness_btwn, "../intermediates/global/robustness_btwn_results_fb.rds")

```

```{r}
# a <- ggplot(all_node_robustness_degree, aes(x=removed.pct, y=comp.pct, group=domain, color=domain)) +
#   geom_line() +
#   labs(x="Percentage of nodes removed", y="Size of largest connected component",
#        title="Degree-based attack")


all_node_robustness_btwn <- readRDS("../intermediates/global/robustness_btwn_results_fb.rds")
all_node_robustness_btwn$domain <- factor(all_node_robustness_btwn$domain, c("Fungi", "Bacteria", "Cross"))

test_lm <- lm(comp.pct ~ removed.pct + domain, data = all_node_robustness_btwn)

b <- ggplot(all_node_robustness_btwn, aes(x=removed.pct, y=comp.pct, group=domain, color=domain)) +
  geom_point(size=0.5, alpha=0.6) +
  labs(x="Percentage of nodes removed", y="Size of largest connected component",color="Domain") +
  theme(legend.key = element_rect(fill="white")) +
  #geom_smooth(method="lm", se=FALSE) +
  theme(panel.border = element_blank(), panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(), axis.line = element_line(colour = "black"),
        panel.background=element_blank()) +
       # axis.title = element_text(size=14)) +
  scale_color_manual(values=c("#D81B60", "#1E88E5", "#DEA805")) +
  # theme(legend.text = element_text(size=12)) +
  #  theme(legend.title = element_text(size=14)) +
  #  guides(color = guide_legend(override.aes = list(size=8))) +
  theme(axis.title.y = element_text(margin = margin(t = 0, r = 10, b = 0, l = 0))) +
  theme(axis.title.x = element_text(margin = margin(t = 10, r = 0, b = 0, l = 0))) +
  scale_x_continuous(limits = c(0,1), expand = c(0, 0)) +
  scale_y_continuous(limits = c(0,1), expand = c(0, 0)) 



#> $vibrant
#>  vibrant_orange    vibrant_blue vibrant_magenta    vibrant_cyan 
#>       "#ee7733"       "#0077bb"       "#ee3377"       "#33bbee" 
#>     vibrant_red    vibrant_teal     bright_grey 
#>       "#cc3311"       "#009988"       "#bbbbbb" 

#library(ggpubr


#c <- ggarrange(a,b, nrow=1, common.legend = TRUE, legend = "right")

ggsave("../figures/global/prev20_robustness_curves_fb_smaller_axes.png", width=9, height=6)

```






