---
title: "17_whats_in_each_network"
output: html_document
date: "2023-09-16"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(ggplot2)
library(dplyr)
library(patchwork)

options(bitmapType='cairo')
```

```{r}
# metadata
fung_meta <- readRDS("../intermediates/global/fully_filtered_p20_fungal_otu_metadata_matched_up.rds")
bact_meta <- readRDS("../intermediates/global/fully_filtered_p20_bact_otu_metadata_matched_up.rds")


fung_meta$trophic[!(fung_meta$trophic %in% c("PrimaryProducer", "Environmental"))] <- "Consumer"
fung_meta$trophic[fung_meta$trophic=="Unknown"] <- "Consumer"
fung_meta$trophic[fung_meta$sample_type=="WoodArthropod"] <- "Consumer"
fung_meta$trophic[fung_meta$sample_type=="Coral"] <- "Consumer"
```

Watershed - habitat % plot and replicate bars

```{r}
how_many <- fung_meta %>% group_by(habitat, empo_3, trophic) %>% summarize(count = n())

empo <- sort(unique(fung_meta$empo_3), decreasing = TRUE)

how_many$empo_3 <- factor(how_many$empo_3, levels = empo)
how_many$trophic <- factor(how_many$trophic, levels = c("Environmental", "PrimaryProducer", "Consumer"))

# Stacked + percent
wshed_hab_pct <- ggplot(how_many, aes(fill=habitat, y=count, x=empo_3)) + 
            geom_bar(position="fill", stat="identity") + 
            coord_flip() +
            labs(x = "Sample Type (EMPO3)", y = "Habitat %", title = "Watershed Networks",
                 fill = "Habitat") +
  theme(panel.border = element_blank(), panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(), axis.line = element_line(colour = "black"),
        panel.background=element_blank(),
        axis.title = element_text(size=16),
        title=element_text(size=18),
        axis.ticks.y = element_blank(),
        axis.text = element_text(color="black", size = 12)) +
  scale_fill_manual(values = c("#77B6EA", "#373F51", "#BC9CB0")) +
    scale_y_continuous(expand = c(0, 0)) 


wshed_counts <- ggplot(how_many, aes(fill=trophic, y=count, x=empo_3)) + 
            geom_bar(stat="identity") + 
            coord_flip() +
            labs(x = "Sample Type (EMPO3)", y = "Number of Samples", fill = "Trophic Level") +
  theme(panel.border = element_blank(), panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(), axis.line = element_line(colour = "black"),
        panel.background=element_blank(),
        axis.title = element_text(size=16),
        title=element_text(size=18),
        axis.ticks.y = element_blank(),
        axis.text.y = element_blank(),
        axis.title.y = element_blank(),
        axis.text = element_text(color="black", size = 12)) +
  scale_fill_brewer(palette = "Set2") +
    scale_y_continuous(expand = c(0, 0)) 

wshed_both <- wshed_hab_pct + wshed_counts
wshed_both <- wshed_both + plot_layout(guides = "collect")
  

ggsave("../figures/finals/global/watershed_how_many.pdf", wshed_both, width = 9, height = 6)

```


Habitat - # of samples by empo for each habitat

```{r}
all_empos <- unique(how_many$empo_3)

terr_empos <- c("Animal corpus", "Plant corpus", "Surface (non-saline)", "Plant rhizosphere", "Soil (non-saline)")
terr_empos <- sort(terr_empos)


add_zeros <- function(empo_vec, habitat) {
  not_there <- setdiff(all_empos, empo_vec)
  nt_num <- length(not_there)
  
  new_df <- data.frame(empo = c(empo_vec, not_there),
                       count = c(rep(17,5), rep(0,nt_num)),
                       habitat = rep(habitat, length(all_empos)))
  new_df$trophic <- how_many$trophic[match(new_df$empo, how_many$empo_3)]
  
  return(new_df)
}

terr_df <- add_zeros(terr_empos, "Terrestrial")

mar_empos <- sort(unique(fung_meta$empo_3[fung_meta$habitat=="Marine"]))
mar_df <- add_zeros(mar_empos, "Marine")

str_empos <- sort(unique(fung_meta$empo_3[fung_meta$habitat=="Riverine"]))
str_df <- add_zeros(str_empos, "Stream")

hab_dfs <- list(mar_df, str_df, terr_df)

hab_counts <- list()

habitats = c("Marine", "Stream", "Terrestrial")

for (i in 1:length(habitats)) {
  dat <- hab_dfs[[i]]
  
  pl <- ggplot(dat, aes(fill=trophic, y=count, x=factor(empo, levels = sort(empo, decreasing = T)))) + 
            geom_bar(stat="identity") + 
            coord_flip() +
            labs(x = "Sample Type (EMPO3)", y = "Number of Samples", fill = "Trophic Level",
                 title = habitats[i]) +
  theme(panel.border = element_blank(), panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(), axis.line = element_line(colour = "black"),
        panel.background=element_blank(),
        axis.title = element_text(size=16),
        title=element_text(size=18),
        axis.ticks.y = element_blank(),
        axis.text = element_text(color="black", size = 12)) +
  scale_fill_brewer(palette = "Set2") +
    scale_y_continuous(breaks = seq(0,17, 17), limits = c(0,17), expand = c(0,0))
  
  hab_counts[[i]] <- pl

}

hab_counts[[2]] <- hab_counts[[2]] +
  theme(axis.text.y = element_blank(),
        axis.title.y = element_blank())

hab_counts[[3]] <- hab_counts[[3]] +
  theme(axis.text.y = element_blank(),
        axis.title.y = element_blank())

# includes site plot from chunk below (run that first)
hab_all <- wrap_plots(hab_counts) + site_counts +  plot_layout(guides = "collect", nrow = 1)


ggsave("../figures/finals/global/habitat_gradient_how_many.pdf", hab_all, width = 13, height = 5.5)


```


Gradient = # of samples per empo (same for all sites)

```{r}
fung_meta_terr <- fung_meta[fung_meta$habitat=="Terrestrial",]

fung_terr_samp_counts <- fung_meta_terr %>% dplyr::group_by(empo_3, site_name) %>% dplyr::summarise(sum = n())

fung_terr_min_df <- fung_terr_samp_counts %>% dplyr::group_by(empo_3) %>% dplyr::slice(which.min(sum))

empos <- unique(fung_terr_min_df$empo_3)
# need to remove animal distal gut and animal surface because these are not present in Ridge site
empos <- empos[!empos %in% c("Animal distal gut", "Animal surface")]

# update min count df
fung_terr_min_df <- fung_terr_min_df[fung_terr_min_df$empo_3 %in% empos,]

fung_terr_min_df$trophic <- how_many$trophic[match(fung_terr_min_df$empo_3, how_many$empo_3)]


grad_df <- dplyr::select(fung_terr_min_df, empo_3, sum)

not_there <- setdiff(all_empos, grad_df$empo_3)
nt_num <- length(not_there)

new_df <- data.frame(empo = c(grad_df$empo_3, not_there),
                     count = c(grad_df$sum, rep(0,nt_num)),
                     habitat = rep("Gradient", length(all_empos)))
new_df$trophic <- how_many$trophic[match(new_df$empo, how_many$empo_3)]


site_counts <- ggplot(new_df, aes(fill=trophic, y=count, x=factor(empo, levels = sort(empo, decreasing = T)))) + 
            geom_bar(stat="identity") + 
            coord_flip() +
            labs(x = "Sample Type (EMPO3)", y = "Number of Samples", fill = "Trophic Level",
                 title = "Gradient") +
  theme(panel.border = element_blank(), panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(), axis.line = element_line(colour = "black"),
        panel.background=element_blank(),
        axis.title = element_text(size=16),
        title=element_text(size=18),
        axis.ticks.y = element_blank(),
        axis.title.y = element_blank(),
        axis.text.y = element_blank(),
        axis.text = element_text(color="black", size = 12)) +
  scale_fill_manual(values = wes_palette("GrandBudapest1")) +
    scale_y_continuous(breaks = seq(0,13, 4), limits = c(0,13), expand = c(0,0))

pp <- paletteer_d("wesanderson::GrandBudapest1")

ggsave("../figures/finals/global/gradient_how_many.pdf", site_counts, width = 7, height = 4)


```






